In [1]:
import pandas as pd

fahrzeug_11 = pd.read_csv(
    "data/Fahrzeug/Fahrzeuge_OEM1_Typ11.csv",
    sep=","
)

bom_11 = pd.read_csv(
    "data/Fahrzeug/Bestandteile_Fahrzeuge_OEM1_Typ11.csv",
    sep=";"
)

fahrzeug_21 = pd.read_csv(
    "data/Fahrzeug/Fahrzeuge_OEM2_Typ21.csv",
    sep=","
)

bom_21 = pd.read_csv(
    "data/Fahrzeug/Bestandteile_Fahrzeuge_OEM2_Typ21.csv",
    sep=";"
)

In [2]:
print(fahrzeug_11.shape)
print(bom_11.shape)

print(fahrzeug_21.shape)
print(bom_21.shape)

(1977164, 9)
(1977164, 6)
(512354, 10)
(512354, 6)

In [3]:
print("OEM1")
print("Vehicle IDs unique:", fahrzeug_11["ID_Fahrzeug"].is_unique)
print("BOM IDs unique:", bom_11["ID_Fahrzeug"].is_unique)

print(
    "Vehicles missing from BOM:",
    len(set(fahrzeug_11["ID_Fahrzeug"]) - set(bom_11["ID_Fahrzeug"]))
)

print(
    "BOM IDs missing from vehicles:",
    len(set(bom_11["ID_Fahrzeug"]) - set(fahrzeug_11["ID_Fahrzeug"]))
)


print("\nOEM2")
print("Vehicle IDs unique:", fahrzeug_21["ID_Fahrzeug"].is_unique)
print("BOM IDs unique:", bom_21["ID_Fahrzeug"].is_unique)

print(
    "Vehicles missing from BOM:",
    len(set(fahrzeug_21["ID_Fahrzeug"]) - set(bom_21["ID_Fahrzeug"]))
)

print(
    "BOM IDs missing from vehicles:",
    len(set(bom_21["ID_Fahrzeug"]) - set(fahrzeug_21["ID_Fahrzeug"]))
)


vehicle_11 = fahrzeug_11.merge(
    bom_11[
        [
            "ID_Fahrzeug",
            "ID_Karosserie",
            "ID_Schaltung",
            "ID_Sitze",
            "ID_Motor"
        ]
    ],
    on="ID_Fahrzeug",
    how="left",
    validate="one_to_one"
)

vehicle_21 = fahrzeug_21.merge(
    bom_21[
        [
            "ID_Fahrzeug",
            "ID_Karosserie",
            "ID_Schaltung",
            "ID_Sitze",
            "ID_Motor"
        ]
    ],
    on="ID_Fahrzeug",
    how="left",
    validate="one_to_one"
)


print("\nMerged shapes:")
print("OEM1:", vehicle_11.shape)
print("OEM2:", vehicle_21.shape)


print("\nMissing installed components OEM1:")
print(
    vehicle_11[
        [
            "ID_Karosserie",
            "ID_Schaltung",
            "ID_Sitze",
            "ID_Motor"
        ]
    ].isna().sum()
)

print("\nMissing installed components OEM2:")
print(
    vehicle_21[
        [
            "ID_Karosserie",
            "ID_Schaltung",
            "ID_Sitze",
            "ID_Motor"
        ]
    ].isna().sum()
)

OEM1
Vehicle IDs unique: True
BOM IDs unique: True
Vehicles missing from BOM: 0
BOM IDs missing from vehicles: 0

OEM2
Vehicle IDs unique: True
BOM IDs unique: True
Vehicles missing from BOM: 0
BOM IDs missing from vehicles: 0

Merged shapes:
OEM1: (1977164, 13)
OEM2: (512354, 14)

Missing installed components OEM1:
ID_Karosserie    0
ID_Schaltung     0
ID_Sitze         0
ID_Motor         0
dtype: int64

Missing installed components OEM2:
ID_Karosserie    0
ID_Schaltung     0
ID_Sitze         0
ID_Motor         0
dtype: int64

In [4]:
vehicle_11 = fahrzeug_11.merge(
    bom_11[
        [
            "ID_Fahrzeug",
            "ID_Karosserie",
            "ID_Schaltung",
            "ID_Sitze",
            "ID_Motor"
        ]
    ],
    on="ID_Fahrzeug",
    how="left",
    validate="one_to_one"
)

vehicle_21 = fahrzeug_21.merge(
    bom_21[
        [
            "ID_Fahrzeug",
            "ID_Karosserie",
            "ID_Schaltung",
            "ID_Sitze",
            "ID_Motor"
        ]
    ],
    on="ID_Fahrzeug",
    how="left",
    validate="one_to_one"
)

vehicle_11 = vehicle_11.drop(
    columns=["Unnamed: 0", "X1"]
)

vehicle_21 = vehicle_21.drop(
    columns=[
        col for col in ["Unnamed: 0", "X1"]
        if col in vehicle_21.columns
    ]
)

In [5]:
vehicle_11.head()

,ID_Fahrzeug,Produktionsdatum,Herstellernummer,Werksnummer,Fehlerhaft,Fehlerhaft_Datum,Fehlerhaft_Fahrleistung,ID_Karosserie,ID_Schaltung,ID_Sitze,ID_Motor
0,11-1-11-1,2008-11-18,1,11,0,NaN,0,K4-112-1121-3,K3SG1-105-1051-32,K2LE1-109-1091-2,K1BE1-101-1011-7
1,11-1-11-2,2008-11-18,1,11,0,NaN,0,K4-112-1121-4,K3SG1-105-1051-141,K2ST1-109-1092-5,K1BE1-101-1011-12
2,11-1-11-3,2008-11-19,1,11,0,NaN,0,K4-112-1121-7,K3SG1-105-1051-106,K2ST1-109-1092-57,K1BE1-101-1011-38
3,11-1-11-4,2008-11-19,1,11,0,NaN,0,K4-112-1121-9,K3SG1-105-1051-21,K2ST1-109-1092-91,K1BE1-101-1011-97
4,11-1-11-5,2008-11-19,1,11,0,NaN,0,K4-112-1121-11,K3SG1-105-1051-59,K2ST1-109-1092-4,K1BE1-101-1011-65

In [6]:
def get_prefix(series):
    return series.str.split("-").str[0]

print("OEM1 Type11 component families")

for col in [
    "ID_Karosserie",
    "ID_Schaltung",
    "ID_Sitze",
    "ID_Motor"
]:
    print(f"\n{col}")
    print(
        get_prefix(vehicle_11[col])
        .value_counts()
    )


print("\nOEM2 Type21 component families")

for col in [
    "ID_Karosserie",
    "ID_Schaltung",
    "ID_Sitze",
    "ID_Motor"
]:
    print(f"\n{col}")
    print(
        get_prefix(vehicle_21[col])
        .value_counts()
    )

OEM1 Type11 component families

ID_Karosserie
ID_Karosserie
K4    1977164
Name: count, dtype: int64

ID_Schaltung
ID_Schaltung
K3SG1    1581724
K3AG1     395440
Name: count, dtype: int64

ID_Sitze
ID_Sitze
K2ST1    1581267
K2LE1     395897
Name: count, dtype: int64

ID_Motor
ID_Motor
K1DI1    988744
K1BE1    988420
Name: count, dtype: int64

OEM2 Type21 component families

ID_Karosserie
ID_Karosserie
K6    512354
Name: count, dtype: int64

ID_Schaltung
ID_Schaltung
K3SG2    409700
K3AG2    102654
Name: count, dtype: int64

ID_Sitze
ID_Sitze
K2ST2    409543
K2LE2    102811
Name: count, dtype: int64

ID_Motor
ID_Motor
K1BE2    269276
K1DI2    243078
Name: count, dtype: int64

In [7]:
component_families = [
    # OEM1 Type11
    "K4",
    "K3SG1",
    "K3AG1",
    "K2ST1",
    "K2LE1",
    "K1DI1",
    "K1BE1",

    # OEM2 Type21
    "K6",
    "K3SG2",
    "K3AG2",
    "K2ST2",
    "K2LE2",
    "K1BE2",
    "K1DI2",
]

In [8]:
from pathlib import Path

COMPONENT_FOLDER = Path("data/Komponente")

for path in sorted(COMPONENT_FOLDER.iterdir()):
    print(path.name)

for family in component_families:
    matches = list(COMPONENT_FOLDER.glob(f"*{family}*"))

    print(f"\n{family}:")
    for path in matches:
        print("   ", path.name)

Bestandteile_Komponente_K1BE1.csv
Bestandteile_Komponente_K1BE2.csv
Bestandteile_Komponente_K1DI1.csv
Bestandteile_Komponente_K1DI2.csv
Bestandteile_Komponente_K2LE1.csv
Bestandteile_Komponente_K2LE2.csv
Bestandteile_Komponente_K2ST1.csv
Bestandteile_Komponente_K2ST2.csv
Bestandteile_Komponente_K3AG1.csv
Bestandteile_Komponente_K3AG2.csv
Bestandteile_Komponente_K3SG1.csv
Bestandteile_Komponente_K3SG2.csv
Bestandteile_Komponente_K4.csv
Bestandteile_Komponente_K5.csv
Bestandteile_Komponente_K6.csv
Bestandteile_Komponente_K7.csv
Komponente_K1BE1.csv
Komponente_K1BE2.csv
Komponente_K1DI1.csv
Komponente_K1DI2.csv
Komponente_K1DI2.txt
Komponente_K2LE1.csv
Komponente_K2LE1.txt
Komponente_K2LE2.csv
Komponente_K2LE2.txt
Komponente_K2ST1.csv
Komponente_K2ST1.txt
Komponente_K2ST2.csv
Komponente_K3AG1.csv
Komponente_K3AG2.csv
Komponente_K3AG2.txt
Komponente_K3SG1.csv
Komponente_K3SG2.csv
Komponente_K4.csv
Komponente_K5.csv
Komponente_K6.csv
Komponente_K7.csv
Komponente_K7.txt

K4:
    Bestandteile_Komponente_K4.csv
    Komponente_K4.csv

K3SG1:
    Bestandteile_Komponente_K3SG1.csv
    Komponente_K3SG1.csv

K3AG1:
    Bestandteile_Komponente_K3AG1.csv
    Komponente_K3AG1.csv

K2ST1:
    Bestandteile_Komponente_K2ST1.csv
    Komponente_K2ST1.txt
    Komponente_K2ST1.csv

K2LE1:
    Bestandteile_Komponente_K2LE1.csv
    Komponente_K2LE1.txt
    Komponente_K2LE1.csv

K1DI1:
    Bestandteile_Komponente_K1DI1.csv
    Komponente_K1DI1.csv

K1BE1:
    Bestandteile_Komponente_K1BE1.csv
    Komponente_K1BE1.csv

K6:
    Bestandteile_Komponente_K6.csv
    Komponente_K6.csv

K3SG2:
    Bestandteile_Komponente_K3SG2.csv
    Komponente_K3SG2.csv

K3AG2:
    Bestandteile_Komponente_K3AG2.csv
    Komponente_K3AG2.txt
    Komponente_K3AG2.csv

K2ST2:
    Bestandteile_Komponente_K2ST2.csv
    Komponente_K2ST2.csv

K2LE2:
    Bestandteile_Komponente_K2LE2.csv
    Komponente_K2LE2.txt
    Komponente_K2LE2.csv

K1BE2:
    Bestandteile_Komponente_K1BE2.csv
    Komponente_K1BE2.csv

K1DI2:
    Bestandteile_Komponente_K1DI2.csv
    Komponente_K1DI2.txt
    Komponente_K1DI2.csv

In [9]:
from pathlib import Path
import pandas as pd
import csv

COMPONENT_FOLDER = Path("data/Komponente")


def detect_separator(path):
    with open(path, "r", encoding="utf-8", errors="replace") as f:
        first_line = f.readline()

    candidates = [",", ";", "\t", "|"]

    return max(
        candidates,
        key=lambda sep: first_line.count(sep)
    )


for family in component_families:

    component_path = (
        COMPONENT_FOLDER
        / f"Komponente_{family}.csv"
    )

    bom_path = (
        COMPONENT_FOLDER
        / f"Bestandteile_Komponente_{family}.csv"
    )

    print("\n" + "=" * 70)
    print(family)

    for label, path in [
        ("COMPONENT", component_path),
        ("COMPONENT BOM", bom_path)
    ]:

        sep = detect_separator(path)

        df_test = pd.read_csv(
            path,
            sep=sep,
            nrows=3
        )

        print(f"\n{label}")
        print("separator:", repr(sep))
        print("columns:")
        print(df_test.columns.tolist())

        display(df_test)

======================================================================
K4

COMPONENT
separator: ';'
columns:
['Unnamed: 0', 'X1', 'ID_Karosserie.x', 'Produktionsdatum.x', 'Herstellernummer.x', 'Werksnummer.x', 'Fehlerhaft.x', 'Fehlerhaft_Datum.x', 'Fehlerhaft_Fahrleistung.x', 'ID_Karosserie.y', 'Produktionsdatum.y', 'Herstellernummer.y', 'Werksnummer.y', 'Fehlerhaft.y', 'Fehlerhaft_Datum.y', 'Fehlerhaft_Fahrleistung.y']

,Unnamed: 0,X1,ID_Karosserie.x,Produktionsdatum.x,Herstellernummer.x,Werksnummer.x,Fehlerhaft.x,Fehlerhaft_Datum.x,Fehlerhaft_Fahrleistung.x,ID_Karosserie.y,Produktionsdatum.y,Herstellernummer.y,Werksnummer.y,Fehlerhaft.y,Fehlerhaft_Datum.y,Fehlerhaft_Fahrleistung.y
0,1,1,K4-112-1121-3,2008-11-12,112,1121,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,2,K4-112-1121-4,2008-11-12,112,1121,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,3,K4-112-1121-7,2008-11-12,112,1121,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

COMPONENT BOM
separator: ';'
columns:
['X1', 'ID_T30', 'ID_T31', 'ID_T32', 'ID_K4']

   X1           ID_T30           ID_T31          ID_T32          ID_K4
0   1  30-216-2161-242  31-217-2172-302  32-216-2162-21  K4-112-1121-1
1   2   30-216-2161-87  31-216-2161-242  32-216-2162-48  K4-112-1121-2
2   3  30-217-2171-214   31-217-2172-53  32-216-2162-62  K4-112-1121-3

======================================================================
K3SG1

COMPONENT
separator: ','
columns:
['Unnamed: 0', 'X1', 'ID_Schaltung.x', 'Produktionsdatum.x', 'Herstellernummer.x', 'Werksnummer.x', 'Fehlerhaft.x', 'Fehlerhaft_Datum.x', 'Fehlerhaft_Fahrleistung.x', 'ID_Schaltung.y', 'Produktionsdatum.y', 'Herstellernummer.y', 'Werksnummer.y', 'Fehlerhaft.y', 'Fehlerhaft_Datum.y', 'Fehlerhaft_Fahrleistung.y']

,Unnamed: 0,X1,ID_Schaltung.x,Produktionsdatum.x,Herstellernummer.x,Werksnummer.x,Fehlerhaft.x,Fehlerhaft_Datum.x,Fehlerhaft_Fahrleistung.x,ID_Schaltung.y,Produktionsdatum.y,Herstellernummer.y,Werksnummer.y,Fehlerhaft.y,Fehlerhaft_Datum.y,Fehlerhaft_Fahrleistung.y
0,1,1,K3SG1-105-1051-32,2008-11-13,105,1051,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,2,K3SG1-105-1051-141,2008-11-13,105,1051,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,3,K3SG1-105-1051-4,2008-11-12,105,1051,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

COMPONENT BOM
separator: ';'
columns:
['X1', 'ID_T21', 'ID_T22', 'ID_T23', 'ID_K3SG1']

   X1           ID_T21           ID_T22           ID_T23          ID_K3SG1
0   1  21-208-2081-357  22-205-2051-438   23-205-2051-33  K3SG1-105-1051-1
1   2  21-205-2051-218    22-206-2061-1  23-205-2051-133  K3SG1-105-1051-2
2   3   21-207-2072-49  22-205-2051-368  23-205-2051-160  K3SG1-105-1051-3

======================================================================
K3AG1

COMPONENT
separator: ','
columns:
['Unnamed: 0', 'X1', 'ID_Schaltung.x', 'Produktionsdatum.x', 'Herstellernummer.x', 'Werksnummer.x', 'Fehlerhaft.x', 'Fehlerhaft_Datum.x', 'Fehlerhaft_Fahrleistung.x', 'ID_Schaltung.y', 'Produktionsdatum.y', 'Herstellernummer.y', 'Werksnummer.y', 'Fehlerhaft.y', 'Fehlerhaft_Datum.y', 'Fehlerhaft_Fahrleistung.y', 'ID_Schaltung', 'Produktionsdatum', 'Herstellernummer', 'Werksnummer', 'Fehlerhaft', 'Fehlerhaft_Datum', 'Fehlerhaft_Fahrleistung']

,Unnamed: 0,X1,ID_Schaltung.x,Produktionsdatum.x,Herstellernummer.x,Werksnummer.x,Fehlerhaft.x,Fehlerhaft_Datum.x,Fehlerhaft_Fahrleistung.x,ID_Schaltung.y,...,Fehlerhaft.y,Fehlerhaft_Datum.y,Fehlerhaft_Fahrleistung.y,ID_Schaltung,Produktionsdatum,Herstellernummer,Werksnummer,Fehlerhaft,Fehlerhaft_Datum,Fehlerhaft_Fahrleistung
0,1,1,K3AG1-105-1051-36,2008-11-13,105,1051,0,NaN,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,2,K3AG1-105-1051-5,2008-11-13,105,1051,0,NaN,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,3,K3AG1-105-1051-28,2008-11-13,105,1051,0,NaN,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

COMPONENT BOM
separator: ';'
columns:
['X1', 'ID_T21', 'ID_T24', 'ID_T25', 'ID_K3AG1']

   X1           ID_T21          ID_T24         ID_T25          ID_K3AG1
0   1   21-205-2051-52  24-207-2072-43  25-206-2061-1  K3AG1-105-1051-1
1   2   21-208-2081-78  24-207-2072-12  25-206-2061-2  K3AG1-105-1051-2
2   3  21-205-2051-195  24-206-2062-52  25-206-2061-4  K3AG1-105-1051-3

======================================================================
K2ST1

COMPONENT
separator: ','
columns:
['Komponententyp', 'ID', 'Produktionsdatum', 'Herstellernummer', 'Werksnummer', 'Fehlerhaft', 'Fehlerhaft_Datum', 'Fehlerhaft_Fahrleistung']

,Komponententyp,ID,Produktionsdatum,Herstellernummer,Werksnummer,Fehlerhaft,Fehlerhaft_Datum,Fehlerhaft_Fahrleistung
0,K2ST1,K2ST1-109-1092-5,2008-11-12,109,1092,1,2010-09-04,47634.0
1,K2ST1,K2ST1-109-1092-1,2008-11-12,109,1092,0,NaN,0.0
2,K2ST1,K2ST1-109-1092-16,2008-11-13,109,1092,0,NaN,0.0

COMPONENT BOM
separator: ';'
columns:
['X1', 'X', 'ID_T11', 'ID_T12', 'ID_T13', 'ID_K2ST1']

   X1  X           ID_T11          ID_T12          ID_T13          ID_K2ST1
0   1  1  11-213-2131-128  12-212-2121-15  13-209-2091-25  K2ST1-109-1092-1
1   2  2  11-213-2131-134  12-212-2121-28   13-209-2092-7  K2ST1-109-1092-2
2   3  3  11-212-2121-107  12-212-2121-73  13-209-2092-69  K2ST1-109-1092-3

======================================================================
K2LE1

COMPONENT
separator: ','
columns:
['Komponententyp', 'ID', 'Produktionsdatum', 'Herstellernummer', 'Werksnummer', 'Fehlerhaft', 'Fehlerhaft_Datum', 'Fehlerhaft_Fahrleistung']

,Komponententyp,ID,Produktionsdatum,Herstellernummer,Werksnummer,Fehlerhaft,Fehlerhaft_Datum,Fehlerhaft_Fahrleistung
0,K2LE1,K2LE1-109-1091-2,2008-11-12,109,1091,1,2010-10-18,37080.0
1,K2LE1,K2LE1-109-1091-1,2008-11-12,109,1091,0,NaN,0.0
2,K2LE1,K2LE1-109-1091-12,2008-11-13,109,1091,0,NaN,0.0

COMPONENT BOM
separator: ';'
columns:
['Unnamed: 0', 'ID_T11', 'ID_T14', 'ID_T15', 'ID_K2LE1']

,Unnamed: 0,ID_T11,ID_T14,ID_T15,ID_K2LE1
0,1,11-215-2154-70,14-214-2142-8,15-209-2093-12,K2LE1-109-1091-1
1,2,11-215-2154-102,14-214-2142-11,15-209-2093-20,K2LE1-109-1091-2
2,3,11-212-2121-7,14-213-2132-1,15-210-2101-2,K2LE1-109-1091-3

======================================================================
K1DI1

COMPONENT
separator: ','
columns:
['Unnamed: 0', 'X1', 'ID_Motor.x', 'Produktionsdatum.x', 'Herstellernummer.x', 'Werksnummer.x', 'Fehlerhaft.x', 'Fehlerhaft_Datum.x', 'Fehlerhaft_Fahrleistung.x', 'ID_Motor.y', 'Produktionsdatum.y', 'Herstellernummer.y', 'Werksnummer.y', 'Fehlerhaft.y', 'Fehlerhaft_Datum.y', 'Fehlerhaft_Fahrleistung.y', 'ID_Motor', 'Produktionsdatum', 'Herstellernummer', 'Werksnummer', 'Fehlerhaft', 'Fehlerhaft_Datum', 'Fehlerhaft_Fahrleistung']

,Unnamed: 0,X1,ID_Motor.x,Produktionsdatum.x,Herstellernummer.x,Werksnummer.x,Fehlerhaft.x,Fehlerhaft_Datum.x,Fehlerhaft_Fahrleistung.x,ID_Motor.y,...,Fehlerhaft.y,Fehlerhaft_Datum.y,Fehlerhaft_Fahrleistung.y,ID_Motor,Produktionsdatum,Herstellernummer,Werksnummer,Fehlerhaft,Fehlerhaft_Datum,Fehlerhaft_Fahrleistung
0,1,1,K1DI1-101-1041-90,2008-11-13,101,1011,0,NaN,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,2,K1DI1-101-1041-12,2008-11-13,101,1011,1,2010-03-09,21509,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,5,K1DI1-101-1041-55,2008-11-13,101,1011,0,NaN,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

COMPONENT BOM
separator: ';'
columns:
['Unnamed: 0', 'ID_T1', 'ID_T2', 'ID_T5', 'ID_T6', 'ID_K1DI1']

,Unnamed: 0,ID_T1,ID_T2,ID_T5,ID_T6,ID_K1DI1
0,1,1-204-2044-27,2-201-2011-144,5-202-2012-89,6-203-2032-5,K1DI1-101-1041-1
1,2,1-202-2021-32,2-202-2022-577,5-202-2012-155,6-203-2032-79,K1DI1-101-1041-2
2,3,1-201-2011-238,2-202-2022-514,5-202-2012-199,6-203-2032-136,K1DI1-101-1041-3

======================================================================
K1BE1

COMPONENT
separator: ','
columns:
['Unnamed: 0', 'X1', 'ID_Motor', 'Herstellernummer', 'Werksnummer', 'Fehlerhaft', 'Fehlerhaft_Datum', 'Fehlerhaft_Fahrleistung', 'Produktionsdatum_Origin_01011970', 'origin']

,Unnamed: 0,X1,ID_Motor,Herstellernummer,Werksnummer,Fehlerhaft,Fehlerhaft_Datum,Fehlerhaft_Fahrleistung,Produktionsdatum_Origin_01011970,origin
0,1,1,K1BE1-101-1011-7,101,1011,0,NaN,0,14195,01-01-1970
1,2,2,K1BE1-101-1011-12,101,1011,0,NaN,0,14196,01-01-1970
2,3,3,K1BE1-101-1011-90,101,1011,0,NaN,0,14196,01-01-1970

COMPONENT BOM
separator: ';'
columns:
['Unnamed: 0', 'ID_T1', 'ID_T2', 'ID_T3', 'ID_T4', 'ID_K1BE1']

,Unnamed: 0,ID_T1,ID_T2,ID_T3,ID_T4,ID_K1BE1
0,1,1-201-2011-45,2-201-2011-161,3-202-2023-14,4-202-2023-20,K1BE1-101-1011-1
1,2,1-201-2011-429,2-201-2011-239,3-202-2023-16,4-202-2023-51,K1BE1-101-1011-2
2,3,1-201-2011-399,2-201-2011-220,3-202-2023-46,4-202-2023-93,K1BE1-101-1011-3

======================================================================
K6

COMPONENT
separator: ';'
columns:
['Unnamed: 0', 'X1', 'ID_Karosserie', 'Herstellernummer', 'Werksnummer', 'Fehlerhaft', 'Fehlerhaft_Datum', 'Fehlerhaft_Fahrleistung', 'Produktionsdatum_Origin_01011970', 'origin']

,Unnamed: 0,X1,ID_Karosserie,Herstellernummer,Werksnummer,Fehlerhaft,Fehlerhaft_Datum,Fehlerhaft_Fahrleistung,Produktionsdatum_Origin_01011970,origin
0,1,1,K6-113-1132-1,113,1132,0,NaN,0,14195,01-01-1970
1,2,2,K6-113-1132-2,113,1132,0,NaN,0,14195,01-01-1970
2,3,3,K6-113-1132-3,113,1132,0,NaN,0,14196,01-01-1970

COMPONENT BOM
separator: ';'
columns:
['X1', 'ID_T34', 'ID_T35', 'ID_T36', 'ID_T37', 'ID_K6']

,X1,ID_T34,ID_T35,ID_T36,ID_T37,ID_K6
0,1,34-217-2173-51,35-217-2173-9,36-219-2193-38,37-218-2183-22,K6-113-1132-1
1,2,34-217-2173-45,35-217-2173-64,36-219-2193-64,37-218-2183-52,K6-113-1132-2
2,3,34-218-2181-24,35-217-2173-107,36-218-2182-51,37-218-2182-11,K6-113-1132-3

======================================================================
K3SG2

COMPONENT
separator: ','
columns:
['Unnamed: 0', 'X1', 'ID_Schaltung', 'Herstellernummer', 'Werksnummer', 'Fehlerhaft', 'Fehlerhaft_Datum', 'Fehlerhaft_Fahrleistung', 'Produktionsdatum_Origin_01011970', 'origin']

,Unnamed: 0,X1,ID_Schaltung,Herstellernummer,Werksnummer,Fehlerhaft,Fehlerhaft_Datum,Fehlerhaft_Fahrleistung,Produktionsdatum_Origin_01011970,origin
0,1,1,K3SG2-108-1081-53,108,1081,0,NaN,0,14202,01-01-1970
1,2,2,K3SG2-105-1051-2,105,1051,1,2009-11-13,28919,14202,01-01-1970
2,3,3,K3SG2-105-1051-5,105,1051,0,NaN,0,14202,01-01-1970

COMPONENT BOM
separator: ';'
columns:
['X1', 'ID_T21', 'ID_T22', 'ID_T26', 'ID_K3SG2']

   X1           ID_T21           ID_T22         ID_T26          ID_K3SG2
0   1  21-208-2081-452  22-206-2061-105  26-206-2062-1  K3SG2-105-1051-1
1   2  21-208-2081-530  22-205-2051-315  26-206-2062-2  K3SG2-105-1051-2
2   3  21-208-2081-358  22-205-2051-265  26-206-2062-3  K3SG2-105-1051-3

======================================================================
K3AG2

COMPONENT
separator: ','
columns:
['Komponententyp', 'ID', 'Produktionsdatum', 'Herstellernummer', 'Werksnummer', 'Fehlerhaft', 'Fehlerhaft_Datum', 'Fehlerhaft_Fahrleistung']

,Komponententyp,ID,Produktionsdatum,Herstellernummer,Werksnummer,Fehlerhaft,Fehlerhaft_Datum,Fehlerhaft_Fahrleistung
0,K3AG2,K3AG2-108-1082-9,2008-11-13,108,1082,0,NaN,0.0
1,K3AG2,K3AG2-108-1082-11,2008-11-13,108,1082,1,2010-03-02,31859.0
2,K3AG2,K3AG2-108-1082-14,2008-11-13,108,1082,0,NaN,0.0

COMPONENT BOM
separator: ';'
columns:
['X1', 'ID_T21', 'ID_T24', 'ID_T27', 'ID_K3AG2']

   X1           ID_T21          ID_T24         ID_T27          ID_K3AG2
0   1  21-208-2081-525  24-207-2071-36  27-208-2082-1  K3AG2-108-1082-1
1   2  21-208-2081-108  24-208-2082-34  27-208-2082-2  K3AG2-108-1082-2
2   3  21-205-2051-233  24-207-2071-68  27-208-2082-4  K3AG2-108-1082-3

======================================================================
K2ST2

COMPONENT
separator: ';'
columns:
['Unnamed: 0', 'X1', 'ID_Sitze', 'Herstellernummer', 'Werksnummer', 'Fehlerhaft', 'Fehlerhaft_Datum', 'Fehlerhaft_Fahrleistung', 'Produktionsdatum_Origin_01011970', 'origin']

,Unnamed: 0,X1,ID_Sitze,Herstellernummer,Werksnummer,Fehlerhaft,Fehlerhaft_Datum,Fehlerhaft_Fahrleistung,Produktionsdatum_Origin_01011970,origin
0,1,1,K2ST2-109-1092-2,109,1092,0,NaN,0,14195,01-01-1970
1,2,2,K2ST2-109-1092-59,109,1092,0,NaN,0,14196,01-01-1970
2,3,3,K2ST2-109-1092-4,109,1092,0,NaN,0,14195,01-01-1970

COMPONENT BOM
separator: ';'
columns:
['Unnamed: 0', 'ID_T16', 'ID_T17', 'ID_T18', 'ID_K2ST2']

,Unnamed: 0,ID_T16,ID_T17,ID_T18,ID_K2ST2
0,1,16-215-2152-11,17-214-2141-3,18-209-2091-61,K2ST2-109-1092-1
1,2,16-212-2121-7,17-214-2141-20,18-209-2091-62,K2ST2-109-1092-2
2,3,16-215-2152-46,17-209-2092-21,18-209-2091-68,K2ST2-109-1092-3

======================================================================
K2LE2

COMPONENT
separator: ','
columns:
['Komponententyp', 'ID', 'Produktionsdatum', 'Herstellernummer', 'Werksnummer', 'Fehlerhaft', 'Fehlerhaft_Datum', 'Fehlerhaft_Fahrleistung']

,Komponententyp,ID,Produktionsdatum,Herstellernummer,Werksnummer,Fehlerhaft,Fehlerhaft_Datum,Fehlerhaft_Fahrleistung
0,K2LE2,K2LE2-111-1111-1,2008-11-12,111,1111,0,NaN,0.0
1,K2LE2,K2LE2-111-1111-4,2008-11-13,111,1111,0,NaN,0.0
2,K2LE2,K2LE2-111-1111-6,2008-11-13,111,1111,0,NaN,0.0

COMPONENT BOM
separator: ';'
columns:
['Unnamed: 0', 'ID_T16', 'ID_T19', 'ID_T20', 'ID_K2LE2']

   Unnamed: 0          ID_T16         ID_T19          ID_T20          ID_K2LE2
0           1  16-213-2132-44  19-215-2154-4  20-209-2091-23  K2LE2-111-1111-1
1           2  16-215-2152-68  19-214-2143-3   20-211-2111-6  K2LE2-111-1111-2
2           3   16-212-2121-9  19-214-2143-6  20-211-2111-10  K2LE2-111-1111-3

======================================================================
K1BE2

COMPONENT
separator: ';'
columns:
['Unnamed: 0', 'X1', 'ID_Motor', 'Herstellernummer', 'Werksnummer', 'Fehlerhaft', 'Fehlerhaft_Datum', 'Fehlerhaft_Fahrleistung', 'Produktionsdatum_Origin_01011970', 'origin']

,Unnamed: 0,X1,ID_Motor,Herstellernummer,Werksnummer,Fehlerhaft,Fehlerhaft_Datum,Fehlerhaft_Fahrleistung,Produktionsdatum_Origin_01011970,origin
0,1,1,K1BE2-101-1011-2,101,1011,0,NaN,0,14196,01-01-1970
1,2,2,K1BE2-101-1011-3,101,1011,0,NaN,0,14196,01-01-1970
2,3,3,K1BE2-101-1011-10,101,1011,0,NaN,0,14196,01-01-1970

COMPONENT BOM
separator: ';'
columns:
['Unnamed: 0', 'ID_T1', 'ID_T2', 'ID_T7', 'ID_T8', 'ID_K1BE2']

,Unnamed: 0,ID_T1,ID_T2,ID_T7,ID_T8,ID_K1BE2
0,1,1-202-2021-339,2-202-2022-171,7-203-2031-9,8-204-2041-12,K1BE2-101-1011-1
1,2,1-201-2011-57,2-201-2011-260,7-201-2012-30,8-204-2041-38,K1BE2-101-1011-2
2,3,1-202-2021-101,2-202-2022-335,7-201-2012-101,8-203-2031-8,K1BE2-101-1011-3

======================================================================
K1DI2

COMPONENT
separator: ','
columns:
['Komponententyp', 'ID', 'Produktionsdatum', 'Herstellernummer', 'Werksnummer', 'Fehlerhaft', 'Fehlerhaft_Datum', 'Fehlerhaft_Fahrleistung']

,Komponententyp,ID,Produktionsdatum,Herstellernummer,Werksnummer,Fehlerhaft,Fehlerhaft_Datum,Fehlerhaft_Fahrleistung
0,K1DI2,K1DI2-103-1031-2,2008-11-12,103,1031,0,NaN,0.0
1,K1DI2,K1DI2-103-1031-9,2008-11-13,103,1031,0,NaN,0.0
2,K1DI2,K1DI2-103-1031-10,2008-11-13,103,1031,0,NaN,0.0

COMPONENT BOM
separator: ';'
columns:
['Unnamed: 0', 'ID_T1', 'ID_T2', 'ID_T9', 'ID_T10', 'ID_K1DI2']

,Unnamed: 0,ID_T1,ID_T2,ID_T9,ID_T10,ID_K1DI2
0,1,1-204-2044-183,2-202-2022-551,9-204-2043-1,10-204-2042-3,K1DI2-103-1031-1
1,2,1-201-2011-246,2-202-2022-738,9-204-2043-35,10-204-2042-41,K1DI2-103-1031-2
2,3,1-201-2011-152,2-201-2011-181,9-203-2032-29,10-203-2032-8,K1DI2-103-1031-3

In [10]:
path = COMPONENT_FOLDER / "Komponente_K3SG1.csv"

sep = detect_separator(path)

test = pd.read_csv(
    path,
    sep=sep,
    nrows=3
)

print(test.columns.tolist())
display(test)

['Unnamed: 0', 'X1', 'ID_Schaltung.x', 'Produktionsdatum.x', 'Herstellernummer.x', 'Werksnummer.x', 'Fehlerhaft.x', 'Fehlerhaft_Datum.x', 'Fehlerhaft_Fahrleistung.x', 'ID_Schaltung.y', 'Produktionsdatum.y', 'Herstellernummer.y', 'Werksnummer.y', 'Fehlerhaft.y', 'Fehlerhaft_Datum.y', 'Fehlerhaft_Fahrleistung.y']

,Unnamed: 0,X1,ID_Schaltung.x,Produktionsdatum.x,Herstellernummer.x,Werksnummer.x,Fehlerhaft.x,Fehlerhaft_Datum.x,Fehlerhaft_Fahrleistung.x,ID_Schaltung.y,Produktionsdatum.y,Herstellernummer.y,Werksnummer.y,Fehlerhaft.y,Fehlerhaft_Datum.y,Fehlerhaft_Fahrleistung.y
0,1,1,K3SG1-105-1051-32,2008-11-13,105,1051,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,2,K3SG1-105-1051-141,2008-11-13,105,1051,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,3,K3SG1-105-1051-4,2008-11-12,105,1051,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
for family in component_families:
    path = COMPONENT_FOLDER / f"Komponente_{family}.csv"

    sep = detect_separator(path)

    test = pd.read_csv(
        path,
        sep=sep,
        nrows=1
    )

    print(
        family,
        "->",
        test.columns.tolist()
    )

K4 -> ['Unnamed: 0', 'X1', 'ID_Karosserie.x', 'Produktionsdatum.x', 'Herstellernummer.x', 'Werksnummer.x', 'Fehlerhaft.x', 'Fehlerhaft_Datum.x', 'Fehlerhaft_Fahrleistung.x', 'ID_Karosserie.y', 'Produktionsdatum.y', 'Herstellernummer.y', 'Werksnummer.y', 'Fehlerhaft.y', 'Fehlerhaft_Datum.y', 'Fehlerhaft_Fahrleistung.y']
K3SG1 -> ['Unnamed: 0', 'X1', 'ID_Schaltung.x', 'Produktionsdatum.x', 'Herstellernummer.x', 'Werksnummer.x', 'Fehlerhaft.x', 'Fehlerhaft_Datum.x', 'Fehlerhaft_Fahrleistung.x', 'ID_Schaltung.y', 'Produktionsdatum.y', 'Herstellernummer.y', 'Werksnummer.y', 'Fehlerhaft.y', 'Fehlerhaft_Datum.y', 'Fehlerhaft_Fahrleistung.y']
K3AG1 -> ['Unnamed: 0', 'X1', 'ID_Schaltung.x', 'Produktionsdatum.x', 'Herstellernummer.x', 'Werksnummer.x', 'Fehlerhaft.x', 'Fehlerhaft_Datum.x', 'Fehlerhaft_Fahrleistung.x', 'ID_Schaltung.y', 'Produktionsdatum.y', 'Herstellernummer.y', 'Werksnummer.y', 'Fehlerhaft.y', 'Fehlerhaft_Datum.y', 'Fehlerhaft_Fahrleistung.y', 'ID_Schaltung', 'Produktionsdatum', 'Herstellernummer', 'Werksnummer', 'Fehlerhaft', 'Fehlerhaft_Datum', 'Fehlerhaft_Fahrleistung']
K2ST1 -> ['Komponententyp', 'ID', 'Produktionsdatum', 'Herstellernummer', 'Werksnummer', 'Fehlerhaft', 'Fehlerhaft_Datum', 'Fehlerhaft_Fahrleistung']
K2LE1 -> ['Komponententyp', 'ID', 'Produktionsdatum', 'Herstellernummer', 'Werksnummer', 'Fehlerhaft', 'Fehlerhaft_Datum', 'Fehlerhaft_Fahrleistung']
K1DI1 -> ['Unnamed: 0', 'X1', 'ID_Motor.x', 'Produktionsdatum.x', 'Herstellernummer.x', 'Werksnummer.x', 'Fehlerhaft.x', 'Fehlerhaft_Datum.x', 'Fehlerhaft_Fahrleistung.x', 'ID_Motor.y', 'Produktionsdatum.y', 'Herstellernummer.y', 'Werksnummer.y', 'Fehlerhaft.y', 'Fehlerhaft_Datum.y', 'Fehlerhaft_Fahrleistung.y', 'ID_Motor', 'Produktionsdatum', 'Herstellernummer', 'Werksnummer', 'Fehlerhaft', 'Fehlerhaft_Datum', 'Fehlerhaft_Fahrleistung']
K1BE1 -> ['Unnamed: 0', 'X1', 'ID_Motor', 'Herstellernummer', 'Werksnummer', 'Fehlerhaft', 'Fehlerhaft_Datum', 'Fehlerhaft_Fahrleistung', 'Produktionsdatum_Origin_01011970', 'origin']
K6 -> ['Unnamed: 0', 'X1', 'ID_Karosserie', 'Herstellernummer', 'Werksnummer', 'Fehlerhaft', 'Fehlerhaft_Datum', 'Fehlerhaft_Fahrleistung', 'Produktionsdatum_Origin_01011970', 'origin']
K3SG2 -> ['Unnamed: 0', 'X1', 'ID_Schaltung', 'Herstellernummer', 'Werksnummer', 'Fehlerhaft', 'Fehlerhaft_Datum', 'Fehlerhaft_Fahrleistung', 'Produktionsdatum_Origin_01011970', 'origin']
K3AG2 -> ['Komponententyp', 'ID', 'Produktionsdatum', 'Herstellernummer', 'Werksnummer', 'Fehlerhaft', 'Fehlerhaft_Datum', 'Fehlerhaft_Fahrleistung']
K2ST2 -> ['Unnamed: 0', 'X1', 'ID_Sitze', 'Herstellernummer', 'Werksnummer', 'Fehlerhaft', 'Fehlerhaft_Datum', 'Fehlerhaft_Fahrleistung', 'Produktionsdatum_Origin_01011970', 'origin']
K2LE2 -> ['Komponententyp', 'ID', 'Produktionsdatum', 'Herstellernummer', 'Werksnummer', 'Fehlerhaft', 'Fehlerhaft_Datum', 'Fehlerhaft_Fahrleistung']
K1BE2 -> ['Unnamed: 0', 'X1', 'ID_Motor', 'Herstellernummer', 'Werksnummer', 'Fehlerhaft', 'Fehlerhaft_Datum', 'Fehlerhaft_Fahrleistung', 'Produktionsdatum_Origin_01011970', 'origin']
K1DI2 -> ['Komponententyp', 'ID', 'Produktionsdatum', 'Herstellernummer', 'Werksnummer', 'Fehlerhaft', 'Fehlerhaft_Datum', 'Fehlerhaft_Fahrleistung']

In [12]:
import pandas as pd


def component_id_column(family):
    if family.startswith("K1"):
        return "ID_Motor"
    elif family.startswith("K2"):
        return "ID_Sitze"
    elif family.startswith("K3"):
        return "ID_Schaltung"
    elif family.startswith("K4") or family.startswith("K6"):
        return "ID_Karosserie"

    raise ValueError(f"Unknown component family: {family}")


def normalize_component_chunk(df, family):

    id_col = component_id_column(family)

    fields = [
        id_col,
        "Produktionsdatum",
        "Herstellernummer",
        "Werksnummer",
        "Fehlerhaft",
        "Fehlerhaft_Datum",
        "Fehlerhaft_Fahrleistung",
    ]

    clean = pd.DataFrame(index=df.index)

    # Case 1: .x/.y or .x/.y/base
    if f"{id_col}.x" in df.columns:

        possible_id_cols = [
            f"{id_col}.x",
            f"{id_col}.y",
            id_col
        ]

        possible_id_cols = [
            col for col in possible_id_cols
            if col in df.columns
        ]

        populated = df[possible_id_cols].notna().sum(axis=1)

        if (populated > 1).any():
            raise ValueError(
                f"{family}: some rows contain multiple "
                "component records (.x/.y/base)"
            )

        if (populated == 0).any():
            raise ValueError(
                f"{family}: some rows contain no component ID"
            )

        for field in fields:

            candidates = [
                f"{field}.x",
                f"{field}.y",
                field
            ]

            candidates = [
                col for col in candidates
                if col in df.columns
            ]

            result = df[candidates[0]]

            for col in candidates[1:]:
                result = result.combine_first(df[col])

            clean[field] = result

    # Case 2: already normal
    else:

        for field in fields:
            if field in df.columns:
                clean[field] = df[field]

        # Special production-date format:
        # days since origin date
        if (
            "Produktionsdatum" not in df.columns
            and
            "Produktionsdatum_Origin_01011970" in df.columns
            and
            "origin" in df.columns
        ):
            days = pd.to_numeric(
                df["Produktionsdatum_Origin_01011970"],
                errors="coerce"
            )

            origin = pd.to_datetime(
                df["origin"],
                format="%d-%m-%Y",
                errors="coerce"
            )

            clean["Produktionsdatum"] = (
                origin
                + pd.to_timedelta(days, unit="D")
            )

    # Standard names

    clean = clean.rename(
        columns={id_col: "ID"}
    )

    clean.insert(
        0,
        "Komponententyp",
        family
    )

    # Standard data types

    clean["ID"] = clean["ID"].astype("string")

    clean["Herstellernummer"] = (
        pd.to_numeric(
            clean["Herstellernummer"],
            errors="coerce"
        )
        .astype("Int64")
        .astype("string")
    )

    clean["Werksnummer"] = (
        pd.to_numeric(
            clean["Werksnummer"],
            errors="coerce"
        )
        .astype("Int64")
        .astype("string")
    )

    clean["Produktionsdatum"] = pd.to_datetime(
        clean["Produktionsdatum"],
        errors="coerce"
    )

    clean["Fehlerhaft_Datum"] = pd.to_datetime(
        clean["Fehlerhaft_Datum"],
        errors="coerce"
    )

    clean["Fehlerhaft"] = pd.to_numeric(
        clean["Fehlerhaft"],
        errors="coerce"
    ).astype("Int8")

    clean["Fehlerhaft_Fahrleistung"] = pd.to_numeric(
        clean["Fehlerhaft_Fahrleistung"],
        errors="coerce"
    ).astype("Float64")

    return clean[
        [
            "Komponententyp",
            "ID",
            "Produktionsdatum",
            "Herstellernummer",
            "Werksnummer",
            "Fehlerhaft",
            "Fehlerhaft_Datum",
            "Fehlerhaft_Fahrleistung",
        ]
    ]

In [13]:
for family in component_families:

    path = (
        COMPONENT_FOLDER
        / f"Komponente_{family}.csv"
    )

    sep = detect_separator(path)

    raw = pd.read_csv(
        path,
        sep=sep,
        nrows=5
    )

    clean = normalize_component_chunk(
        raw,
        family
    )

    print(
        family,
        "OK",
        "|",
        len(raw.columns),
        "->",
        len(clean.columns),
        "columns"
    )

    display(clean.head(2))

K4 OK | 16 -> 8 columns

,Komponententyp,ID,Produktionsdatum,Herstellernummer,Werksnummer,Fehlerhaft,Fehlerhaft_Datum,Fehlerhaft_Fahrleistung
0,K4,K4-112-1121-3,2008-11-12,112,1121,0,NaT,0.0
1,K4,K4-112-1121-4,2008-11-12,112,1121,0,NaT,0.0

K3SG1 OK | 16 -> 8 columns

,Komponententyp,ID,Produktionsdatum,Herstellernummer,Werksnummer,Fehlerhaft,Fehlerhaft_Datum,Fehlerhaft_Fahrleistung
0,K3SG1,K3SG1-105-1051-32,2008-11-13,105,1051,0,NaT,0.0
1,K3SG1,K3SG1-105-1051-141,2008-11-13,105,1051,0,NaT,0.0

K3AG1 OK | 23 -> 8 columns

,Komponententyp,ID,Produktionsdatum,Herstellernummer,Werksnummer,Fehlerhaft,Fehlerhaft_Datum,Fehlerhaft_Fahrleistung
0,K3AG1,K3AG1-105-1051-36,2008-11-13,105,1051,0,NaT,0.0
1,K3AG1,K3AG1-105-1051-5,2008-11-13,105,1051,0,NaT,0.0

KeyError: 'ID'

In [ ]:
component_summaries = {}

for family in component_families:

    input_path = (
        COMPONENT_FOLDER
        / f"Komponente_{family}.csv"
    )

    output_path = (
        COMPONENT_FOLDER
        / f"Komponente_{family}_clean.csv"
    )

    if output_path.exists():
        output_path.unlink()

    sep = detect_separator(input_path)

    total_rows = 0
    missing_id = 0
    duplicate_id = 0
    faulty_without_date = 0
    nonfaulty_with_date = 0

    first_chunk = True
    seen_ids = set()

    for raw in pd.read_csv(
        input_path,
        sep=sep,
        chunksize=50_000
    ):

        clean = normalize_component_chunk(
            raw,
            family
        )

        # Missing IDs
        missing_id += int(
            clean["ID"].isna().sum()
        )

        # Duplicate IDs within this chunk
        ids = clean["ID"].dropna()

        duplicate_id += int(
            ids.duplicated().sum()
        )

        # Duplicate IDs against previous chunks
        unique_ids = ids.unique()

        duplicate_id += sum(
            id_ in seen_ids
            for id_ in unique_ids
        )

        seen_ids.update(unique_ids)

        # Defect consistency
        faulty_without_date += int(
            (
                (clean["Fehlerhaft"] == 1)
                & clean["Fehlerhaft_Datum"].isna()
            ).sum()
        )

        nonfaulty_with_date += int(
            (
                (clean["Fehlerhaft"] == 0)
                & clean["Fehlerhaft_Datum"].notna()
            ).sum()
        )

        clean.to_csv(
            output_path,
            mode="a",
            header=first_chunk,
            index=False
        )

        first_chunk = False
        total_rows += len(clean)

        print(
            f"\r{family}: {total_rows:,} rows",
            end=""
        )

    component_summaries[family] = {
        "rows": total_rows,
        "missing_ID": missing_id,
        "duplicate_ID": duplicate_id,
        "faulty_without_date": faulty_without_date,
        "nonfaulty_with_date": nonfaulty_with_date,
    }

    print(
        f"\r{family}: finished — {total_rows:,} rows"
        + " " * 10
    )


component_summary_df = pd.DataFrame.from_dict(
    component_summaries,
    orient="index"
)

component_summary_df.index.name = "component"

display(component_summary_df)

K4: 750,000 rows

/tmp/ipykernel_9535/2010734308.py:29: DtypeWarning: Columns (0: ID_Karosserie.y, 1: Produktionsdatum.y, 2: Fehlerhaft_Datum.y) have mixed types. Specify dtype option on import or set low_memory=False.
  for raw in pd.read_csv(

K4: finished — 1,977,164 rows
K3SG1: 750,000 rows

/tmp/ipykernel_9535/2010734308.py:29: DtypeWarning: Columns (0: ID_Schaltung.x, 1: Produktionsdatum.x, 2: Fehlerhaft_Datum.x) have mixed types. Specify dtype option on import or set low_memory=False.
  for raw in pd.read_csv(

K3SG1: finished — 1,908,208 rows
K3AG1: 100,000 rows

/tmp/ipykernel_9535/2010734308.py:29: DtypeWarning: Columns (0: ID_Schaltung.y, 1: Produktionsdatum.y, 2: Fehlerhaft_Datum.y) have mixed types. Specify dtype option on import or set low_memory=False.
  for raw in pd.read_csv(

K3AG1: 350,000 rows

/tmp/ipykernel_9535/2010734308.py:29: DtypeWarning: Columns (0: ID_Schaltung.y, 1: Produktionsdatum.y, 2: Fehlerhaft_Datum.y) have mixed types. Specify dtype option on import or set low_memory=False.
  for raw in pd.read_csv(

K3AG1: finished — 477,052 rows
K2ST1: finished — 1,908,208 rows
K2LE1: finished — 477,052 rows
K1DI1: 450,000 rows

/tmp/ipykernel_9535/2010734308.py:29: DtypeWarning: Columns (0: ID_Motor.x, 1: Produktionsdatum.x, 2: Fehlerhaft_Datum.x) have mixed types. Specify dtype option on import or set low_memory=False.
  for raw in pd.read_csv(

K1DI1: 700,000 rows

/tmp/ipykernel_9535/2010734308.py:29: DtypeWarning: Columns (0: ID_Motor.y, 1: Produktionsdatum.y, 2: Fehlerhaft_Datum.y) have mixed types. Specify dtype option on import or set low_memory=False.
  for raw in pd.read_csv(

K1DI1: finished — 1,192,630 rows
K1BE1: finished — 1,192,630 rows
K6: finished — 512,354 rows
K3SG2: finished — 655,075 rows
K3AG2: finished — 163,769 rows
K2ST2: finished — 655,075 rows
K2LE2: finished — 163,769 rows
K1BE2: finished — 409,422 rows
K1DI2: finished — 409,422 rows

,rows,missing_ID,duplicate_ID,faulty_without_date,nonfaulty_with_date
component,,,,,
K4,1977164,0,0,0,0
K3SG1,1908208,0,0,0,0
K3AG1,477052,0,0,0,0
K2ST1,1908208,0,0,0,0
K2LE1,477052,0,0,0,0
K1DI1,1192630,0,0,0,0
K1BE1,1192630,0,0,0,0
K6,512354,0,0,0,0
K3SG2,655075,0,0,0,0
K3AG2,163769,0,0,0,0
K2ST2,655075,0,0,0,0
K2LE2,163769,0,0,0,0
K1BE2,409422,0,0,0,0
K1DI2,409422,0,0,0,0

In [ ]:
for family in component_families:

    path = (
        COMPONENT_FOLDER
        / f"Bestandteile_Komponente_{family}.csv"
    )

    sep = detect_separator(path)

    test = pd.read_csv(
        path,
        sep=sep,
        nrows=1
    )

    print(
        family,
        "->",
        test.columns.tolist()
    )

K4 -> ['X1', 'ID_T30', 'ID_T31', 'ID_T32', 'ID_K4']
K3SG1 -> ['X1', 'ID_T21', 'ID_T22', 'ID_T23', 'ID_K3SG1']
K3AG1 -> ['X1', 'ID_T21', 'ID_T24', 'ID_T25', 'ID_K3AG1']
K2ST1 -> ['X1', 'X', 'ID_T11', 'ID_T12', 'ID_T13', 'ID_K2ST1']
K2LE1 -> ['Unnamed: 0', 'ID_T11', 'ID_T14', 'ID_T15', 'ID_K2LE1']
K1DI1 -> ['Unnamed: 0', 'ID_T1', 'ID_T2', 'ID_T5', 'ID_T6', 'ID_K1DI1']
K1BE1 -> ['Unnamed: 0', 'ID_T1', 'ID_T2', 'ID_T3', 'ID_T4', 'ID_K1BE1']
K6 -> ['X1', 'ID_T34', 'ID_T35', 'ID_T36', 'ID_T37', 'ID_K6']
K3SG2 -> ['X1', 'ID_T21', 'ID_T22', 'ID_T26', 'ID_K3SG2']
K3AG2 -> ['X1', 'ID_T21', 'ID_T24', 'ID_T27', 'ID_K3AG2']
K2ST2 -> ['Unnamed: 0', 'ID_T16', 'ID_T17', 'ID_T18', 'ID_K2ST2']
K2LE2 -> ['Unnamed: 0', 'ID_T16', 'ID_T19', 'ID_T20', 'ID_K2LE2']
K1BE2 -> ['Unnamed: 0', 'ID_T1', 'ID_T2', 'ID_T7', 'ID_T8', 'ID_K1BE2']
K1DI2 -> ['Unnamed: 0', 'ID_T1', 'ID_T2', 'ID_T9', 'ID_T10', 'ID_K1DI2']

Type11:

| Component          | Parts inside   |
| ------------------ | -------------- |
| K4 body            | T30, T31, T32  |
| K3SG1 transmission | T21, T22, T23  |
| K3AG1 transmission | T21, T24, T25  |
| K2ST1 seats        | T11, T12, T13  |
| K2LE1 seats        | T11, T14, T15  |
| K1DI1 motor        | T1, T2, T5, T6 |
| K1BE1 motor        | T1, T2, T3, T4 |

Type21:

| Component          | Parts inside       |
| ------------------ | ------------------ |
| K6 body            | T34, T35, T36, T37 |
| K3SG2 transmission | T21, T22, T26      |
| K3AG2 transmission | T21, T24, T27      |
| K2ST2 seats        | T16, T17, T18      |
| K2LE2 seats        | T16, T19, T20      |
| K1BE2 motor        | T1, T2, T7, T8     |
| K1DI2 motor        | T1, T2, T9, T10    |

In [ ]:
from pathlib import Path

EINZELTEIL_FOLDER = Path("data/Einzelteil")

for part in ["T21", "T22", "T23"]:
    print(f"\n{part}")

    for path in sorted(EINZELTEIL_FOLDER.glob(f"*{part}*")):
        print(" ", path.name)

T21
  Einzelteil_T21.csv

T22
  Einzelteil_T22.txt
  Einzelteil_T22_clean.csv

T23
  Einzelteil_T23.csv