In [1]:
import pandas as pd

fahrzeug_11 = pd.read_csv(
    "data/Fahrzeug/Fahrzeuge_OEM1_Typ11.csv",
    sep=","
)

bom_11 = pd.read_csv(
    "data/Fahrzeug/Bestandteile_Fahrzeuge_OEM1_Typ11.csv",
    sep=";"
)

fahrzeug_21 = pd.read_csv(
    "data/Fahrzeug/Fahrzeuge_OEM2_Typ21.csv",
    sep=","
)

bom_21 = pd.read_csv(
    "data/Fahrzeug/Bestandteile_Fahrzeuge_OEM2_Typ21.csv",
    sep=";"
)

In [2]:
print(fahrzeug_11.shape)
print(bom_11.shape)

print(fahrzeug_21.shape)
print(bom_21.shape)

(1977164, 9)
(1977164, 6)
(512354, 10)
(512354, 6)

In [3]:
print("OEM1")
print("Vehicle IDs unique:", fahrzeug_11["ID_Fahrzeug"].is_unique)
print("BOM IDs unique:", bom_11["ID_Fahrzeug"].is_unique)

print(
    "Vehicles missing from BOM:",
    len(set(fahrzeug_11["ID_Fahrzeug"]) - set(bom_11["ID_Fahrzeug"]))
)

print(
    "BOM IDs missing from vehicles:",
    len(set(bom_11["ID_Fahrzeug"]) - set(fahrzeug_11["ID_Fahrzeug"]))
)


print("\nOEM2")
print("Vehicle IDs unique:", fahrzeug_21["ID_Fahrzeug"].is_unique)
print("BOM IDs unique:", bom_21["ID_Fahrzeug"].is_unique)

print(
    "Vehicles missing from BOM:",
    len(set(fahrzeug_21["ID_Fahrzeug"]) - set(bom_21["ID_Fahrzeug"]))
)

print(
    "BOM IDs missing from vehicles:",
    len(set(bom_21["ID_Fahrzeug"]) - set(fahrzeug_21["ID_Fahrzeug"]))
)


vehicle_11 = fahrzeug_11.merge(
    bom_11[
        [
            "ID_Fahrzeug",
            "ID_Karosserie",
            "ID_Schaltung",
            "ID_Sitze",
            "ID_Motor"
        ]
    ],
    on="ID_Fahrzeug",
    how="left",
    validate="one_to_one"
)

vehicle_21 = fahrzeug_21.merge(
    bom_21[
        [
            "ID_Fahrzeug",
            "ID_Karosserie",
            "ID_Schaltung",
            "ID_Sitze",
            "ID_Motor"
        ]
    ],
    on="ID_Fahrzeug",
    how="left",
    validate="one_to_one"
)


print("\nMerged shapes:")
print("OEM1:", vehicle_11.shape)
print("OEM2:", vehicle_21.shape)


print("\nMissing installed components OEM1:")
print(
    vehicle_11[
        [
            "ID_Karosserie",
            "ID_Schaltung",
            "ID_Sitze",
            "ID_Motor"
        ]
    ].isna().sum()
)

print("\nMissing installed components OEM2:")
print(
    vehicle_21[
        [
            "ID_Karosserie",
            "ID_Schaltung",
            "ID_Sitze",
            "ID_Motor"
        ]
    ].isna().sum()
)

OEM1
Vehicle IDs unique: True
BOM IDs unique: True
Vehicles missing from BOM: 0
BOM IDs missing from vehicles: 0

OEM2
Vehicle IDs unique: True
BOM IDs unique: True
Vehicles missing from BOM: 0
BOM IDs missing from vehicles: 0

Merged shapes:
OEM1: (1977164, 13)
OEM2: (512354, 14)

Missing installed components OEM1:
ID_Karosserie    0
ID_Schaltung     0
ID_Sitze         0
ID_Motor         0
dtype: int64

Missing installed components OEM2:
ID_Karosserie    0
ID_Schaltung     0
ID_Sitze         0
ID_Motor         0
dtype: int64

In [4]:
vehicle_11 = fahrzeug_11.merge(
    bom_11[
        [
            "ID_Fahrzeug",
            "ID_Karosserie",
            "ID_Schaltung",
            "ID_Sitze",
            "ID_Motor"
        ]
    ],
    on="ID_Fahrzeug",
    how="left",
    validate="one_to_one"
)

vehicle_21 = fahrzeug_21.merge(
    bom_21[
        [
            "ID_Fahrzeug",
            "ID_Karosserie",
            "ID_Schaltung",
            "ID_Sitze",
            "ID_Motor"
        ]
    ],
    on="ID_Fahrzeug",
    how="left",
    validate="one_to_one"
)

vehicle_11 = vehicle_11.drop(
    columns=["Unnamed: 0", "X1"]
)

vehicle_21 = vehicle_21.drop(
    columns=[
        col for col in ["Unnamed: 0", "X1"]
        if col in vehicle_21.columns
    ]
)

In [5]:
vehicle_11.head()

,ID_Fahrzeug,Produktionsdatum,Herstellernummer,Werksnummer,Fehlerhaft,Fehlerhaft_Datum,Fehlerhaft_Fahrleistung,ID_Karosserie,ID_Schaltung,ID_Sitze,ID_Motor
0,11-1-11-1,2008-11-18,1,11,0,NaN,0,K4-112-1121-3,K3SG1-105-1051-32,K2LE1-109-1091-2,K1BE1-101-1011-7
1,11-1-11-2,2008-11-18,1,11,0,NaN,0,K4-112-1121-4,K3SG1-105-1051-141,K2ST1-109-1092-5,K1BE1-101-1011-12
2,11-1-11-3,2008-11-19,1,11,0,NaN,0,K4-112-1121-7,K3SG1-105-1051-106,K2ST1-109-1092-57,K1BE1-101-1011-38
3,11-1-11-4,2008-11-19,1,11,0,NaN,0,K4-112-1121-9,K3SG1-105-1051-21,K2ST1-109-1092-91,K1BE1-101-1011-97
4,11-1-11-5,2008-11-19,1,11,0,NaN,0,K4-112-1121-11,K3SG1-105-1051-59,K2ST1-109-1092-4,K1BE1-101-1011-65

In [6]:
def get_prefix(series):
    return series.str.split("-").str[0]

print("OEM1 Type11 component families")

for col in [
    "ID_Karosserie",
    "ID_Schaltung",
    "ID_Sitze",
    "ID_Motor"
]:
    print(f"\n{col}")
    print(
        get_prefix(vehicle_11[col])
        .value_counts()
    )


print("\nOEM2 Type21 component families")

for col in [
    "ID_Karosserie",
    "ID_Schaltung",
    "ID_Sitze",
    "ID_Motor"
]:
    print(f"\n{col}")
    print(
        get_prefix(vehicle_21[col])
        .value_counts()
    )

OEM1 Type11 component families

ID_Karosserie
ID_Karosserie
K4    1977164
Name: count, dtype: int64

ID_Schaltung
ID_Schaltung
K3SG1    1581724
K3AG1     395440
Name: count, dtype: int64

ID_Sitze
ID_Sitze
K2ST1    1581267
K2LE1     395897
Name: count, dtype: int64

ID_Motor
ID_Motor
K1DI1    988744
K1BE1    988420
Name: count, dtype: int64

OEM2 Type21 component families

ID_Karosserie
ID_Karosserie
K6    512354
Name: count, dtype: int64

ID_Schaltung
ID_Schaltung
K3SG2    409700
K3AG2    102654
Name: count, dtype: int64

ID_Sitze
ID_Sitze
K2ST2    409543
K2LE2    102811
Name: count, dtype: int64

ID_Motor
ID_Motor
K1BE2    269276
K1DI2    243078
Name: count, dtype: int64

In [7]:
from pathlib import Path

KOMPONENTE_FOLDER = Path("data/Komponente")
EINZELTEIL_FOLDER = Path("data/Einzelteil")

relevant_families = {
    "K4",
    "K3SG1",
    "K3AG1",
    "K2ST1",
    "K2LE1",
    "K1DI1",
    "K1BE1",
    "K6",
    "K3SG2",
    "K3AG2",
    "K2ST2",
    "K2LE2",
    "K1BE2",
    "K1DI2",
}

In [8]:
canonical_component_columns = [
    "Komponententyp",
    "ID",
    "Produktionsdatum",
    "Herstellernummer",
    "Werksnummer",
    "Fehlerhaft",
    "Fehlerhaft_Datum",
    "Fehlerhaft_Fahrleistung",
]

for family in sorted(relevant_families):
    path = KOMPONENTE_FOLDER / f"Komponente_{family}.csv"

    if not path.exists():
        raise FileNotFoundError(path)

    columns = pd.read_csv(path, nrows=0).columns.tolist()

    if columns != canonical_component_columns:
        raise ValueError(
            f"{family}: unexpected schema: {columns}"
        )

    print(f"{family}: OK")

K1BE1: OK
K1BE2: OK
K1DI1: OK
K1DI2: OK
K2LE1: OK
K2LE2: OK
K2ST1: OK
K2ST2: OK
K3AG1: OK
K3AG2: OK
K3SG1: OK
K3SG2: OK
K4: OK
K6: OK

In [9]:
component_parts = {}

for family in sorted(relevant_families):
    path = (
        KOMPONENTE_FOLDER
        / f"Bestandteile_Komponente_{family}.csv"
    )

    columns = pd.read_csv(
        path,
        sep=";",
        nrows=0
    ).columns.tolist()

    component_parts[family] = [
        f"T{int(col.replace('ID_T', '')):02d}"
        for col in columns
        if col.startswith("ID_T")
    ]

component_parts

{'K1BE1': ['T01', 'T02', 'T03', 'T04'],
 'K1BE2': ['T01', 'T02', 'T07', 'T08'],
 'K1DI1': ['T01', 'T02', 'T05', 'T06'],
 'K1DI2': ['T01', 'T02', 'T09', 'T10'],
 'K2LE1': ['T11', 'T14', 'T15'],
 'K2LE2': ['T16', 'T19', 'T20'],
 'K2ST1': ['T11', 'T12', 'T13'],
 'K2ST2': ['T16', 'T17', 'T18'],
 'K3AG1': ['T21', 'T24', 'T25'],
 'K3AG2': ['T21', 'T24', 'T27'],
 'K3SG1': ['T21', 'T22', 'T23'],
 'K3SG2': ['T21', 'T22', 'T26'],
 'K4': ['T30', 'T31', 'T32'],
 'K6': ['T34', 'T35', 'T36', 'T37']}

Type11:

| Component | Parts inside |
| --- | --- |
| K4 body | T30, T31, T32 |
| K3SG1 transmission | T21, T22, T23 |
| K3AG1 transmission | T21, T24, T25 |
| K2ST1 seats | T11, T12, T13 |
| K2LE1 seats | T11, T14, T15 |
| K1DI1 motor | T1, T2, T5, T6 |
| K1BE1 motor | T1, T2, T3, T4 |

Type21:

| Component | Parts inside |
| --- | --- |
| K6 body | T34, T35, T36, T37 |
| K3SG2 transmission | T21, T22, T26 |
| K3AG2 transmission | T21, T24, T27 |
| K2ST2 seats | T16, T17, T18 |
| K2LE2 seats | T16, T19, T20 |
| K1BE2 motor | T1, T2, T7, T8 |
| K1DI2 motor | T1, T2, T9, T10 |

In [10]:
required_parts = sorted(
    {
        part
        for parts in component_parts.values()
        for part in parts
    },
    key=lambda part: int(part[1:])
)

for part in required_parts:
    path = EINZELTEIL_FOLDER / f"Einzelteil_{part}.csv"
    print(part, "OK" if path.exists() else "MISSING")

T01 OK
T02 OK
T03 OK
T04 OK
T05 OK
T06 OK
T07 OK
T08 OK
T09 OK
T10 OK
T11 OK
T12 OK
T13 OK
T14 OK
T15 OK
T16 OK
T17 OK
T18 OK
T19 OK
T20 OK
T21 OK
T22 OK
T23 OK
T24 OK
T25 OK
T26 OK
T27 OK
T30 OK
T31 OK
T32 OK
T34 OK
T35 OK
T36 OK
T37 OK

## Supply-chain diagnostics

The following analyses are exploratory diagnostics used to understand which components and suppliers contribute to the vehicle-level field defects. They are not separate final datasets.

In [11]:
def combine_defect_flags(*series):
    values = pd.concat(series, axis=1)

    defective = values.eq(1).any(axis=1)
    unknown = values.isna().any(axis=1)

    result = pd.Series(
        0,
        index=values.index,
        dtype="Int8"
    )

    result = result.mask(
        ~defective & unknown,
        pd.NA
    )

    result = result.mask(
        defective,
        1
    )

    return result

In [12]:
family = "K3SG1"

component = pd.read_csv(
    KOMPONENTE_FOLDER / "Komponente_K3SG1.csv",
    usecols=[
        "ID",
        "Werksnummer",
        "Fehlerhaft"
    ],
    dtype="string"
)

bom = pd.read_csv(
    KOMPONENTE_FOLDER
    / "Bestandteile_Komponente_K3SG1.csv",
    sep=";",
    usecols=[
        "ID_K3SG1",
        "ID_T21",
        "ID_T22",
        "ID_T23"
    ],
    dtype="string"
)

if not component["ID"].is_unique:
    raise ValueError(
        "Duplicate K3SG1 IDs in component file"
    )

if not bom["ID_K3SG1"].is_unique:
    raise ValueError(
        "Duplicate K3SG1 IDs in BOM"
    )

component_lookup = component.set_index("ID")

k3sg1_quality = pd.DataFrame({
    "ID": bom["ID_K3SG1"],
    "Tier1_Werksnummer":
        bom["ID_K3SG1"].map(
            component_lookup["Werksnummer"]
        ),
    "Fehlerhaft_Komponente_Roh":
        pd.to_numeric(
            bom["ID_K3SG1"].map(
                component_lookup["Fehlerhaft"]
            ),
            errors="coerce"
        ).astype("Int8")
})

for part in ["T21", "T22", "T23"]:
    part_data = pd.read_csv(
        EINZELTEIL_FOLDER
        / f"Einzelteil_{part}.csv",
        usecols=[
            "ID",
            "Werksnummer",
            "Fehlerhaft"
        ],
        dtype="string"
    )

    if not part_data["ID"].is_unique:
        raise ValueError(
            f"Duplicate {part} IDs"
        )

    part_lookup = part_data.set_index("ID")

    part_id_column = f"ID_{part}"

    k3sg1_quality[
        f"Tier2_Werksnummer_{part}"
    ] = bom[part_id_column].map(
        part_lookup["Werksnummer"]
    )

    k3sg1_quality[
        f"Fehlerhaft_{part}"
    ] = pd.to_numeric(
        bom[part_id_column].map(
            part_lookup["Fehlerhaft"]
        ),
        errors="coerce"
    ).astype("Int8")

    del part_data
    del part_lookup

k3sg1_quality[
    "Fehlerhaft_Einzelteil"
] = combine_defect_flags(
    k3sg1_quality["Fehlerhaft_T21"],
    k3sg1_quality["Fehlerhaft_T22"],
    k3sg1_quality["Fehlerhaft_T23"]
)

k3sg1_quality[
    "Anzahl_Fehlerhafte_Einzelteile"
] = (
    k3sg1_quality[
        [
            "Fehlerhaft_T21",
            "Fehlerhaft_T22",
            "Fehlerhaft_T23"
        ]
    ]
    .eq(1)
    .sum(axis=1)
    .astype("Int8")
)

k3sg1_quality[
    "Fehlerhaft_Komponente"
] = combine_defect_flags(
    k3sg1_quality[
        "Fehlerhaft_Komponente_Roh"
    ],
    k3sg1_quality[
        "Fehlerhaft_Einzelteil"
    ]
)

k3sg1_quality.head()

,ID,Tier1_Werksnummer,Fehlerhaft_Komponente_Roh,Tier2_Werksnummer_T21,Fehlerhaft_T21,Tier2_Werksnummer_T22,Fehlerhaft_T22,Tier2_Werksnummer_T23,Fehlerhaft_T23,Fehlerhaft_Einzelteil,Anzahl_Fehlerhafte_Einzelteile,Fehlerhaft_Komponente
0,K3SG1-105-1051-1,1051,0,2081,1,2051,1,2051,0,1,2,1
1,K3SG1-105-1051-2,1051,0,2051,0,2061,0,2051,0,0,0,0
2,K3SG1-105-1051-3,1051,0,2072,0,2051,0,2051,0,0,0,0
3,K3SG1-105-1051-4,1051,0,2081,0,2061,0,2051,0,0,0,0
4,K3SG1-105-1051-5,1051,0,2072,0,2051,0,2051,0,0,0,0

In [13]:
print(
    "Rows:",
    f"{len(k3sg1_quality):,}"
)

print(
    "Unique IDs:",
    k3sg1_quality["ID"].is_unique
)

print(
    "Missing Tier1 plant:",
    k3sg1_quality[
        "Tier1_Werksnummer"
    ].isna().sum()
)

print(
    "Missing T21:",
    k3sg1_quality[
        "Fehlerhaft_T21"
    ].isna().sum()
)

print(
    "Missing T22:",
    k3sg1_quality[
        "Fehlerhaft_T22"
    ].isna().sum()
)

print(
    "Missing T23:",
    k3sg1_quality[
        "Fehlerhaft_T23"
    ].isna().sum()
)

print(
    "\nFinal defect distribution:"
)

print(
    k3sg1_quality[
        "Fehlerhaft_Komponente"
    ].value_counts(
        dropna=False
    )
)

Rows: 1,908,208
Unique IDs: True
Missing Tier1 plant: 0
Missing T21: 0
Missing T22: 0
Missing T23: 0

Final defect distribution:
Fehlerhaft_Komponente
0    1252763
1     655445
Name: count, dtype: Int64

In [14]:
k3sg1_lookup = k3sg1_quality.set_index("ID")

k3sg1_mask = (
    vehicle_11["ID_Schaltung"]
    .astype("string")
    .str.startswith("K3SG1-")
)

vehicle_11.loc[
    k3sg1_mask,
    "Tier1_Werksnummer_Schaltung"
] = (
    vehicle_11.loc[
        k3sg1_mask,
        "ID_Schaltung"
    ]
    .map(
        k3sg1_lookup[
            "Tier1_Werksnummer"
        ]
    )
)

vehicle_11.loc[
    k3sg1_mask,
    "Fehlerhaft_Schaltung_Roh"
] = (
    vehicle_11.loc[
        k3sg1_mask,
        "ID_Schaltung"
    ]
    .map(
        k3sg1_lookup[
            "Fehlerhaft_Komponente_Roh"
        ]
    )
)

vehicle_11.loc[
    k3sg1_mask,
    "Fehlerhaft_Schaltung_Einzelteil"
] = (
    vehicle_11.loc[
        k3sg1_mask,
        "ID_Schaltung"
    ]
    .map(
        k3sg1_lookup[
            "Fehlerhaft_Einzelteil"
        ]
    )
)

vehicle_11.loc[
    k3sg1_mask,
    "Anzahl_Fehlerhafte_Einzelteile_Schaltung"
] = (
    vehicle_11.loc[
        k3sg1_mask,
        "ID_Schaltung"
    ]
    .map(
        k3sg1_lookup[
            "Anzahl_Fehlerhafte_Einzelteile"
        ]
    )
)

vehicle_11.loc[
    k3sg1_mask,
    "Fehlerhaft_Schaltung"
] = (
    vehicle_11.loc[
        k3sg1_mask,
        "ID_Schaltung"
    ]
    .map(
        k3sg1_lookup[
            "Fehlerhaft_Komponente"
        ]
    )
)

print(
    "vehicle_11 rows:",
    f"{len(vehicle_11):,}"
)

print(
    "K3SG1 vehicles:",
    f"{k3sg1_mask.sum():,}"
)

print(
    "Missing Tier1 mappings:",
    vehicle_11.loc[
        k3sg1_mask,
        "Tier1_Werksnummer_Schaltung"
    ].isna().sum()
)

print(
    "Missing defect mappings:",
    vehicle_11.loc[
        k3sg1_mask,
        "Fehlerhaft_Schaltung"
    ].isna().sum()
)

print(
    "\nDefect distribution among installed K3SG1:"
)

print(
    vehicle_11.loc[
        k3sg1_mask,
        "Fehlerhaft_Schaltung"
    ].value_counts(
        dropna=False
    )
)

vehicle_11.loc[
    k3sg1_mask,
    [
        "ID_Fahrzeug",
        "Werksnummer",
        "ID_Schaltung",
        "Tier1_Werksnummer_Schaltung",
        "Fehlerhaft_Schaltung_Roh",
        "Fehlerhaft_Schaltung_Einzelteil",
        "Anzahl_Fehlerhafte_Einzelteile_Schaltung",
        "Fehlerhaft_Schaltung"
    ]
].head()

vehicle_11 rows: 1,977,164
K3SG1 vehicles: 1,581,724
Missing Tier1 mappings: 0
Missing defect mappings: 0

Defect distribution among installed K3SG1:
Fehlerhaft_Schaltung
0    1038792
1     542932
Name: count, dtype: Int64

,ID_Fahrzeug,Werksnummer,ID_Schaltung,Tier1_Werksnummer_Schaltung,Fehlerhaft_Schaltung_Roh,Fehlerhaft_Schaltung_Einzelteil,Anzahl_Fehlerhafte_Einzelteile_Schaltung,Fehlerhaft_Schaltung
0,11-1-11-1,11,K3SG1-105-1051-32,1051,0,1,1,1
1,11-1-11-2,11,K3SG1-105-1051-141,1051,0,1,2,1
2,11-1-11-3,11,K3SG1-105-1051-106,1051,0,1,1,1
3,11-1-11-4,11,K3SG1-105-1051-21,1051,0,1,1,1
4,11-1-11-5,11,K3SG1-105-1051-59,1051,0,1,1,1

In [15]:
del component
del bom
del component_lookup
del k3sg1_quality
del k3sg1_lookup
del k3sg1_mask

In [16]:
type11_families = {
    "K4",
    "K3SG1",
    "K3AG1",
    "K2ST1",
    "K2LE1",
    "K1DI1",
    "K1BE1",
}

type21_families = {
    "K6",
    "K3SG2",
    "K3AG2",
    "K2ST2",
    "K2LE2",
    "K1BE2",
    "K1DI2",
}

roles = [
    "Karosserie",
    "Schaltung",
    "Sitze",
    "Motor"
]

for vehicle in [vehicle_11, vehicle_21]:
    for role in roles:
        vehicle[
            f"Tier1_Werksnummer_{role}"
        ] = pd.Series(
            pd.NA,
            index=vehicle.index,
            dtype="string"
        )

        vehicle[
            f"Fehlerhaft_{role}_Roh"
        ] = pd.Series(
            pd.NA,
            index=vehicle.index,
            dtype="Int8"
        )

        vehicle[
            f"Fehlerhaft_{role}_Einzelteil"
        ] = pd.Series(
            pd.NA,
            index=vehicle.index,
            dtype="Int8"
        )

        vehicle[
            f"Anzahl_Fehlerhafte_Einzelteile_{role}"
        ] = pd.Series(
            pd.NA,
            index=vehicle.index,
            dtype="Int8"
        )

        vehicle[
            f"Fehlerhaft_{role}"
        ] = pd.Series(
            pd.NA,
            index=vehicle.index,
            dtype="Int8"
        )

In [17]:
def family_role(family):
    if family in {"K4", "K6"}:
        return "Karosserie"
    if family.startswith("K3"):
        return "Schaltung"
    if family.startswith("K2"):
        return "Sitze"
    if family.startswith("K1"):
        return "Motor"
    raise ValueError(f"Unknown family: {family}")


def process_family(family, vehicle):
    role = family_role(family)

    parts = component_parts[family]

    bom_part_columns = [
        f"ID_T{int(part[1:])}"
        for part in parts
    ]

    component_id_column = f"ID_{family}"

    component = pd.read_csv(
        KOMPONENTE_FOLDER
        / f"Komponente_{family}.csv",
        usecols=[
            "ID",
            "Werksnummer",
            "Fehlerhaft"
        ],
        dtype="string"
    )

    bom = pd.read_csv(
        KOMPONENTE_FOLDER
        / f"Bestandteile_Komponente_{family}.csv",
        sep=";",
        usecols=[
            component_id_column,
            *bom_part_columns
        ],
        dtype="string"
    )

    if not component["ID"].is_unique:
        raise ValueError(
            f"{family}: duplicate component IDs"
        )

    if not bom[component_id_column].is_unique:
        raise ValueError(
            f"{family}: duplicate BOM component IDs"
        )

    component_lookup = component.set_index("ID")

    quality = pd.DataFrame({
        "ID": bom[component_id_column],
        "Tier1_Werksnummer":
            bom[component_id_column].map(
                component_lookup["Werksnummer"]
            ),
        "Fehlerhaft_Roh":
            pd.to_numeric(
                bom[component_id_column].map(
                    component_lookup["Fehlerhaft"]
                ),
                errors="coerce"
            ).astype("Int8")
    })

    part_defect_columns = []

    for part, bom_part_column in zip(
        parts,
        bom_part_columns
    ):
        part_data = pd.read_csv(
            EINZELTEIL_FOLDER
            / f"Einzelteil_{part}.csv",
            usecols=[
                "ID",
                "Fehlerhaft"
            ],
            dtype="string"
        )

        if not part_data["ID"].is_unique:
            raise ValueError(
                f"{part}: duplicate IDs"
            )

        part_lookup = (
            part_data
            .set_index("ID")["Fehlerhaft"]
        )

        defect_column = f"Fehlerhaft_{part}"

        quality[defect_column] = pd.to_numeric(
            bom[bom_part_column].map(
                part_lookup
            ),
            errors="coerce"
        ).astype("Int8")

        part_defect_columns.append(
            defect_column
        )

        del part_data
        del part_lookup

    quality[
        "Fehlerhaft_Einzelteil"
    ] = combine_defect_flags(
        *[
            quality[column]
            for column in part_defect_columns
        ]
    )

    quality[
        "Anzahl_Fehlerhafte_Einzelteile"
    ] = (
        quality[
            part_defect_columns
        ]
        .eq(1)
        .sum(axis=1)
        .astype("Int8")
    )

    quality[
        "Fehlerhaft_Komponente"
    ] = combine_defect_flags(
        quality["Fehlerhaft_Roh"],
        quality["Fehlerhaft_Einzelteil"]
    )

    lookup = quality.set_index("ID")

    vehicle_id_column = f"ID_{role}"

    mask = (
        vehicle[vehicle_id_column]
        .astype("string")
        .str.startswith(f"{family}-")
    )

    vehicle.loc[
        mask,
        f"Tier1_Werksnummer_{role}"
    ] = (
        vehicle.loc[
            mask,
            vehicle_id_column
        ]
        .map(
            lookup["Tier1_Werksnummer"]
        )
    )

    vehicle.loc[
        mask,
        f"Fehlerhaft_{role}_Roh"
    ] = (
        vehicle.loc[
            mask,
            vehicle_id_column
        ]
        .map(
            lookup["Fehlerhaft_Roh"]
        )
    )

    vehicle.loc[
        mask,
        f"Fehlerhaft_{role}_Einzelteil"
    ] = (
        vehicle.loc[
            mask,
            vehicle_id_column
        ]
        .map(
            lookup["Fehlerhaft_Einzelteil"]
        )
    )

    vehicle.loc[
        mask,
        f"Anzahl_Fehlerhafte_Einzelteile_{role}"
    ] = (
        vehicle.loc[
            mask,
            vehicle_id_column
        ]
        .map(
            lookup[
                "Anzahl_Fehlerhafte_Einzelteile"
            ]
        )
    )

    vehicle.loc[
        mask,
        f"Fehlerhaft_{role}"
    ] = (
        vehicle.loc[
            mask,
            vehicle_id_column
        ]
        .map(
            lookup["Fehlerhaft_Komponente"]
        )
    )

    result = {
        "family": family,
        "role": role,
        "produced_components": len(quality),
        "installed_components": int(mask.sum()),
        "missing_tier1": int(
            vehicle.loc[
                mask,
                f"Tier1_Werksnummer_{role}"
            ].isna().sum()
        ),
        "missing_defect": int(
            vehicle.loc[
                mask,
                f"Fehlerhaft_{role}"
            ].isna().sum()
        )
    }

    del component
    del bom
    del component_lookup
    del quality
    del lookup

    return result

In [18]:
family_results = []

for family in sorted(type11_families):
    print(f"Processing Type11 {family}...")

    result = process_family(
        family,
        vehicle_11
    )

    family_results.append(result)

    print(
        f"{family}: "
        f"{result['installed_components']:,} installed, "
        f"{result['missing_tier1']} missing Tier1, "
        f"{result['missing_defect']} missing defects"
    )

for family in sorted(type21_families):
    print(f"Processing Type21 {family}...")

    result = process_family(
        family,
        vehicle_21
    )

    family_results.append(result)

    print(
        f"{family}: "
        f"{result['installed_components']:,} installed, "
        f"{result['missing_tier1']} missing Tier1, "
        f"{result['missing_defect']} missing defects"
    )

family_results = pd.DataFrame(
    family_results
)

display(family_results)

Processing Type11 K1BE1...
K1BE1: 988,420 installed, 0 missing Tier1, 0 missing defects
Processing Type11 K1DI1...
K1DI1: 988,744 installed, 0 missing Tier1, 0 missing defects
Processing Type11 K2LE1...
K2LE1: 395,897 installed, 0 missing Tier1, 0 missing defects
Processing Type11 K2ST1...
K2ST1: 1,581,267 installed, 0 missing Tier1, 0 missing defects
Processing Type11 K3AG1...
K3AG1: 395,440 installed, 0 missing Tier1, 0 missing defects
Processing Type11 K3SG1...
K3SG1: 1,581,724 installed, 0 missing Tier1, 0 missing defects
Processing Type11 K4...
K4: 1,977,164 installed, 0 missing Tier1, 0 missing defects
Processing Type21 K1BE2...
K1BE2: 269,276 installed, 0 missing Tier1, 0 missing defects
Processing Type21 K1DI2...
K1DI2: 243,078 installed, 0 missing Tier1, 0 missing defects
Processing Type21 K2LE2...
K2LE2: 102,811 installed, 0 missing Tier1, 0 missing defects
Processing Type21 K2ST2...
K2ST2: 409,543 installed, 0 missing Tier1, 0 missing defects
Processing Type21 K3AG2...
K3AG2: 102,654 installed, 0 missing Tier1, 0 missing defects
Processing Type21 K3SG2...
K3SG2: 409,700 installed, 0 missing Tier1, 0 missing defects
Processing Type21 K6...
K6: 512,354 installed, 0 missing Tier1, 0 missing defects

,family,role,produced_components,installed_components,missing_tier1,missing_defect
0,K1BE1,Motor,1192630,988420,0,0
1,K1DI1,Motor,1192630,988744,0,0
2,K2LE1,Sitze,477052,395897,0,0
3,K2ST1,Sitze,1908208,1581267,0,0
4,K3AG1,Schaltung,477052,395440,0,0
5,K3SG1,Schaltung,1908208,1581724,0,0
6,K4,Karosserie,1977164,1977164,0,0
7,K1BE2,Motor,409422,269276,0,0
8,K1DI2,Motor,409422,243078,0,0
9,K2LE2,Sitze,163769,102811,0,0
10,K2ST2,Sitze,655075,409543,0,0
11,K3AG2,Schaltung,163769,102654,0,0
12,K3SG2,Schaltung,655075,409700,0,0
13,K6,Karosserie,512354,512354,0,0

In [19]:
print(
    "vehicle_11 rows:",
    f"{len(vehicle_11):,}"
)

print(
    "vehicle_21 rows:",
    f"{len(vehicle_21):,}"
)

for name, vehicle in [
    ("Type11", vehicle_11),
    ("Type21", vehicle_21)
]:
    print(f"\n{name}")

    for role in roles:
        print(
            role,
            "Tier1 missing:",
            vehicle[
                f"Tier1_Werksnummer_{role}"
            ].isna().sum(),
            "| defect missing:",
            vehicle[
                f"Fehlerhaft_{role}"
            ].isna().sum()
        )

vehicle_11 rows: 1,977,164
vehicle_21 rows: 512,354

Type11
Karosserie Tier1 missing: 0 | defect missing: 0
Schaltung Tier1 missing: 0 | defect missing: 0
Sitze Tier1 missing: 0 | defect missing: 0
Motor Tier1 missing: 0 | defect missing: 0

Type21
Karosserie Tier1 missing: 0 | defect missing: 0
Schaltung Tier1 missing: 0 | defect missing: 0
Sitze Tier1 missing: 0 | defect missing: 0
Motor Tier1 missing: 0 | defect missing: 0

In [20]:
for vehicle in [vehicle_11, vehicle_21]:
    vehicle[
        "Fehlerhaft_Fahrzeug_Roh"
    ] = pd.to_numeric(
        vehicle["Fehlerhaft"],
        errors="coerce"
    ).astype("Int8")

    component_defect_columns = [
        f"Fehlerhaft_{role}"
        for role in roles
    ]

    vehicle[
        "Anzahl_Fehlerhafte_Komponenten"
    ] = (
        vehicle[
            component_defect_columns
        ]
        .eq(1)
        .sum(axis=1)
        .astype("Int8")
    )

    vehicle[
        "Fehlerhaft_Gesamt"
    ] = combine_defect_flags(
        vehicle[
            "Fehlerhaft_Fahrzeug_Roh"
        ],
        *[
            vehicle[column]
            for column
            in component_defect_columns
        ]
    )

In [21]:
for name, vehicle in [
    ("Type11", vehicle_11),
    ("Type21", vehicle_21)
]:
    print(f"\n{name}")

    print(
        "Rows:",
        f"{len(vehicle):,}"
    )

    print(
        "Missing final defect:",
        vehicle[
            "Fehlerhaft_Gesamt"
        ].isna().sum()
    )

    print(
        "\nFinal defect distribution:"
    )

    print(
        vehicle[
            "Fehlerhaft_Gesamt"
        ].value_counts(
            dropna=False
        )
    )

    print(
        "\nNumber of defective components:"
    )

    print(
        vehicle[
            "Anzahl_Fehlerhafte_Komponenten"
        ].value_counts(
            dropna=False
        ).sort_index()
    )

Type11
Rows: 1,977,164
Missing final defect: 0

Final defect distribution:
Fehlerhaft_Gesamt
1    1735093
0     242071
Name: count, dtype: Int64

Number of defective components:
Anzahl_Fehlerhafte_Komponenten
0    268979
1    710278
2    676368
3    279506
4     42033
Name: count, dtype: Int64

Type21
Rows: 512,354
Missing final defect: 0

Final defect distribution:
Fehlerhaft_Gesamt
1    455877
0     56477
Name: count, dtype: Int64

Number of defective components:
Anzahl_Fehlerhafte_Komponenten
0     62678
1    176948
2    179939
3     79779
4     13010
Name: count, dtype: Int64

In [22]:
vehicle_11["OEM"] = "OEM1"
vehicle_11["Fahrzeugtyp"] = "Type11"

vehicle_21["OEM"] = "OEM2"
vehicle_21["Fahrzeugtyp"] = "Type21"

vehicle_quality = pd.concat(
    [
        vehicle_11,
        vehicle_21
    ],
    ignore_index=True,
    sort=False
)

print(
    "vehicle_quality rows:",
    f"{len(vehicle_quality):,}"
)

print(
    "Unique vehicle IDs:",
    vehicle_quality["ID_Fahrzeug"].is_unique
)

print(
    "\nVehicles by type:"
)

print(
    vehicle_quality[
        "Fahrzeugtyp"
    ].value_counts()
)

print(
    "\nMissing final defect:"
)

print(
    vehicle_quality[
        "Fehlerhaft_Gesamt"
    ].isna().sum()
)

vehicle_quality rows: 2,489,518
Unique vehicle IDs: True

Vehicles by type:
Fahrzeugtyp
Type11    1977164
Type21     512354
Name: count, dtype: int64

Missing final defect:
0

In [23]:
vehicle_quality[
    [
        "ID_Fahrzeug",
        "OEM",
        "Fahrzeugtyp",
        "Werksnummer",
        "ID_Karosserie",
        "ID_Schaltung",
        "ID_Sitze",
        "ID_Motor",
        "Tier1_Werksnummer_Karosserie",
        "Tier1_Werksnummer_Schaltung",
        "Tier1_Werksnummer_Sitze",
        "Tier1_Werksnummer_Motor",
        "Fehlerhaft_Fahrzeug_Roh",
        "Fehlerhaft_Karosserie",
        "Fehlerhaft_Schaltung",
        "Fehlerhaft_Sitze",
        "Fehlerhaft_Motor",
        "Anzahl_Fehlerhafte_Komponenten",
        "Fehlerhaft_Gesamt"
    ]
].head()

,ID_Fahrzeug,OEM,Fahrzeugtyp,Werksnummer,ID_Karosserie,ID_Schaltung,ID_Sitze,ID_Motor,Tier1_Werksnummer_Karosserie,Tier1_Werksnummer_Schaltung,Tier1_Werksnummer_Sitze,Tier1_Werksnummer_Motor,Fehlerhaft_Fahrzeug_Roh,Fehlerhaft_Karosserie,Fehlerhaft_Schaltung,Fehlerhaft_Sitze,Fehlerhaft_Motor,Anzahl_Fehlerhafte_Komponenten,Fehlerhaft_Gesamt
0,11-1-11-1,OEM1,Type11,11,K4-112-1121-3,K3SG1-105-1051-32,K2LE1-109-1091-2,K1BE1-101-1011-7,1121,1051,1091,1011,0,0,1,1,1,3,1
1,11-1-11-2,OEM1,Type11,11,K4-112-1121-4,K3SG1-105-1051-141,K2ST1-109-1092-5,K1BE1-101-1011-12,1121,1051,1092,1011,0,0,1,1,1,3,1
2,11-1-11-3,OEM1,Type11,11,K4-112-1121-7,K3SG1-105-1051-106,K2ST1-109-1092-57,K1BE1-101-1011-38,1121,1051,1092,1011,0,0,1,0,0,1,1
3,11-1-11-4,OEM1,Type11,11,K4-112-1121-9,K3SG1-105-1051-21,K2ST1-109-1092-91,K1BE1-101-1011-97,1121,1051,1092,1011,0,0,1,0,1,2,1
4,11-1-11-5,OEM1,Type11,11,K4-112-1121-11,K3SG1-105-1051-59,K2ST1-109-1092-4,K1BE1-101-1011-65,1121,1051,1092,1011,0,0,1,1,1,3,1

In [24]:
GEODATEN_FOLDER = Path("data/Geodaten")

path = GEODATEN_FOLDER / "OEM_Werke_2017-07-04_TrR.csv"

with path.open(
    "r",
    encoding="cp1252"
) as f:
    header = f.readline()

sep = ";" if header.count(";") > header.count(",") else ","

oem_werke = pd.read_csv(
    path,
    sep=sep,
    dtype="string",
    encoding="cp1252"
)

print("Separator:", repr(sep))
print("Shape:", oem_werke.shape)
print("Columns:")
print(oem_werke.columns.tolist())

display(oem_werke.head(10))

Separator: ';'
Shape: (5, 5)
Columns:
['PLZ ', 'ORT', 'Werk', 'Breitengrad', 'L„ngengrad']

    PLZ          ORT Werk Breitengrad L„ngengrad
0  90491   NUERNBERG  O11    49.46699  11.107353
1  53225        BONN  O12   50.742015   7.120073
2  33607   BIELEFELD  O13   52.022568   8.540961
3  37073  GOETTINGEN  O21   51.535703   9.932804
4  93051  REGENSBURG  O22   49.008761  12.080696

In [25]:
oem_werke = oem_werke.rename(
    columns={
        "PLZ ": "PLZ_OEM",
        "ORT": "ORT_OEM",
        "Werk": "Werksnummer_OEM",
        "Breitengrad": "Breitengrad_OEM",
        "L„ngengrad": "Laengengrad_OEM"
    }
)

oem_werke["Werksnummer_OEM"] = (
    oem_werke["Werksnummer_OEM"]
    .str.removeprefix("O")
)

oem_werke["PLZ_OEM"] = (
    oem_werke["PLZ_OEM"]
    .str.strip()
    .str.zfill(5)
)

oem_werke["Breitengrad_OEM"] = pd.to_numeric(
    oem_werke["Breitengrad_OEM"],
    errors="coerce"
)

oem_werke["Laengengrad_OEM"] = pd.to_numeric(
    oem_werke["Laengengrad_OEM"],
    errors="coerce"
)

vehicle_quality["Werksnummer"] = (
    vehicle_quality["Werksnummer"]
    .astype("string")
)

if not oem_werke["Werksnummer_OEM"].is_unique:
    raise ValueError(
        "Duplicate OEM plant numbers"
    )

display(oem_werke)

  PLZ_OEM     ORT_OEM Werksnummer_OEM  Breitengrad_OEM  Laengengrad_OEM
0   90491   NUERNBERG              11         49.46699        11.107353
1   53225        BONN              12        50.742015         7.120073
2   33607   BIELEFELD              13        52.022568         8.540961
3   37073  GOETTINGEN              21        51.535703         9.932804
4   93051  REGENSBURG              22        49.008761        12.080696

In [26]:
rows_before = len(vehicle_quality)

vehicle_quality = vehicle_quality.merge(
    oem_werke,
    how="left",
    left_on="Werksnummer",
    right_on="Werksnummer_OEM",
    validate="many_to_one"
)

print(
    "Rows before:",
    f"{rows_before:,}"
)

print(
    "Rows after:",
    f"{len(vehicle_quality):,}"
)

print(
    "Missing OEM plant:",
    vehicle_quality[
        "Werksnummer_OEM"
    ].isna().sum()
)

print(
    "\nVehicles by OEM plant:"
)

print(
    vehicle_quality[
        [
            "Werksnummer_OEM",
            "ORT_OEM"
        ]
    ]
    .value_counts()
    .sort_index()
)

Rows before: 2,489,518
Rows after: 2,489,518
Missing OEM plant: 0

Vehicles by OEM plant:
Werksnummer_OEM  ORT_OEM
11               NUERNBERG     1186298
12               BONN           790866
21               GOETTINGEN     512354
Name: count, dtype: int64

In [27]:
oem_plant_quality = (
    vehicle_quality
    .groupby(
        [
            "OEM",
            "Werksnummer_OEM",
            "ORT_OEM"
        ],
        as_index=False
    )
    .agg(
        Fahrzeuge=(
            "ID_Fahrzeug",
            "size"
        ),
        Fehlerhafte_Fahrzeuge=(
            "Fehlerhaft_Gesamt",
            "sum"
        ),
        Direkte_Fahrzeugfehler=(
            "Fehlerhaft_Fahrzeug_Roh",
            "sum"
        )
    )
)

oem_plant_quality[
    "Fehlerrate"
] = (
    oem_plant_quality[
        "Fehlerhafte_Fahrzeuge"
    ]
    / oem_plant_quality[
        "Fahrzeuge"
    ]
)

oem_plant_quality[
    "Direkte_Fehlerrate"
] = (
    oem_plant_quality[
        "Direkte_Fahrzeugfehler"
    ]
    / oem_plant_quality[
        "Fahrzeuge"
    ]
)

oem_plant_quality = (
    oem_plant_quality
    .sort_values(
        "Fehlerrate",
        ascending=False
    )
    .reset_index(drop=True)
)

display(oem_plant_quality)

,OEM,Werksnummer_OEM,ORT_OEM,Fahrzeuge,Fehlerhafte_Fahrzeuge,Direkte_Fahrzeugfehler,Fehlerrate,Direkte_Fehlerrate
0,OEM2,21,GOETTINGEN,512354,455877,50796,0.88977,0.099142
1,OEM1,11,NUERNBERG,1186298,1041102,118762,0.877606,0.100111
2,OEM1,12,BONN,790866,693991,79307,0.877508,0.100279

In [28]:
vehicle_quality[
    "Fehlerhaft_Komponenten"
] = combine_defect_flags(
    vehicle_quality["Fehlerhaft_Karosserie"],
    vehicle_quality["Fehlerhaft_Schaltung"],
    vehicle_quality["Fehlerhaft_Sitze"],
    vehicle_quality["Fehlerhaft_Motor"]
)

plant_source_quality = (
    vehicle_quality
    .groupby(
        [
            "OEM",
            "Werksnummer_OEM",
            "ORT_OEM"
        ],
        as_index=False
    )
    .agg(
        Fahrzeuge=(
            "ID_Fahrzeug",
            "size"
        ),
        Fahrzeug_Roh=(
            "Fehlerhaft_Fahrzeug_Roh",
            "mean"
        ),
        Karosserie=(
            "Fehlerhaft_Karosserie",
            "mean"
        ),
        Schaltung=(
            "Fehlerhaft_Schaltung",
            "mean"
        ),
        Sitze=(
            "Fehlerhaft_Sitze",
            "mean"
        ),
        Motor=(
            "Fehlerhaft_Motor",
            "mean"
        ),
        Irgendeine_Komponente=(
            "Fehlerhaft_Komponenten",
            "mean"
        ),
        Gesamt=(
            "Fehlerhaft_Gesamt",
            "mean"
        )
    )
)

display(
    plant_source_quality
    .sort_values(
        "Gesamt",
        ascending=False
    )
)

,OEM,Werksnummer_OEM,ORT_OEM,Fahrzeuge,Fahrzeug_Roh,Karosserie,Schaltung,Sitze,Motor,Irgendeine_Komponente,Gesamt
2,OEM2,21,GOETTINGEN,512354,0.099142,0.409797,0.343071,0.352897,0.510702,0.877667,0.88977
0,OEM1,11,NUERNBERG,1186298,0.100111,0.343994,0.347796,0.352218,0.509448,0.863973,0.877606
1,OEM1,12,BONN,790866,0.100279,0.343474,0.348039,0.351387,0.508315,0.863934,0.877508

In [29]:
karosserie_source_quality = (
    vehicle_quality
    .groupby(
        [
            "OEM",
            "Werksnummer_OEM",
            "ORT_OEM"
        ],
        as_index=False
    )
    .agg(
        Fahrzeuge=(
            "ID_Fahrzeug",
            "size"
        ),
        Karosserie_Roh=(
            "Fehlerhaft_Karosserie_Roh",
            "mean"
        ),
        Karosserie_Einzelteile=(
            "Fehlerhaft_Karosserie_Einzelteil",
            "mean"
        ),
        Karosserie_Gesamt=(
            "Fehlerhaft_Karosserie",
            "mean"
        )
    )
)

display(
    karosserie_source_quality
    .sort_values(
        "Karosserie_Gesamt",
        ascending=False
    )
)

,OEM,Werksnummer_OEM,ORT_OEM,Fahrzeuge,Karosserie_Roh,Karosserie_Einzelteile,Karosserie_Gesamt
2,OEM2,21,GOETTINGEN,512354,0.100046,0.344096,0.409797
0,OEM1,11,NUERNBERG,1186298,0.100256,0.270864,0.343994
1,OEM1,12,BONN,790866,0.099383,0.271113,0.343474

In [30]:
karosserie_tier1_quality = (
    vehicle_quality
    .groupby(
        [
            "OEM",
            "Werksnummer_OEM",
            "ORT_OEM",
            "Tier1_Werksnummer_Karosserie"
        ],
        as_index=False
    )
    .agg(
        Installierte_Karosserien=(
            "ID_Karosserie",
            "size"
        ),
        Fehlerhafte_Karosserien=(
            "Fehlerhaft_Karosserie",
            "sum"
        ),
        Karosserie_Roh=(
            "Fehlerhaft_Karosserie_Roh",
            "mean"
        ),
        Karosserie_Einzelteile=(
            "Fehlerhaft_Karosserie_Einzelteil",
            "mean"
        ),
        Fehlerrate=(
            "Fehlerhaft_Karosserie",
            "mean"
        )
    )
    .sort_values(
        "Fehlerrate",
        ascending=False
    )
    .reset_index(drop=True)
)

display(karosserie_tier1_quality)

,OEM,Werksnummer_OEM,ORT_OEM,Tier1_Werksnummer_Karosserie,Installierte_Karosserien,Fehlerhafte_Karosserien,Karosserie_Roh,Karosserie_Einzelteile,Fehlerrate
0,OEM2,21,GOETTINGEN,1141,256177,105077,0.100509,0.3442,0.410173
1,OEM2,21,GOETTINGEN,1132,256177,104884,0.099583,0.343993,0.40942
2,OEM1,11,NUERNBERG,1121,476070,163878,0.100122,0.271439,0.344231
3,OEM1,12,BONN,1141,476071,163695,0.099424,0.271417,0.343846
4,OEM1,11,NUERNBERG,1141,710228,244201,0.100347,0.270478,0.343835
5,OEM1,12,BONN,1121,314795,107947,0.099322,0.270652,0.342912

In [31]:
defect_level_quality = pd.DataFrame({
    "Ebene": [
        "Fahrzeug",
        "Karosserie",
        "Schaltung",
        "Sitze",
        "Motor"
    ],
    "Fehlerrate": [
        vehicle_quality[
            "Fehlerhaft_Fahrzeug_Roh"
        ].mean(),
        vehicle_quality[
            "Fehlerhaft_Karosserie_Roh"
        ].mean(),
        vehicle_quality[
            "Fehlerhaft_Schaltung_Roh"
        ].mean(),
        vehicle_quality[
            "Fehlerhaft_Sitze_Roh"
        ].mean(),
        vehicle_quality[
            "Fehlerhaft_Motor_Roh"
        ].mean()
    ]
})

display(defect_level_quality)

        Ebene  Fehlerrate
0    Fahrzeug    0.099965
1  Karosserie    0.099936
2   Schaltung    0.104209
3       Sitze    0.111218
4       Motor    0.138297

In [32]:
part_quality_rows = []

for family in sorted(relevant_families):
    parts = component_parts[family]

    bom = pd.read_csv(
        KOMPONENTE_FOLDER
        / f"Bestandteile_Komponente_{family}.csv",
        sep=";",
        dtype="string"
    )

    for part in parts:
        bom_column = f"ID_T{int(part[1:])}"

        part_data = pd.read_csv(
            EINZELTEIL_FOLDER
            / f"Einzelteil_{part}.csv",
            usecols=[
                "ID",
                "Fehlerhaft"
            ],
            dtype="string"
        )

        lookup = (
            pd.to_numeric(
                part_data["Fehlerhaft"],
                errors="coerce"
            )
            .groupby(
                part_data["ID"]
            )
            .max()
        )

        installed = pd.to_numeric(
            bom[bom_column].map(lookup),
            errors="coerce"
        )

        part_quality_rows.append({
            "Familie": family,
            "Einzelteil": part,
            "Komponenten_BOM": len(installed),
            "Fehlerrate": installed.mean()
        })

        del part_data
        del lookup
        del installed

    del bom

part_quality = pd.DataFrame(
    part_quality_rows
)

display(
    part_quality.sort_values(
        "Fehlerrate",
        ascending=False
    )
)

   Familie Einzelteil  Komponenten_BOM  Fehlerrate
4    K1BE2        T01           409422    0.220452
12   K1DI2        T01           409422    0.220037
8    K1DI1        T01          1192630    0.219698
0    K1BE1        T01          1192630    0.219652
29   K3AG1        T24           477052    0.100918
18   K2LE1        T15           477052    0.100677
14   K1DI2        T09           409422    0.100508
37   K3SG2        T21           655075    0.100427
21   K2LE2        T20           163769    0.100379
6    K1BE2        T07           409422    0.100322
20   K2LE2        T19           163769    0.100312
27   K2ST2        T18           655075    0.100298
3    K1BE1        T04          1192630    0.100295
26   K2ST2        T17           655075    0.100277
45      K6        T36           512354    0.100271
38   K3SG2        T22           655075    0.100265
25   K2ST2        T16           655075    0.100199
24   K2ST1        T13          1908208    0.100143
43      K6        T34           512354    0.100112
34   K3SG1        T21          1908208    0.100106
7    K1BE2        T08           409422    0.100095
42      K4        T32          1977164    0.100072
5    K1BE2        T02           409422    0.100068
40      K4        T30          1977164    0.100003
13   K1DI2        T02           409422    0.099992
11   K1DI1        T06          1192630    0.099991
15   K1DI2        T10           409422    0.099990
44      K6        T35           512354    0.099982
28   K3AG1        T21           477052    0.099979
36   K3SG1        T23          1908208    0.099917
9    K1DI1        T02          1192630    0.099896
22   K2ST1        T11          1908208    0.099886
2    K1BE1        T03          1192630    0.099868
33   K3AG2        T27           163769    0.099836
30   K3AG1        T25           477052    0.099828
35   K3SG1        T22          1908208    0.099826
41      K4        T31          1977164    0.099780
31   K3AG2        T21           163769    0.099775
1    K1BE1        T02          1192630    0.099741
39   K3SG2        T26           655075    0.099720
16   K2LE1        T11           477052    0.099675
23   K2ST1        T12          1908208    0.099635
10   K1DI1        T05          1192630    0.099615
46      K6        T37           512354    0.099576
17   K2LE1        T14           477052    0.099494
32   K3AG2        T24           163769    0.099317
19   K2LE2        T16           163769    0.099280

In [33]:
display(
    part_quality.sort_values(
        "Einzelteil",
        ascending=False
    )
)

   Familie Einzelteil  Komponenten_BOM  Fehlerrate
46      K6        T37           512354    0.099576
45      K6        T36           512354    0.100271
44      K6        T35           512354    0.099982
43      K6        T34           512354    0.100112
42      K4        T32          1977164    0.100072
41      K4        T31          1977164    0.099780
40      K4        T30          1977164    0.100003
33   K3AG2        T27           163769    0.099836
39   K3SG2        T26           655075    0.099720
30   K3AG1        T25           477052    0.099828
32   K3AG2        T24           163769    0.099317
29   K3AG1        T24           477052    0.100918
36   K3SG1        T23          1908208    0.099917
35   K3SG1        T22          1908208    0.099826
38   K3SG2        T22           655075    0.100265
37   K3SG2        T21           655075    0.100427
34   K3SG1        T21          1908208    0.100106
28   K3AG1        T21           477052    0.099979
31   K3AG2        T21           163769    0.099775
21   K2LE2        T20           163769    0.100379
20   K2LE2        T19           163769    0.100312
27   K2ST2        T18           655075    0.100298
26   K2ST2        T17           655075    0.100277
19   K2LE2        T16           163769    0.099280
25   K2ST2        T16           655075    0.100199
18   K2LE1        T15           477052    0.100677
17   K2LE1        T14           477052    0.099494
24   K2ST1        T13          1908208    0.100143
23   K2ST1        T12          1908208    0.099635
16   K2LE1        T11           477052    0.099675
22   K2ST1        T11          1908208    0.099886
15   K1DI2        T10           409422    0.099990
14   K1DI2        T09           409422    0.100508
7    K1BE2        T08           409422    0.100095
6    K1BE2        T07           409422    0.100322
11   K1DI1        T06          1192630    0.099991
10   K1DI1        T05          1192630    0.099615
3    K1BE1        T04          1192630    0.100295
2    K1BE1        T03          1192630    0.099868
1    K1BE1        T02          1192630    0.099741
5    K1BE2        T02           409422    0.100068
9    K1DI1        T02          1192630    0.099896
13   K1DI2        T02           409422    0.099992
8    K1DI1        T01          1192630    0.219698
4    K1BE2        T01           409422    0.220452
12   K1DI2        T01           409422    0.220037
0    K1BE1        T01          1192630    0.219652

In [34]:
motor_families = [
    "K1BE1",
    "K1DI1",
    "K1BE2",
    "K1DI2"
]

t01_rows = []

t01_data = pd.read_csv(
    EINZELTEIL_FOLDER / "Einzelteil_T01.csv",
    usecols=[
        "ID",
        "Werksnummer",
        "Fehlerhaft"
    ],
    dtype="string"
)

if not t01_data["ID"].is_unique:
    raise ValueError(
        "Duplicate T01 IDs"
    )

t01_lookup = t01_data.set_index("ID")

for family in motor_families:
    bom = pd.read_csv(
        KOMPONENTE_FOLDER
        / f"Bestandteile_Komponente_{family}.csv",
        sep=";",
        usecols=[
            f"ID_{family}",
            "ID_T1"
        ],
        dtype="string"
    )

    if not bom[f"ID_{family}"].is_unique:
        raise ValueError(
            f"{family}: duplicate BOM IDs"
        )

    motor_to_t01 = (
        bom
        .set_index(f"ID_{family}")["ID_T1"]
    )

    mask = (
        vehicle_quality["ID_Motor"]
        .astype("string")
        .str.startswith(f"{family}-")
    )

    installed = vehicle_quality.loc[
        mask,
        [
            "ID_Fahrzeug",
            "OEM",
            "Werksnummer_OEM",
            "ORT_OEM",
            "ID_Motor"
        ]
    ].copy()

    installed["Familie"] = family

    installed["ID_T01"] = (
        installed["ID_Motor"]
        .map(motor_to_t01)
    )

    installed["Tier2_Werksnummer_T01"] = (
        installed["ID_T01"]
        .map(
            t01_lookup["Werksnummer"]
        )
    )

    installed["Fehlerhaft_T01"] = pd.to_numeric(
        installed["ID_T01"].map(
            t01_lookup["Fehlerhaft"]
        ),
        errors="coerce"
    ).astype("Int8")

    t01_rows.append(installed)

    del bom
    del motor_to_t01
    del installed

t01_installed = pd.concat(
    t01_rows,
    ignore_index=True
)

del t01_rows
del t01_data
del t01_lookup

print(
    "Installed T01:",
    f"{len(t01_installed):,}"
)

print(
    "Missing T01 ID:",
    t01_installed[
        "ID_T01"
    ].isna().sum()
)

print(
    "Missing Tier2 plant:",
    t01_installed[
        "Tier2_Werksnummer_T01"
    ].isna().sum()
)

print(
    "Missing defect flag:",
    t01_installed[
        "Fehlerhaft_T01"
    ].isna().sum()
)

Installed T01: 2,489,518
Missing T01 ID: 0
Missing Tier2 plant: 0
Missing defect flag: 0

In [35]:
t01_supplier_quality = (
    t01_installed
    .groupby(
        "Tier2_Werksnummer_T01",
        as_index=False
    )
    .agg(
        Installierte_T01=(
            "ID_T01",
            "size"
        ),
        Fehlerhafte_T01=(
            "Fehlerhaft_T01",
            "sum"
        )
    )
)

t01_supplier_quality[
    "Fehlerrate"
] = (
    t01_supplier_quality[
        "Fehlerhafte_T01"
    ]
    /
    t01_supplier_quality[
        "Installierte_T01"
    ]
)

t01_supplier_quality = (
    t01_supplier_quality
    .sort_values(
        "Fehlerrate",
        ascending=False
    )
    .reset_index(drop=True)
)

display(t01_supplier_quality)

  Tier2_Werksnummer_T01  Installierte_T01  Fehlerhafte_T01  Fehlerrate
0                  2011            995857           248468    0.249502
1                  2044            498092            99416    0.199594
2                  2021            995569           198637    0.199521

In [36]:
t01_supplier_oem_quality = (
    t01_installed
    .groupby(
        [
            "Werksnummer_OEM",
            "ORT_OEM",
            "Tier2_Werksnummer_T01"
        ],
        as_index=False
    )
    .agg(
        Installierte_T01=(
            "ID_T01",
            "size"
        ),
        Fehlerhafte_T01=(
            "Fehlerhaft_T01",
            "sum"
        ),
        Fehlerrate=(
            "Fehlerhaft_T01",
            "mean"
        )
    )
    .sort_values(
        "Fehlerrate",
        ascending=False
    )
    .reset_index(drop=True)
)

display(t01_supplier_oem_quality)

,Werksnummer_OEM,ORT_OEM,Tier2_Werksnummer_T01,Installierte_T01,Fehlerhafte_T01,Fehlerrate
0,21,GOETTINGEN,2011,204581,51085,0.249705
1,11,NUERNBERG,2011,474516,118420,0.24956
2,12,BONN,2011,316760,78963,0.249283
3,11,NUERNBERG,2044,237372,47548,0.20031
4,11,NUERNBERG,2021,474410,94998,0.200245
5,21,GOETTINGEN,2044,102993,20589,0.199907
6,21,GOETTINGEN,2021,204780,40742,0.198955
7,12,BONN,2021,316379,62897,0.198803
8,12,BONN,2044,157727,31279,0.198311

In [37]:
path = GEODATEN_FOLDER / "Tier2_Werke_2017-07-11_v1.2_TrR.csv"

with path.open(
    "r",
    encoding="cp1252",
    errors="replace"
) as f:
    header = f.readline()

sep = ";" if header.count(";") > header.count(",") else ","

tier2_werke = pd.read_csv(
    path,
    sep=sep,
    dtype="string",
    encoding="cp1252"
)

print("Separator:", repr(sep))
print("Shape:", tier2_werke.shape)
print("Columns:")
print(tier2_werke.columns.tolist())

display(tier2_werke.head(10))

Separator: ';'
Shape: (45, 18)
Columns:
['PLZ', 'ORT ', 'Werk', 'Breitengrad', 'L„ngengrad', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17']

,PLZ,ORT,Werk,Breitengrad,L„ngengrad,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17
0,90762,FUERTH,2011,49.477859,10.988665,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1,96047,BAMBERG,2012,49.86667,10.86667,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
2,86150,AUGSBURG,2021,48.369099,10.893711,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
3,69115,HEIDELBERG,2022,49.40027,8.677846,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
4,63739,ASCHAFFENBURG,2023,49.40027,8.677846,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
5,34277,FULDABRUECK,2031,51.247524,9.483038,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
6,99092,ERFURT,2032,50.981092,11.006537,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
7,15517,FUERSTENWALDE/SPREE,2041,52.347883,14.062828,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
8,14770,BRANDENBURG/HAVEL,2042,52.408413,12.504185,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
9,56068,KOBLENZ,2043,50.3485,7.593805,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

In [38]:
tier2_werke = (
    tier2_werke[
        [
            "PLZ",
            "ORT ",
            "Werk",
            "Breitengrad",
            "L„ngengrad"
        ]
    ]
    .rename(
        columns={
            "PLZ": "PLZ_Tier2",
            "ORT ": "ORT_Tier2",
            "Werk": "Tier2_Werksnummer",
            "Breitengrad": "Breitengrad_Tier2",
            "L„ngengrad": "Laengengrad_Tier2"
        }
    )
)

tier2_werke["PLZ_Tier2"] = (
    tier2_werke["PLZ_Tier2"]
    .str.strip()
    .str.zfill(5)
)

tier2_werke["ORT_Tier2"] = (
    tier2_werke["ORT_Tier2"]
    .str.strip()
)

tier2_werke["Tier2_Werksnummer"] = (
    tier2_werke["Tier2_Werksnummer"]
    .str.strip()
)

tier2_werke["Breitengrad_Tier2"] = pd.to_numeric(
    tier2_werke["Breitengrad_Tier2"],
    errors="coerce"
)

tier2_werke["Laengengrad_Tier2"] = pd.to_numeric(
    tier2_werke["Laengengrad_Tier2"],
    errors="coerce"
)

tier2_werke = tier2_werke.dropna(
    subset=[
        "Tier2_Werksnummer",
        "ORT_Tier2"
    ]
)

if not tier2_werke[
    "Tier2_Werksnummer"
].is_unique:
    raise ValueError(
        "Duplicate Tier-2 plant numbers"
    )

display(tier2_werke.head(10))

,PLZ_Tier2,ORT_Tier2,Tier2_Werksnummer,Breitengrad_Tier2,Laengengrad_Tier2
0,90762,FUERTH,2011,49.477859,10.988665
1,96047,BAMBERG,2012,49.86667,10.86667
2,86150,AUGSBURG,2021,48.369099,10.893711
3,69115,HEIDELBERG,2022,49.40027,8.677846
4,63739,ASCHAFFENBURG,2023,49.40027,8.677846
5,34277,FULDABRUECK,2031,51.247524,9.483038
6,99092,ERFURT,2032,50.981092,11.006537
7,15517,FUERSTENWALDE/SPREE,2041,52.347883,14.062828
8,14770,BRANDENBURG/HAVEL,2042,52.408413,12.504185
9,56068,KOBLENZ,2043,50.3485,7.593805

In [39]:
t01_supplier_quality = (
    t01_supplier_quality
    .merge(
        tier2_werke,
        how="left",
        left_on="Tier2_Werksnummer_T01",
        right_on="Tier2_Werksnummer",
        validate="one_to_one"
    )
)

print(
    "Missing Tier-2 locations:",
    t01_supplier_quality[
        "ORT_Tier2"
    ].isna().sum()
)

display(
    t01_supplier_quality[
        [
            "Tier2_Werksnummer_T01",
            "ORT_Tier2",
            "PLZ_Tier2",
            "Installierte_T01",
            "Fehlerhafte_T01",
            "Fehlerrate"
        ]
    ]
    .sort_values(
        "Fehlerrate",
        ascending=False
    )
)

Missing Tier-2 locations: 0

,Tier2_Werksnummer_T01,ORT_Tier2,PLZ_Tier2,Installierte_T01,Fehlerhafte_T01,Fehlerrate
0,2011,FUERTH,90762,995857,248468,0.249502
1,2044,WERTHEIM,97877,498092,99416,0.199594
2,2021,AUGSBURG,86150,995569,198637,0.199521

In [40]:
path = GEODATEN_FOLDER / "Tier1_Werke_2017-07-11_v1.2_TrR.csv"

with path.open(
    "r",
    encoding="cp1252",
    errors="replace"
) as f:
    header = f.readline()

sep = ";" if header.count(";") > header.count(",") else ","

tier1_werke = pd.read_csv(
    path,
    sep=sep,
    dtype="string",
    encoding="cp1252"
)

print("Separator:", repr(sep))
print("Shape:", tier1_werke.shape)
print("Columns:")
print(tier1_werke.columns.tolist())

display(tier1_werke.head(10))

Separator: ';'
Shape: (45, 5)
Columns:
['PLZ ', 'ORT', 'Werk', 'Breitengrad', 'L„ngengrad']

    PLZ              ORT  Werk Breitengrad L„ngengrad
0  81247        MUENCHEN  1011   48.169568  11.470707
1  04179         LEIPZIG  1021   51.333708  12.311921
2  01157         DRESDEN  1031   51.056901  13.666837
3  10365          BERLIN  1041   52.521622  13.488954
4  97422     SCHWEINFURT  1051    50.05266    10.2389
5  21037         HAMBURG  1052   53.462128   10.08458
6  44267        DORTMUND  1053   51.474325   7.516086
7  30163        HANNOVER  1061   52.391025   9.744884
8  60325  FRANKFURT/MAIN  1071   50.115855   8.660156
9  70184       STUTTGART  1072   48.776599   9.198399

In [41]:
tier1_werke = (
    tier1_werke
    .rename(
        columns={
            "PLZ ": "PLZ_Tier1",
            "ORT": "ORT_Tier1",
            "Werk": "Tier1_Werksnummer",
            "Breitengrad": "Breitengrad_Tier1",
            "L„ngengrad": "Laengengrad_Tier1"
        }
    )
)

tier1_werke["PLZ_Tier1"] = (
    tier1_werke["PLZ_Tier1"]
    .str.strip()
    .str.zfill(5)
)

tier1_werke["ORT_Tier1"] = (
    tier1_werke["ORT_Tier1"]
    .str.strip()
)

tier1_werke["Tier1_Werksnummer"] = (
    tier1_werke["Tier1_Werksnummer"]
    .str.strip()
)

tier1_werke["Breitengrad_Tier1"] = pd.to_numeric(
    tier1_werke["Breitengrad_Tier1"],
    errors="coerce"
)

tier1_werke["Laengengrad_Tier1"] = pd.to_numeric(
    tier1_werke["Laengengrad_Tier1"],
    errors="coerce"
)

tier1_werke = (
    tier1_werke
    .dropna(
        subset=[
            "Tier1_Werksnummer",
            "ORT_Tier1"
        ]
    )
)

tier1_werke = tier1_werke[
    tier1_werke["Tier1_Werksnummer"].ne("")
]

tier1_werke = (
    tier1_werke
    .drop_duplicates()
    .reset_index(drop=True)
)

duplicates = tier1_werke[
    tier1_werke.duplicated(
        "Tier1_Werksnummer",
        keep=False
    )
]

if not duplicates.empty:
    conflicts = (
        duplicates
        .groupby(
            "Tier1_Werksnummer"
        )[
            [
                "PLZ_Tier1",
                "ORT_Tier1",
                "Breitengrad_Tier1",
                "Laengengrad_Tier1"
            ]
        ]
        .nunique(
            dropna=False
        )
    )

    conflicting_ids = conflicts[
        conflicts.gt(1).any(axis=1)
    ].index

    if len(conflicting_ids):
        display(
            duplicates[
                duplicates[
                    "Tier1_Werksnummer"
                ].isin(conflicting_ids)
            ]
        )

        raise ValueError(
            "Conflicting Tier-1 plant metadata"
        )

tier1_werke = (
    tier1_werke
    .drop_duplicates(
        "Tier1_Werksnummer"
    )
    .reset_index(drop=True)
)

print(
    "Tier-1 plants:",
    len(tier1_werke)
)

print(
    "Unique plant numbers:",
    tier1_werke[
        "Tier1_Werksnummer"
    ].is_unique
)

display(tier1_werke.head(10))

Tier-1 plants: 22
Unique plant numbers: True

,PLZ_Tier1,ORT_Tier1,Tier1_Werksnummer,Breitengrad_Tier1,Laengengrad_Tier1
0,81247,MUENCHEN,1011,48.169568,11.470707
1,04179,LEIPZIG,1021,51.333708,12.311921
2,01157,DRESDEN,1031,51.056901,13.666837
3,10365,BERLIN,1041,52.521622,13.488954
4,97422,SCHWEINFURT,1051,50.05266,10.2389
5,21037,HAMBURG,1052,53.462128,10.08458
6,44267,DORTMUND,1053,51.474325,7.516086
7,30163,HANNOVER,1061,52.391025,9.744884
8,60325,FRANKFURT/MAIN,1071,50.115855,8.660156
9,70184,STUTTGART,1072,48.776599,9.198399

In [42]:
tier1_lookup = (
    tier1_werke
    .set_index(
        "Tier1_Werksnummer"
    )
)

for role in roles:
    plant_column = (
        f"Tier1_Werksnummer_{role}"
    )

    vehicle_quality[
        f"ORT_Tier1_{role}"
    ] = (
        vehicle_quality[
            plant_column
        ]
        .map(
            tier1_lookup[
                "ORT_Tier1"
            ]
        )
    )

    vehicle_quality[
        f"PLZ_Tier1_{role}"
    ] = (
        vehicle_quality[
            plant_column
        ]
        .map(
            tier1_lookup[
                "PLZ_Tier1"
            ]
        )
    )

    vehicle_quality[
        f"Breitengrad_Tier1_{role}"
    ] = pd.to_numeric(
        vehicle_quality[
            plant_column
        ]
        .map(
            tier1_lookup[
                "Breitengrad_Tier1"
            ]
        ),
        errors="coerce"
    )

    vehicle_quality[
        f"Laengengrad_Tier1_{role}"
    ] = pd.to_numeric(
        vehicle_quality[
            plant_column
        ]
        .map(
            tier1_lookup[
                "Laengengrad_Tier1"
            ]
        ),
        errors="coerce"
    )

print(
    "Missing Tier-1 locations:",
    sum(
        vehicle_quality[
            f"ORT_Tier1_{role}"
        ].isna().sum()
        for role in roles
    )
)

del tier1_lookup

Missing Tier-1 locations: 0

In [43]:
tier1_quality_rows = []

for role in roles:
    plant_column = f"Tier1_Werksnummer_{role}"

    summary = (
        vehicle_quality
        .groupby(
            [
                "OEM",
                "Werksnummer_OEM",
                "ORT_OEM",
                plant_column
            ],
            as_index=False
        )
        .agg(
            Einheiten=(
                f"ID_{role}",
                "size"
            ),
            Fehlerhaft=(
                f"Fehlerhaft_{role}",
                "sum"
            ),
            Direkte_Fehler=(
                f"Fehlerhaft_{role}_Roh",
                "sum"
            )
        )
        .rename(
            columns={
                plant_column:
                    "Tier1_Werksnummer"
            }
        )
    )

    summary["Typ"] = role

    summary["Fehlerrate"] = (
        summary["Fehlerhaft"]
        / summary["Einheiten"]
    )

    summary["Direkte_Fehlerrate"] = (
        summary["Direkte_Fehler"]
        / summary["Einheiten"]
    )

    tier1_quality_rows.append(summary)

tier1_quality = pd.concat(
    tier1_quality_rows,
    ignore_index=True
)

del tier1_quality_rows

tier1_quality = tier1_quality.merge(
    tier1_werke,
    how="left",
    on="Tier1_Werksnummer",
    validate="many_to_one"
)

tier1_quality = (
    tier1_quality
    .sort_values(
        "Fehlerrate",
        ascending=False
    )
    .reset_index(drop=True)
)

display(tier1_quality)

,OEM,Werksnummer_OEM,ORT_OEM,Tier1_Werksnummer,Einheiten,Fehlerhaft,Direkte_Fehler,Typ,Fehlerrate,Direkte_Fehlerrate,PLZ_Tier1,ORT_Tier1,Breitengrad_Tier1,Laengengrad_Tier1
0,OEM2,21,GOETTINGEN,1011,53575,28511,9588,Motor,0.53217,0.178964,81247,MUENCHEN,48.169568,11.470707
1,OEM1,11,NUERNBERG,1041,355953,189113,62156,Motor,0.531286,0.174619,10365,BERLIN,52.521622,13.488954
2,OEM2,21,GOETTINGEN,1041,215701,114443,37727,Motor,0.530563,0.174904,10365,BERLIN,52.521622,13.488954
3,OEM1,12,BONN,1041,236941,125598,41564,Motor,0.530081,0.175419,10365,BERLIN,52.521622,13.488954
4,OEM1,11,NUERNBERG,1011,415119,210228,55144,Motor,0.506428,0.132839,81247,MUENCHEN,48.169568,11.470707
5,OEM1,12,BONN,1011,276712,139824,36811,Motor,0.505305,0.13303,81247,MUENCHEN,48.169568,11.470707
6,OEM1,11,NUERNBERG,1021,178368,89556,22341,Motor,0.502086,0.125252,04179,LEIPZIG,51.333708,12.311921
7,OEM1,12,BONN,1021,118791,59624,14984,Motor,0.501924,0.126138,04179,LEIPZIG,51.333708,12.311921
8,OEM2,21,GOETTINGEN,1021,143639,70235,14343,Motor,0.488969,0.099854,04179,LEIPZIG,51.333708,12.311921
9,OEM1,11,NUERNBERG,1031,236858,115460,23806,Motor,0.487465,0.100507,01157,DRESDEN,51.056901,13.666837
10,OEM2,21,GOETTINGEN,1031,99439,48471,10010,Motor,0.487445,0.100665,01157,DRESDEN,51.056901,13.666837
11,OEM1,12,BONN,1031,158422,76963,15820,Motor,0.48581,0.09986,01157,DRESDEN,51.056901,13.666837
12,OEM1,11,NUERNBERG,1111,142651,59574,28559,Sitze,0.417621,0.200202,44143,DORTMUND,51.520312,7.480238
13,OEM2,21,GOETTINGEN,1111,61713,25740,12304,Sitze,0.417092,0.199375,44143,DORTMUND,51.520312,7.480238
14,OEM1,12,BONN,1111,94925,39232,18690,Sitze,0.413295,0.196892,44143,DORTMUND,51.520312,7.480238
15,OEM2,21,GOETTINGEN,1141,256177,105077,25748,Karosserie,0.410173,0.100509,08112,ZWICKAU,50.68766,12.515885
16,OEM2,21,GOETTINGEN,1132,256177,104884,25511,Karosserie,0.40942,0.099583,84036,Landshut,48.552219,12.187357
17,OEM1,11,NUERNBERG,1051,451011,160305,52157,Schaltung,0.355435,0.115645,97422,SCHWEINFURT,50.05266,10.2389
18,OEM1,12,BONN,1051,299815,106462,34436,Schaltung,0.355092,0.114857,97422,SCHWEINFURT,50.05266,10.2389
19,OEM2,21,GOETTINGEN,1072,81638,28314,8176,Schaltung,0.346824,0.100149,70184,STUTTGART,48.776599,9.198399
20,OEM1,11,NUERNBERG,1082,47578,16459,4759,Schaltung,0.345937,0.100025,87779,TRUNKELSBERG,48.000631,10.214855
21,OEM2,21,GOETTINGEN,1092,245801,84827,24692,Sitze,0.345104,0.100455,97080,WUERZBURG,48.748784,11.487228
22,OEM2,21,GOETTINGEN,1101,163742,56466,16507,Sitze,0.344847,0.100811,99867,GOTHA,50.921596,10.713028
23,OEM1,11,NUERNBERG,1061,118972,40956,11711,Schaltung,0.344249,0.098435,30163,HANNOVER,52.391025,9.744884
24,OEM1,11,NUERNBERG,1121,476070,163878,47665,Karosserie,0.344231,0.100122,38120,BRAUNSCHWEIG,52.25431,10.490542
25,OEM1,12,BONN,1071,380697,130988,38050,Schaltung,0.344074,0.099948,60325,FRANKFURT/MAIN,50.115855,8.660156
26,OEM1,11,NUERNBERG,1092,948571,326241,94978,Sitze,0.343929,0.100127,97080,WUERZBURG,48.748784,11.487228
27,OEM1,12,BONN,1141,476071,163695,47333,Karosserie,0.343846,0.099424,08112,ZWICKAU,50.68766,12.515885
28,OEM1,11,NUERNBERG,1141,710228,244201,71269,Karosserie,0.343835,0.100347,08112,ZWICKAU,50.68766,12.515885
29,OEM1,12,BONN,1092,632696,217321,63128,Sitze,0.343484,0.099776,97080,WUERZBURG,48.748784,11.487228
30,OEM1,12,BONN,1121,314795,107947,31266,Karosserie,0.342912,0.099322,38120,BRAUNSCHWEIG,52.25431,10.490542
31,OEM1,12,BONN,1061,78747,26988,8022,Schaltung,0.342718,0.101871,30163,HANNOVER,52.391025,9.744884
32,OEM1,11,NUERNBERG,1071,568737,194870,56580,Schaltung,0.342636,0.099484,60325,FRANKFURT/MAIN,50.115855,8.660156
33,OEM2,21,GOETTINGEN,1082,61532,21069,6092,Schaltung,0.342407,0.099005,87779,TRUNKELSBERG,48.000631,10.214855
34,OEM2,21,GOETTINGEN,1051,246288,84327,24373,Schaltung,0.342392,0.098961,97422,SCHWEINFURT,50.05266,10.2389
35,OEM2,21,GOETTINGEN,1081,122896,42064,12029,Schaltung,0.342273,0.09788,76227,KARLSRUHE,48.989874,8.460197
36,OEM1,12,BONN,1082,31607,10814,3044,Schaltung,0.342139,0.096308,87779,TRUNKELSBERG,48.000631,10.214855
37,OEM1,12,BONN,1091,63245,21347,5681,Sitze,0.337529,0.089825,85053,INGOLSTADT,48.748784,11.487228
38,OEM1,11,NUERNBERG,1091,95076,32020,8591,Sitze,0.336783,0.090359,85053,INGOLSTADT,48.748784,11.487228
39,OEM2,21,GOETTINGEN,1091,41098,13775,3748,Sitze,0.335174,0.091197,85053,INGOLSTADT,48.748784,11.487228

In [44]:
print(
    "Tier-1 summary rows:",
    len(tier1_quality)
)

print(
    "Missing Tier-1 locations:",
    tier1_quality[
        "ORT_Tier1"
    ].isna().sum()
)

print(
    "Total installed component assignments:",
    f"{tier1_quality['Einheiten'].sum():,}"
)

print(
    "\nHighest propagated Tier-1 defect rates:"
)

display(
    tier1_quality[
        [
            "OEM",
            "Werksnummer_OEM",
            "ORT_OEM",
            "Typ",
            "Tier1_Werksnummer",
            "ORT_Tier1",
            "Einheiten",
            "Fehlerhaft",
            "Fehlerrate",
            "Direkte_Fehlerrate"
        ]
    ].head(20)
)

Tier-1 summary rows: 40
Missing Tier-1 locations: 0
Total installed component assignments: 9,958,072

Highest propagated Tier-1 defect rates:

,OEM,Werksnummer_OEM,ORT_OEM,Typ,Tier1_Werksnummer,ORT_Tier1,Einheiten,Fehlerhaft,Fehlerrate,Direkte_Fehlerrate
0,OEM2,21,GOETTINGEN,Motor,1011,MUENCHEN,53575,28511,0.53217,0.178964
1,OEM1,11,NUERNBERG,Motor,1041,BERLIN,355953,189113,0.531286,0.174619
2,OEM2,21,GOETTINGEN,Motor,1041,BERLIN,215701,114443,0.530563,0.174904
3,OEM1,12,BONN,Motor,1041,BERLIN,236941,125598,0.530081,0.175419
4,OEM1,11,NUERNBERG,Motor,1011,MUENCHEN,415119,210228,0.506428,0.132839
5,OEM1,12,BONN,Motor,1011,MUENCHEN,276712,139824,0.505305,0.13303
6,OEM1,11,NUERNBERG,Motor,1021,LEIPZIG,178368,89556,0.502086,0.125252
7,OEM1,12,BONN,Motor,1021,LEIPZIG,118791,59624,0.501924,0.126138
8,OEM2,21,GOETTINGEN,Motor,1021,LEIPZIG,143639,70235,0.488969,0.099854
9,OEM1,11,NUERNBERG,Motor,1031,DRESDEN,236858,115460,0.487465,0.100507
10,OEM2,21,GOETTINGEN,Motor,1031,DRESDEN,99439,48471,0.487445,0.100665
11,OEM1,12,BONN,Motor,1031,DRESDEN,158422,76963,0.48581,0.09986
12,OEM1,11,NUERNBERG,Sitze,1111,DORTMUND,142651,59574,0.417621,0.200202
13,OEM2,21,GOETTINGEN,Sitze,1111,DORTMUND,61713,25740,0.417092,0.199375
14,OEM1,12,BONN,Sitze,1111,DORTMUND,94925,39232,0.413295,0.196892
15,OEM2,21,GOETTINGEN,Karosserie,1141,ZWICKAU,256177,105077,0.410173,0.100509
16,OEM2,21,GOETTINGEN,Karosserie,1132,Landshut,256177,104884,0.40942,0.099583
17,OEM1,11,NUERNBERG,Schaltung,1051,SCHWEINFURT,451011,160305,0.355435,0.115645
18,OEM1,12,BONN,Schaltung,1051,SCHWEINFURT,299815,106462,0.355092,0.114857
19,OEM2,21,GOETTINGEN,Schaltung,1072,STUTTGART,81638,28314,0.346824,0.100149

In [45]:
ZULASSUNGEN_FOLDER = Path("data/Zulassungen")

path = (
    ZULASSUNGEN_FOLDER
    / "Zulassungen_alle_Fahrzeuge.csv"
)

print(path)
print("Exists:", path.exists())
print("Is file:", path.is_file())
print("Is dir:", path.is_dir())

if path.is_file():
    with path.open(
        "r",
        encoding="cp1252",
        errors="replace"
    ) as f:
        for _ in range(5):
            print(repr(f.readline()))

if path.is_dir():
    for item in sorted(path.iterdir()):
        print(item.name)

data/Zulassungen/Zulassungen_alle_Fahrzeuge.csv
Exists: True
Is file: True
Is dir: False
'"";"IDNummer";"Gemeinden";"Zulassung"\n'
'"408097";"11-1-11-1";"DRESDEN";2009-01-01\n'
'"408098";"11-1-11-2";"DRESDEN";2009-01-01\n'
'"1";"12-1-12-1";"LEIPZIG";2009-01-01\n'
'"2";"12-1-12-2";"LEIPZIG";2009-01-01\n'

In [46]:
zulassungen = pd.read_csv(
    path,
    sep=";",
    encoding="cp1252",
    dtype="string",
    usecols=[
        "IDNummer",
        "Gemeinden",
        "Zulassung"
    ]
)

zulassungen = zulassungen.rename(
    columns={
        "IDNummer": "ID_Fahrzeug",
        "Gemeinden": "Gemeinde_Zulassung",
        "Zulassung": "Zulassungsdatum"
    }
)

zulassungen["ID_Fahrzeug"] = (
    zulassungen["ID_Fahrzeug"]
    .str.strip()
)

zulassungen["Gemeinde_Zulassung"] = (
    zulassungen["Gemeinde_Zulassung"]
    .str.strip()
)

zulassungen["Zulassungsdatum"] = pd.to_datetime(
    zulassungen["Zulassungsdatum"],
    errors="coerce"
)

print(
    "Registration rows:",
    f"{len(zulassungen):,}"
)

print(
    "Unique vehicle IDs:",
    zulassungen[
        "ID_Fahrzeug"
    ].is_unique
)

print(
    "Duplicate vehicle IDs:",
    zulassungen[
        "ID_Fahrzeug"
    ].duplicated().sum()
)

print(
    "Missing vehicle IDs:",
    zulassungen[
        "ID_Fahrzeug"
    ].isna().sum()
)

print(
    "Missing municipality:",
    zulassungen[
        "Gemeinde_Zulassung"
    ].isna().sum()
)

print(
    "Invalid registration dates:",
    zulassungen[
        "Zulassungsdatum"
    ].isna().sum()
)

print(
    "Vehicles without registration:",
    (
        ~vehicle_quality[
            "ID_Fahrzeug"
        ].isin(
            zulassungen[
                "ID_Fahrzeug"
            ]
        )
    ).sum()
)

print(
    "Registrations without vehicle:",
    (
        ~zulassungen[
            "ID_Fahrzeug"
        ].isin(
            vehicle_quality[
                "ID_Fahrzeug"
            ]
        )
    ).sum()
)

display(zulassungen.head())

Registration rows: 3,204,104
Unique vehicle IDs: True
Duplicate vehicle IDs: 0
Missing vehicle IDs: 0
Missing municipality: 0
Invalid registration dates: 0
Vehicles without registration: 0
Registrations without vehicle: 714586

  ID_Fahrzeug Gemeinde_Zulassung Zulassungsdatum
0   11-1-11-1            DRESDEN      2009-01-01
1   11-1-11-2            DRESDEN      2009-01-01
2   12-1-12-1            LEIPZIG      2009-01-01
3   12-1-12-2            LEIPZIG      2009-01-01
4   12-1-12-3           DORTMUND      2009-01-01

In [47]:
zulassungen = zulassungen[
    zulassungen[
        "ID_Fahrzeug"
    ].isin(
        vehicle_quality[
            "ID_Fahrzeug"
        ]
    )
].copy()

rows_before = len(
    vehicle_quality
)

vehicle_quality = vehicle_quality.merge(
    zulassungen,
    how="left",
    on="ID_Fahrzeug",
    validate="one_to_one"
)

print(
    "Rows before:",
    f"{rows_before:,}"
)

print(
    "Rows after:",
    f"{len(vehicle_quality):,}"
)

print(
    "Missing municipalities:",
    vehicle_quality[
        "Gemeinde_Zulassung"
    ].isna().sum()
)

print(
    "Missing registration dates:",
    vehicle_quality[
        "Zulassungsdatum"
    ].isna().sum()
)

print(
    "Unique vehicle IDs:",
    vehicle_quality[
        "ID_Fahrzeug"
    ].is_unique
)

display(
    vehicle_quality[
        [
            "ID_Fahrzeug",
            "OEM",
            "Fahrzeugtyp",
            "Werksnummer_OEM",
            "ORT_OEM",
            "Gemeinde_Zulassung",
            "Zulassungsdatum",
            "Fehlerhaft_Gesamt"
        ]
    ].head()
)

Rows before: 2,489,518
Rows after: 2,489,518
Missing municipalities: 0
Missing registration dates: 0
Unique vehicle IDs: True

,ID_Fahrzeug,OEM,Fahrzeugtyp,Werksnummer_OEM,ORT_OEM,Gemeinde_Zulassung,Zulassungsdatum,Fehlerhaft_Gesamt
0,11-1-11-1,OEM1,Type11,11,NUERNBERG,DRESDEN,2009-01-01,1
1,11-1-11-2,OEM1,Type11,11,NUERNBERG,DRESDEN,2009-01-01,1
2,11-1-11-3,OEM1,Type11,11,NUERNBERG,KOELN,2009-01-01,1
3,11-1-11-4,OEM1,Type11,11,NUERNBERG,KOELN,2009-01-01,1
4,11-1-11-5,OEM1,Type11,11,NUERNBERG,KOELN,2009-01-01,1

In [48]:
for item in sorted(
    GEODATEN_FOLDER.iterdir()
):
    if "Gemeind" in item.name:
        print(item.name)

Geodaten_Gemeinden_v1.2_2017-08-22_TrR.csv

In [49]:
gemeinde_path = (
    GEODATEN_FOLDER
    / "Geodaten_Gemeinden_v1.2_2017-08-22_TrR.csv"
)

with gemeinde_path.open(
    "r",
    encoding="cp1252",
    errors="replace"
) as f:
    header = f.readline()

sep = ";" if header.count(";") > header.count(",") else ","

gemeinden = pd.read_csv(
    gemeinde_path,
    sep=sep,
    encoding="cp1252",
    dtype="string"
)

print("Separator:", repr(sep))
print("Shape:", gemeinden.shape)
print("Columns:")
print(gemeinden.columns.tolist())

display(gemeinden.head(10))

Separator: ';'
Shape: (7775, 6)
Columns:
['Unnamed: 0', 'X', 'Postleitzahl', 'Gemeinde', 'Laengengrad', 'Breitengrad']

  Unnamed: 0   X Postleitzahl           Gemeinde Laengengrad Breitengrad
0          1   1         1067            DRESDEN   13,736883   51,051697
1          2   2         1445           RADEBEUL   13,659342   51,105975
2          3   3         1454           RADEBERG   13,921969   51,116404
3          4   4         1454             WACHAU   13,904681   51,160116
4          5   5         1458  OTTENDORF OKRILLA   13,831724   51,187617
5          6   6         1468         MORITZBURG    13,68009   51,159495
6          7   7         1471           RADEBURG   13,723805   51,215453
7          8   8         1477           ARNSDORF   13,992798   51,097715
8          9   9         1558        GROSSENHAIN    13,53055   51,292057
9         10  10         1561          EBERSBACH   13,658579   51,233487

In [50]:
gemeinden = (
    gemeinden[
        [
            "Postleitzahl",
            "Gemeinde",
            "Laengengrad",
            "Breitengrad"
        ]
    ]
    .rename(
        columns={
            "Postleitzahl": "PLZ_Gemeinde",
            "Gemeinde": "Gemeinde_Zulassung",
            "Laengengrad": "Laengengrad_Gemeinde",
            "Breitengrad": "Breitengrad_Gemeinde"
        }
    )
)

gemeinden["PLZ_Gemeinde"] = (
    gemeinden["PLZ_Gemeinde"]
    .str.strip()
    .str.zfill(5)
)

gemeinden["Gemeinde_Zulassung"] = (
    gemeinden["Gemeinde_Zulassung"]
    .str.strip()
)

gemeinden["Laengengrad_Gemeinde"] = pd.to_numeric(
    gemeinden["Laengengrad_Gemeinde"]
    .str.replace(",", ".", regex=False),
    errors="coerce"
)

gemeinden["Breitengrad_Gemeinde"] = pd.to_numeric(
    gemeinden["Breitengrad_Gemeinde"]
    .str.replace(",", ".", regex=False),
    errors="coerce"
)

duplicate_names = gemeinden[
    gemeinden.duplicated(
        "Gemeinde_Zulassung",
        keep=False
    )
]

registration_municipalities = set(
    vehicle_quality[
        "Gemeinde_Zulassung"
    ].dropna()
)

relevant_duplicates = duplicate_names[
    duplicate_names[
        "Gemeinde_Zulassung"
    ].isin(
        registration_municipalities
    )
]

missing_municipalities = (
    vehicle_quality[
        "Gemeinde_Zulassung"
    ]
    .drop_duplicates()
    .loc[
        lambda x:
        ~x.isin(
            gemeinden[
                "Gemeinde_Zulassung"
            ]
        )
    ]
)

print(
    "Municipality rows:",
    len(gemeinden)
)

print(
    "Unique municipality names:",
    gemeinden[
        "Gemeinde_Zulassung"
    ].nunique()
)

print(
    "Duplicate municipality names:",
    duplicate_names[
        "Gemeinde_Zulassung"
    ].nunique()
)

print(
    "Relevant duplicate municipality names:",
    relevant_duplicates[
        "Gemeinde_Zulassung"
    ].nunique()
)

print(
    "Registration municipalities missing from geodata:",
    len(missing_municipalities)
)

print(
    "Invalid coordinates:",
    gemeinden[
        [
            "Breitengrad_Gemeinde",
            "Laengengrad_Gemeinde"
        ]
    ].isna().any(axis=1).sum()
)

if not relevant_duplicates.empty:
    display(
        relevant_duplicates.sort_values(
            "Gemeinde_Zulassung"
        )
    )

if len(missing_municipalities):
    display(
        missing_municipalities.to_frame(
            "Gemeinde_Zulassung"
        )
    )

Municipality rows: 7775
Unique municipality names: 7774
Duplicate municipality names: 0
Relevant duplicate municipality names: 0
Registration municipalities missing from geodata: 1
Invalid coordinates: 0

      Gemeinde_Zulassung
37017               SEEG

In [51]:
print(
    "Vehicles registered in SEEG:",
    vehicle_quality[
        "Gemeinde_Zulassung"
    ].eq("SEEG").sum()
)

display(
    gemeinden[
        gemeinden[
            "Gemeinde_Zulassung"
        ]
        .str.contains(
            "SEE",
            case=False,
            na=False
        )
    ]
    .sort_values(
        "Gemeinde_Zulassung"
    )
)

Vehicles registered in SEEG: 204

,PLZ_Gemeinde,Gemeinde_Zulassung,Laengengrad_Gemeinde,Breitengrad_Gemeinde
973,15838,AM MELLENSEE,13.405535,52.156432
6081,83707,BAD WIESSEE,11.725573,47.712577
879,14778,BEETZSEE,12.537066,52.461693
880,14778,BEETZSEEHEIDE,12.629564,52.494945
6010,83233,BERNAU A.CHIEMSEE,12.374087,47.811654
...,...,...,...,...
1043,16835,VIELITZSEE,13.014725,52.932593
5041,67165,WALDSEE,8.441403,49.394745
7624,99631,WEISSENSEE,11.06815,51.195328
5915,82237,WOERTHSEE,11.202636,48.071942
1660,19246,ZARRENTIN AM SCHAALSEE,10.915544,53.551721

In [52]:
gemeinde_lookup = (
    gemeinden
    .drop_duplicates(
        "Gemeinde_Zulassung"
    )
    .reset_index(drop=True)
)

rows_before = len(
    vehicle_quality
)

vehicle_quality = vehicle_quality.merge(
    gemeinde_lookup,
    how="left",
    on="Gemeinde_Zulassung",
    validate="many_to_one"
)

print(
    "Rows before:",
    f"{rows_before:,}"
)

print(
    "Rows after:",
    f"{len(vehicle_quality):,}"
)

print(
    "Unique vehicle IDs:",
    vehicle_quality[
        "ID_Fahrzeug"
    ].is_unique
)

print(
    "Missing municipality coordinates:",
    vehicle_quality[
        [
            "Breitengrad_Gemeinde",
            "Laengengrad_Gemeinde"
        ]
    ].isna().any(axis=1).sum()
)

print(
    "Municipalities with missing coordinates:"
)

display(
    vehicle_quality.loc[
        vehicle_quality[
            [
                "Breitengrad_Gemeinde",
                "Laengengrad_Gemeinde"
            ]
        ].isna().any(axis=1),
        [
            "Gemeinde_Zulassung"
        ]
    ]
    .value_counts()
    .reset_index(
        name="Fahrzeuge"
    )
)

Rows before: 2,489,518
Rows after: 2,489,518
Unique vehicle IDs: True
Missing municipality coordinates: 204
Municipalities with missing coordinates:

  Gemeinde_Zulassung  Fahrzeuge
0               SEEG        204

## Final dataset

The final dataset has one row per vehicle. It contains the vehicle-level defect status required by the task, OEM production-plant information, installed component and Tier-1 provenance, registration information, and geodata. All dashboard KPIs are derived from this single dataset.

In [53]:
print(
    "vehicle_quality shape:",
    vehicle_quality.shape
)

print(
    "\nvehicle_quality columns:"
)

for column in vehicle_quality.columns:
    print(column)

vehicle_quality shape: (2489518, 65)

vehicle_quality columns:
ID_Fahrzeug
Produktionsdatum
Herstellernummer
Werksnummer
Fehlerhaft
Fehlerhaft_Datum
Fehlerhaft_Fahrleistung
ID_Karosserie
ID_Schaltung
ID_Sitze
ID_Motor
Tier1_Werksnummer_Schaltung
Fehlerhaft_Schaltung_Roh
Fehlerhaft_Schaltung_Einzelteil
Anzahl_Fehlerhafte_Einzelteile_Schaltung
Fehlerhaft_Schaltung
Tier1_Werksnummer_Karosserie
Fehlerhaft_Karosserie_Roh
Fehlerhaft_Karosserie_Einzelteil
Anzahl_Fehlerhafte_Einzelteile_Karosserie
Fehlerhaft_Karosserie
Tier1_Werksnummer_Sitze
Fehlerhaft_Sitze_Roh
Fehlerhaft_Sitze_Einzelteil
Anzahl_Fehlerhafte_Einzelteile_Sitze
Fehlerhaft_Sitze
Tier1_Werksnummer_Motor
Fehlerhaft_Motor_Roh
Fehlerhaft_Motor_Einzelteil
Anzahl_Fehlerhafte_Einzelteile_Motor
Fehlerhaft_Motor
Fehlerhaft_Fahrzeug_Roh
Anzahl_Fehlerhafte_Komponenten
Fehlerhaft_Gesamt
OEM
Fahrzeugtyp
Produktionsdatum_Origin_01011970
origin
PLZ_OEM
ORT_OEM
Werksnummer_OEM
Breitengrad_OEM
Laengengrad_OEM
Fehlerhaft_Komponenten
ORT_Tier1_Karosserie
PLZ_Tier1_Karosserie
Breitengrad_Tier1_Karosserie
Laengengrad_Tier1_Karosserie
ORT_Tier1_Schaltung
PLZ_Tier1_Schaltung
Breitengrad_Tier1_Schaltung
Laengengrad_Tier1_Schaltung
ORT_Tier1_Sitze
PLZ_Tier1_Sitze
Breitengrad_Tier1_Sitze
Laengengrad_Tier1_Sitze
ORT_Tier1_Motor
PLZ_Tier1_Motor
Breitengrad_Tier1_Motor
Laengengrad_Tier1_Motor
Gemeinde_Zulassung
Zulassungsdatum
PLZ_Gemeinde
Laengengrad_Gemeinde
Breitengrad_Gemeinde

In [54]:
vehicle_columns = [
    "ID_Fahrzeug",
    "OEM",
    "Fahrzeugtyp",
    "Produktionsdatum",
    "Herstellernummer",
    "Werksnummer_OEM",
    "ORT_OEM",
    "PLZ_OEM",
    "Breitengrad_OEM",
    "Laengengrad_OEM",
    "ID_Karosserie",
    "Tier1_Werksnummer_Karosserie",
    "ORT_Tier1_Karosserie",
    "PLZ_Tier1_Karosserie",
    "Breitengrad_Tier1_Karosserie",
    "Laengengrad_Tier1_Karosserie",
    "Fehlerhaft_Karosserie_Roh",
    "Fehlerhaft_Karosserie_Einzelteil",
    "Anzahl_Fehlerhafte_Einzelteile_Karosserie",
    "Fehlerhaft_Karosserie",
    "ID_Schaltung",
    "Tier1_Werksnummer_Schaltung",
    "ORT_Tier1_Schaltung",
    "PLZ_Tier1_Schaltung",
    "Breitengrad_Tier1_Schaltung",
    "Laengengrad_Tier1_Schaltung",
    "Fehlerhaft_Schaltung_Roh",
    "Fehlerhaft_Schaltung_Einzelteil",
    "Anzahl_Fehlerhafte_Einzelteile_Schaltung",
    "Fehlerhaft_Schaltung",
    "ID_Sitze",
    "Tier1_Werksnummer_Sitze",
    "ORT_Tier1_Sitze",
    "PLZ_Tier1_Sitze",
    "Breitengrad_Tier1_Sitze",
    "Laengengrad_Tier1_Sitze",
    "Fehlerhaft_Sitze_Roh",
    "Fehlerhaft_Sitze_Einzelteil",
    "Anzahl_Fehlerhafte_Einzelteile_Sitze",
    "Fehlerhaft_Sitze",
    "ID_Motor",
    "Tier1_Werksnummer_Motor",
    "ORT_Tier1_Motor",
    "PLZ_Tier1_Motor",
    "Breitengrad_Tier1_Motor",
    "Laengengrad_Tier1_Motor",
    "Fehlerhaft_Motor_Roh",
    "Fehlerhaft_Motor_Einzelteil",
    "Anzahl_Fehlerhafte_Einzelteile_Motor",
    "Fehlerhaft_Motor",
    "Fehlerhaft_Fahrzeug_Roh",
    "Anzahl_Fehlerhafte_Komponenten",
    "Fehlerhaft_Gesamt",
    "Fehlerhaft_Datum",
    "Fehlerhaft_Fahrleistung",
    "Gemeinde_Zulassung",
    "Zulassungsdatum",
    "PLZ_Gemeinde",
    "Breitengrad_Gemeinde",
    "Laengengrad_Gemeinde"
]

vehicle_quality = vehicle_quality[
    vehicle_columns
].copy()

print(
    "Final vehicle_quality shape:",
    vehicle_quality.shape
)

print(
    "Unique vehicle IDs:",
    vehicle_quality[
        "ID_Fahrzeug"
    ].is_unique
)

print(
    "Missing overall defect flags:",
    vehicle_quality[
        "Fehlerhaft_Gesamt"
    ].isna().sum()
)

print(
    "Missing OEM plants:",
    vehicle_quality[
        "Werksnummer_OEM"
    ].isna().sum()
)

print(
    "Missing registrations:",
    vehicle_quality[
        "Gemeinde_Zulassung"
    ].isna().sum()
)

print(
    "Missing municipality coordinates:",
    vehicle_quality[
        [
            "Breitengrad_Gemeinde",
            "Laengengrad_Gemeinde"
        ]
    ].isna().any(axis=1).sum()
)

tier1_location_columns = [
    f"ORT_Tier1_{role}"
    for role in roles
]

print(
    "Missing Tier-1 locations:",
    vehicle_quality[
        tier1_location_columns
    ].isna().sum().sum()
)

Final vehicle_quality shape: (2489518, 60)
Unique vehicle IDs: True
Missing overall defect flags: 0
Missing OEM plants: 0
Missing registrations: 0
Missing municipality coordinates: 204
Missing Tier-1 locations: 0

In [55]:
FINAL_FOLDER = Path("data/final")

FINAL_FOLDER.mkdir(
    parents=True,
    exist_ok=True
)

vehicle_path = (
    FINAL_FOLDER
    / "vehicle_quality.csv"
)

obsolete_path = (
    FINAL_FOLDER
    / "plant_quality.csv"
)

if obsolete_path.exists():
    obsolete_path.unlink()

vehicle_quality.to_csv(
    vehicle_path,
    index=False
)

print(
    "Final dataset:",
    vehicle_path
)

print(
    "Rows:",
    f"{len(vehicle_quality):,}"
)

print(
    "Columns:",
    len(vehicle_quality.columns)
)

print(
    "File exists:",
    vehicle_path.exists()
)

print(
    "Only one final CSV:",
    len(list(FINAL_FOLDER.glob("*.csv"))) == 1
)

Final dataset: data/final/vehicle_quality.csv
Rows: 2,489,518
Columns: 60
File exists: True
Only one final CSV: True