# Case Study: Plant Audit

**Course:** Introduction to Engineering Data Analytics  
**Semester:** SoSe 2026  
**Group number:** 44

# 1. Group Information

| Name | Matr.-Nr. |
|---|---|
| Group member 1 | `[TO BE ADDED]` |
| Group member 2 | `[TO BE ADDED]` |
| Group member 3 | `[TO BE ADDED]` |
| Group member 4 | `[TO BE ADDED]` |
| Group member 5 | `[TO BE ADDED]` |

# 2. Task

## 2.1 Case Study Task

You are an employee of a fictitious large automotive company that manufactures several types of vehicles under two automotive brands, “OEM1” and “OEM2”. 

The supply chain is composed of two instances: the parts suppliers and the components suppliers. The production plant installs the components in the respective vehicles. 

The head of the group’s quality assurance department asks you to **analyze in which production plant the next process audit should be carried out**. 
As a guide for your decision, you are to relate absolute and relative defect frequencies of the vehicles in the field to your production plants. 
For the analysis, use the failure data available to you for the vehicle types “Type11” and “Type21”. Select the production plant in which the next process audit is to take place. What additional insights does your analysis provide?

## 2.2 Defect Definition

Three related defect types are distinguished:

- **Raw vehicle defect:** the defect flag stored directly in the vehicle file.
- **Component defect:** a defect flag recorded for any component installed in the vehicle.
- **Part defect:** a defect flag recorded for any part contained in any installed component.

A vehicle is considered defective when at least one of the three defect types is active, including any combination of them.

## 2.3 Data Selection

The case study is limited to **OEM1 Vehicle Type 11** and **OEM2 Vehicle Type 21**. Their vehicle files and vehicle-component mapping files are the starting point. The related component, mapping, individual part, and plant files were identified from exploring the raw data and are listed below.

### Relevant files for Vehicle Type 11

| Category | Filename |
|---|---|
| Vehicle data | `Fahrzeuge_OEM1_Typ11.csv` |
| Vehicle–component mapping | `Bestandteile_Fahrzeuge_OEM1_Typ11.csv` |
| OEM plant locations | `OEM_Werke_2017-07-04_TrR.csv` |
| Tier 1 plant locations | `Tier1_Werke_2017-07-11_v1.2_TrR.csv` |
| Tier 2 plant locations | `Tier2_Werke_2017-07-11_v1.2_TrR.csv` |
| Body component | `Komponente_K4.csv` |
| Body component–part mapping | `Bestandteile_Komponente_K4.csv` |
| Body part | `Einzelteil_T30.csv` |
| Body part | `Einzelteil_T31.txt` |
| Body part | `Einzelteil_T32.csv` |
| Transmission component | `Komponente_K3AG1.csv` |
| Transmission component | `Komponente_K3SG1.csv` |
| Transmission component–part mapping | `Bestandteile_Komponente_K3AG1.csv` |
| Transmission component–part mapping | `Bestandteile_Komponente_K3SG1.csv` |
| Transmission part | `Einzelteil_T21.csv` |
| Transmission part | `Einzelteil_T22.txt` |
| Transmission part | `Einzelteil_T23.csv` |
| Transmission part | `Einzelteil_T24.txt` |
| Transmission part | `Einzelteil_T25.csv` |
| Seat component | `Komponente_K2LE1.txt` |
| Seat component | `Komponente_K2ST1.txt` |
| Seat component–part mapping | `Bestandteile_Komponente_K2LE1.csv` |
| Seat component–part mapping | `Bestandteile_Komponente_K2ST1.csv` |
| Seat part | `Einzelteil_T11.txt` |
| Seat part | `Einzelteil_T12.csv` |
| Seat part | `Einzelteil_T13.csv` |
| Seat part | `Einzelteil_T14.csv` |
| Seat part | `Einzelteil_T15.csv` |
| Engine component | `Komponente_K1BE1.csv` |
| Engine component | `Komponente_K1DI1.csv` |
| Engine component–part mapping | `Bestandteile_Komponente_K1BE1.csv` |
| Engine component–part mapping | `Bestandteile_Komponente_K1DI1.csv` |
| Engine part | `Einzelteil_T01.txt` |
| Engine part | `Einzelteil_T02.txt` |
| Engine part | `Einzelteil_T03.txt` |
| Engine part | `Einzelteil_T04.csv` |
| Engine part | `Einzelteil_T05.csv` |
| Engine part | `Einzelteil_T06.csv` |

### Relevant files for Vehicle Type 21

| Category | Filename |
|---|---|
| Vehicle data | `Fahrzeuge_OEM2_Typ21.csv` |
| Vehicle–component mapping | `Bestandteile_Fahrzeuge_OEM2_Typ21.csv` |
| OEM plant locations | `OEM_Werke_2017-07-04_TrR.csv` |
| Tier 1 plant locations | `Tier1_Werke_2017-07-11_v1.2_TrR.csv` |
| Tier 2 plant locations | `Tier2_Werke_2017-07-11_v1.2_TrR.csv` |
| Body component | `Komponente_K6.csv` |
| Body component–part mapping | `Bestandteile_Komponente_K6.csv` |
| Body part | `Einzelteil_T34.txt` |
| Body part | `Einzelteil_T35.txt` |
| Body part | `Einzelteil_T36.txt` |
| Body part | `Einzelteil_T37.csv` |
| Transmission component | `Komponente_K3AG2.txt` |
| Transmission component | `Komponente_K3SG2.csv` |
| Transmission component–part mapping | `Bestandteile_Komponente_K3AG2.csv` |
| Transmission component–part mapping | `Bestandteile_Komponente_K3SG2.csv` |
| Transmission part | `Einzelteil_T21.csv` |
| Transmission part | `Einzelteil_T22.txt` |
| Transmission part | `Einzelteil_T24.txt` |
| Transmission part | `Einzelteil_T26.csv` |
| Transmission part | `Einzelteil_T27.txt` |
| Seat component | `Komponente_K2LE2.txt` |
| Seat component | `Komponente_K2ST2.csv` |
| Seat component–part mapping | `Bestandteile_Komponente_K2LE2.csv` |
| Seat component–part mapping | `Bestandteile_Komponente_K2ST2.csv` |
| Seat part | `Einzelteil_T16.txt` |
| Seat part | `Einzelteil_T17.csv` |
| Seat part | `Einzelteil_T18.csv` |
| Seat part | `Einzelteil_T19.csv` |
| Seat part | `Einzelteil_T20.txt` |
| Engine component | `Komponente_K1BE2.csv` |
| Engine component | `Komponente_K1DI2.txt` |
| Engine component–part mapping | `Bestandteile_Komponente_K1BE2.csv` |
| Engine component–part mapping | `Bestandteile_Komponente_K1DI2.csv` |
| Engine part | `Einzelteil_T01.txt` |
| Engine part | `Einzelteil_T02.txt` |
| Engine part | `Einzelteil_T07.txt` |
| Engine part | `Einzelteil_T08.csv` |
| Engine part | `Einzelteil_T09.txt` |
| Engine part | `Einzelteil_T10.csv` |

# 3. Data Import and Initial Exploration

The files we need are already listed in Section 2. Before any cleaning, we:

1. define all paths relative to the project folder,
2. check that every required file is actually present,
3. open a few representative raw files to see typical formatting problems.

The goal is to understand the raw data as it currently exists, so the later required cleaning steps can be found out.

## 3.1 Imports

`pathlib` keeps file paths independent of the operating system. `pandas` is used for all tables. `csv`, `re`, and `mmap` are needed later for a few TXT files that do not use a normal delimiter or line break. `numpy` is used for everything numeric.

In [25]:
from pathlib import Path
import csv
import mmap
import re

import numpy as np
import pandas as pd

pd.set_option("display.max_columns", 30)
pd.set_option("display.max_colwidth", 110)
pd.set_option("display.max_rows", 100)

## 3.2 Project and Data Directories

All paths start from the current project folder.

The helper function `check_paths` is reused for every file group below. It shows whether a listed path exists without opening the file.

In [26]:
PROJECT_ROOT = Path.cwd().resolve()
DATA_DIRECTORY = PROJECT_ROOT / "data"

VEHICLE_DIRECTORY = DATA_DIRECTORY / "Fahrzeug"
COMPONENT_DIRECTORY = DATA_DIRECTORY / "Komponente"
PART_DIRECTORY = DATA_DIRECTORY / "Einzelteil"
GEODATA_DIRECTORY = DATA_DIRECTORY / "Geodaten"


def check_paths(path_dict, expect_file=True):
    """Show whether each listed path exists."""
    rows = []
    for name, path in path_dict.items():
        exists = path.is_file() if expect_file else path.is_dir()
        rows.append(
            {
                "File": name,
                "Relative Path": path.relative_to(PROJECT_ROOT).as_posix(),
                "Exists": "Yes" if exists else "No",
            }
        )
    return pd.DataFrame(rows)


data_directories = {
    "Vehicle data": VEHICLE_DIRECTORY,
    "Component data": COMPONENT_DIRECTORY,
    "Part data": PART_DIRECTORY,
    "Plant data": GEODATA_DIRECTORY,
}

check_paths(data_directories, expect_file=False)

             File    Relative Path Exists
0    Vehicle data    data/Fahrzeug    Yes
1  Component data  data/Komponente    Yes
2       Part data  data/Einzelteil    Yes
3      Plant data    data/Geodaten    Yes

All four data folders are available. The same overview is used for every file group below.

## 3.3 Vehicle Files

Each vehicle type has one vehicle file and one mapping file that links the vehicle to its four installed components.

In [27]:
vehicle_paths = {
    "Vehicle Type 11": VEHICLE_DIRECTORY / "Fahrzeuge_OEM1_Typ11.csv",
    "Vehicle Type 11 mapping": VEHICLE_DIRECTORY / "Bestandteile_Fahrzeuge_OEM1_Typ11.csv",
    "Vehicle Type 21": VEHICLE_DIRECTORY / "Fahrzeuge_OEM2_Typ21.csv",
    "Vehicle Type 21 mapping": VEHICLE_DIRECTORY / "Bestandteile_Fahrzeuge_OEM2_Typ21.csv",
}

check_paths(vehicle_paths)

,File,Relative Path,Exists
0,Vehicle Type 11,data/Fahrzeug/Fahrzeuge_OEM1_Typ11.csv,Yes
1,Vehicle Type 11 mapping,data/Fahrzeug/Bestandteile_Fahrzeuge_OEM1_Typ11.csv,Yes
2,Vehicle Type 21,data/Fahrzeug/Fahrzeuge_OEM2_Typ21.csv,Yes
3,Vehicle Type 21 mapping,data/Fahrzeug/Bestandteile_Fahrzeuge_OEM2_Typ21.csv,Yes

## 3.4 Component Files

For each component we need two files: the production file (quality and plant of the component) and the mapping file (which parts are installed in it).

In [28]:
component_paths = {
    "K4 production": COMPONENT_DIRECTORY / "Komponente_K4.csv",
    "K4 mapping": COMPONENT_DIRECTORY / "Bestandteile_Komponente_K4.csv",
    "K3AG1 production": COMPONENT_DIRECTORY / "Komponente_K3AG1.csv",
    "K3AG1 mapping": COMPONENT_DIRECTORY / "Bestandteile_Komponente_K3AG1.csv",
    "K3SG1 production": COMPONENT_DIRECTORY / "Komponente_K3SG1.csv",
    "K3SG1 mapping": COMPONENT_DIRECTORY / "Bestandteile_Komponente_K3SG1.csv",
    "K2LE1 production": COMPONENT_DIRECTORY / "Komponente_K2LE1.txt",
    "K2LE1 mapping": COMPONENT_DIRECTORY / "Bestandteile_Komponente_K2LE1.csv",
    "K2ST1 production": COMPONENT_DIRECTORY / "Komponente_K2ST1.txt",
    "K2ST1 mapping": COMPONENT_DIRECTORY / "Bestandteile_Komponente_K2ST1.csv",
    "K1BE1 production": COMPONENT_DIRECTORY / "Komponente_K1BE1.csv",
    "K1BE1 mapping": COMPONENT_DIRECTORY / "Bestandteile_Komponente_K1BE1.csv",
    "K1DI1 production": COMPONENT_DIRECTORY / "Komponente_K1DI1.csv",
    "K1DI1 mapping": COMPONENT_DIRECTORY / "Bestandteile_Komponente_K1DI1.csv",
    "K6 production": COMPONENT_DIRECTORY / "Komponente_K6.csv",
    "K6 mapping": COMPONENT_DIRECTORY / "Bestandteile_Komponente_K6.csv",
    "K3AG2 production": COMPONENT_DIRECTORY / "Komponente_K3AG2.txt",
    "K3AG2 mapping": COMPONENT_DIRECTORY / "Bestandteile_Komponente_K3AG2.csv",
    "K3SG2 production": COMPONENT_DIRECTORY / "Komponente_K3SG2.csv",
    "K3SG2 mapping": COMPONENT_DIRECTORY / "Bestandteile_Komponente_K3SG2.csv",
    "K2LE2 production": COMPONENT_DIRECTORY / "Komponente_K2LE2.txt",
    "K2LE2 mapping": COMPONENT_DIRECTORY / "Bestandteile_Komponente_K2LE2.csv",
    "K2ST2 production": COMPONENT_DIRECTORY / "Komponente_K2ST2.csv",
    "K2ST2 mapping": COMPONENT_DIRECTORY / "Bestandteile_Komponente_K2ST2.csv",
    "K1BE2 production": COMPONENT_DIRECTORY / "Komponente_K1BE2.csv",
    "K1BE2 mapping": COMPONENT_DIRECTORY / "Bestandteile_Komponente_K1BE2.csv",
    "K1DI2 production": COMPONENT_DIRECTORY / "Komponente_K1DI2.txt",
    "K1DI2 mapping": COMPONENT_DIRECTORY / "Bestandteile_Komponente_K1DI2.csv",
}

check_paths(component_paths)

                File                                      Relative Path Exists
0      K4 production                  data/Komponente/Komponente_K4.csv    Yes
1         K4 mapping     data/Komponente/Bestandteile_Komponente_K4.csv    Yes
2   K3AG1 production               data/Komponente/Komponente_K3AG1.csv    Yes
3      K3AG1 mapping  data/Komponente/Bestandteile_Komponente_K3AG1.csv    Yes
4   K3SG1 production               data/Komponente/Komponente_K3SG1.csv    Yes
5      K3SG1 mapping  data/Komponente/Bestandteile_Komponente_K3SG1.csv    Yes
6   K2LE1 production               data/Komponente/Komponente_K2LE1.txt    Yes
7      K2LE1 mapping  data/Komponente/Bestandteile_Komponente_K2LE1.csv    Yes
8   K2ST1 production               data/Komponente/Komponente_K2ST1.txt    Yes
9      K2ST1 mapping  data/Komponente/Bestandteile_Komponente_K2ST1.csv    Yes
10  K1BE1 production               data/Komponente/Komponente_K1BE1.csv    Yes
11     K1BE1 mapping  data/Komponente/Bestandteile_Komponente_K1BE1.csv    Yes
12  K1DI1 production               data/Komponente/Komponente_K1DI1.csv    Yes
13     K1DI1 mapping  data/Komponente/Bestandteile_Komponente_K1DI1.csv    Yes
14     K6 production                  data/Komponente/Komponente_K6.csv    Yes
15        K6 mapping     data/Komponente/Bestandteile_Komponente_K6.csv    Yes
16  K3AG2 production               data/Komponente/Komponente_K3AG2.txt    Yes
17     K3AG2 mapping  data/Komponente/Bestandteile_Komponente_K3AG2.csv    Yes
18  K3SG2 production               data/Komponente/Komponente_K3SG2.csv    Yes
19     K3SG2 mapping  data/Komponente/Bestandteile_Komponente_K3SG2.csv    Yes
20  K2LE2 production               data/Komponente/Komponente_K2LE2.txt    Yes
21     K2LE2 mapping  data/Komponente/Bestandteile_Komponente_K2LE2.csv    Yes
22  K2ST2 production               data/Komponente/Komponente_K2ST2.csv    Yes
23     K2ST2 mapping  data/Komponente/Bestandteile_Komponente_K2ST2.csv    Yes
24  K1BE2 production               data/Komponente/Komponente_K1BE2.csv    Yes
25     K1BE2 mapping  data/Komponente/Bestandteile_Komponente_K1BE2.csv    Yes
26  K1DI2 production               data/Komponente/Komponente_K1DI2.txt    Yes
27     K1DI2 mapping  data/Komponente/Bestandteile_Komponente_K1DI2.csv    Yes

## 3.5 Part Files

Each part type is listed only once, even if both vehicle types use it. That avoids reading the same file twice later.

In [29]:
part_paths = {
    "T01": PART_DIRECTORY / "Einzelteil_T01.txt",
    "T02": PART_DIRECTORY / "Einzelteil_T02.txt",
    "T03": PART_DIRECTORY / "Einzelteil_T03.txt",
    "T04": PART_DIRECTORY / "Einzelteil_T04.csv",
    "T05": PART_DIRECTORY / "Einzelteil_T05.csv",
    "T06": PART_DIRECTORY / "Einzelteil_T06.csv",
    "T07": PART_DIRECTORY / "Einzelteil_T07.txt",
    "T08": PART_DIRECTORY / "Einzelteil_T08.csv",
    "T09": PART_DIRECTORY / "Einzelteil_T09.txt",
    "T10": PART_DIRECTORY / "Einzelteil_T10.csv",
    "T11": PART_DIRECTORY / "Einzelteil_T11.txt",
    "T12": PART_DIRECTORY / "Einzelteil_T12.csv",
    "T13": PART_DIRECTORY / "Einzelteil_T13.csv",
    "T14": PART_DIRECTORY / "Einzelteil_T14.csv",
    "T15": PART_DIRECTORY / "Einzelteil_T15.csv",
    "T16": PART_DIRECTORY / "Einzelteil_T16.txt",
    "T17": PART_DIRECTORY / "Einzelteil_T17.csv",
    "T18": PART_DIRECTORY / "Einzelteil_T18.csv",
    "T19": PART_DIRECTORY / "Einzelteil_T19.csv",
    "T20": PART_DIRECTORY / "Einzelteil_T20.txt",
    "T21": PART_DIRECTORY / "Einzelteil_T21.csv",
    "T22": PART_DIRECTORY / "Einzelteil_T22.txt",
    "T23": PART_DIRECTORY / "Einzelteil_T23.csv",
    "T24": PART_DIRECTORY / "Einzelteil_T24.txt",
    "T25": PART_DIRECTORY / "Einzelteil_T25.csv",
    "T26": PART_DIRECTORY / "Einzelteil_T26.csv",
    "T27": PART_DIRECTORY / "Einzelteil_T27.txt",
    "T30": PART_DIRECTORY / "Einzelteil_T30.csv",
    "T31": PART_DIRECTORY / "Einzelteil_T31.txt",
    "T32": PART_DIRECTORY / "Einzelteil_T32.csv",
    "T34": PART_DIRECTORY / "Einzelteil_T34.txt",
    "T35": PART_DIRECTORY / "Einzelteil_T35.txt",
    "T36": PART_DIRECTORY / "Einzelteil_T36.txt",
    "T37": PART_DIRECTORY / "Einzelteil_T37.csv",
}

check_paths(part_paths)

   File                       Relative Path Exists
0   T01  data/Einzelteil/Einzelteil_T01.txt    Yes
1   T02  data/Einzelteil/Einzelteil_T02.txt    Yes
2   T03  data/Einzelteil/Einzelteil_T03.txt    Yes
3   T04  data/Einzelteil/Einzelteil_T04.csv    Yes
4   T05  data/Einzelteil/Einzelteil_T05.csv    Yes
5   T06  data/Einzelteil/Einzelteil_T06.csv    Yes
6   T07  data/Einzelteil/Einzelteil_T07.txt    Yes
7   T08  data/Einzelteil/Einzelteil_T08.csv    Yes
8   T09  data/Einzelteil/Einzelteil_T09.txt    Yes
9   T10  data/Einzelteil/Einzelteil_T10.csv    Yes
10  T11  data/Einzelteil/Einzelteil_T11.txt    Yes
11  T12  data/Einzelteil/Einzelteil_T12.csv    Yes
12  T13  data/Einzelteil/Einzelteil_T13.csv    Yes
13  T14  data/Einzelteil/Einzelteil_T14.csv    Yes
14  T15  data/Einzelteil/Einzelteil_T15.csv    Yes
15  T16  data/Einzelteil/Einzelteil_T16.txt    Yes
16  T17  data/Einzelteil/Einzelteil_T17.csv    Yes
17  T18  data/Einzelteil/Einzelteil_T18.csv    Yes
18  T19  data/Einzelteil/Einzelteil_T19.csv    Yes
19  T20  data/Einzelteil/Einzelteil_T20.txt    Yes
20  T21  data/Einzelteil/Einzelteil_T21.csv    Yes
21  T22  data/Einzelteil/Einzelteil_T22.txt    Yes
22  T23  data/Einzelteil/Einzelteil_T23.csv    Yes
23  T24  data/Einzelteil/Einzelteil_T24.txt    Yes
24  T25  data/Einzelteil/Einzelteil_T25.csv    Yes
25  T26  data/Einzelteil/Einzelteil_T26.csv    Yes
26  T27  data/Einzelteil/Einzelteil_T27.txt    Yes
27  T30  data/Einzelteil/Einzelteil_T30.csv    Yes
28  T31  data/Einzelteil/Einzelteil_T31.txt    Yes
29  T32  data/Einzelteil/Einzelteil_T32.csv    Yes
30  T34  data/Einzelteil/Einzelteil_T34.txt    Yes
31  T35  data/Einzelteil/Einzelteil_T35.txt    Yes
32  T36  data/Einzelteil/Einzelteil_T36.txt    Yes
33  T37  data/Einzelteil/Einzelteil_T37.csv    Yes

## 3.6 Plant Files

The three plant files connect manufacturer and plant numbers to a location. OEM plants assemble vehicles, Tier 1 plants produce components, and Tier 2 plants produce parts.

In [30]:
plant_paths = {
    "OEM plants": GEODATA_DIRECTORY / "OEM_Werke_2017-07-04_TrR.csv",
    "Tier 1 plants": GEODATA_DIRECTORY / "Tier1_Werke_2017-07-11_v1.2_TrR.csv",
    "Tier 2 plants": GEODATA_DIRECTORY / "Tier2_Werke_2017-07-11_v1.2_TrR.csv",
}

check_paths(plant_paths)

            File                                      Relative Path Exists
0     OEM plants         data/Geodaten/OEM_Werke_2017-07-04_TrR.csv    Yes
1  Tier 1 plants  data/Geodaten/Tier1_Werke_2017-07-11_v1.2_TrR.csv    Yes
2  Tier 2 plants  data/Geodaten/Tier2_Werke_2017-07-11_v1.2_TrR.csv    Yes

## 3.7 Final Path Check

If any listed file is missing, the notebook stops here.

In [31]:
# Combine every listed source so a missing file stops the notebook immediately.
all_relevant_paths = {
    **vehicle_paths,
    **component_paths,
    **part_paths,
    **plant_paths,
}

missing_files = [
    path.relative_to(PROJECT_ROOT).as_posix()
    for path in all_relevant_paths.values()
    if not path.is_file()
]

if missing_files:
    raise FileNotFoundError(f"Missing files: {missing_files}")

print(f"All {len(all_relevant_paths)} required files are available.")

All 69 required files are available.

## 3.8 Selected Raw File Previews

The examples below show an overview of common errors in the files that need to be cleaned later.

### 3.8.1 Vehicle Type 11

Five rows of the Type 11 vehicle file, read with its comma separator.

In [32]:
vehicle_type_11_raw = pd.read_csv(
    vehicle_paths["Vehicle Type 11"],
    sep=",",
    encoding="cp1252",
    nrows=5,
)
vehicle_type_11_raw.head()

,Unnamed: 0,X1,ID_Fahrzeug,Produktionsdatum,Herstellernummer,Werksnummer,Fehlerhaft,Fehlerhaft_Datum,Fehlerhaft_Fahrleistung
0,1,1,11-1-11-1,2008-11-18,1,11,0,NaN,0
1,2,2,11-1-11-2,2008-11-18,1,11,0,NaN,0
2,3,3,11-1-11-3,2008-11-19,1,11,0,NaN,0
3,4,4,11-1-11-4,2008-11-19,1,11,0,NaN,0
4,5,5,11-1-11-5,2008-11-19,1,11,0,NaN,0

The first two columns are an unnamed column and `X1`. They look like duplicate row counters and will need to be removed.

### 3.8.2 Vehicle Type 21

The Type 21 vehicle file is read in the same way so that both vehicle types can be compared.

In [33]:
vehicle_type_21_raw = pd.read_csv(
    vehicle_paths["Vehicle Type 21"],
    sep=",",
    encoding="cp1252",
    nrows=5,
)
vehicle_type_21_raw.head()

,Unnamed: 0,X1,ID_Fahrzeug,Herstellernummer,Werksnummer,Fehlerhaft,Fehlerhaft_Datum,Fehlerhaft_Fahrleistung,Produktionsdatum_Origin_01011970,origin
0,1,1,21-2-21-1,2,21,0,NaN,0,14202,01-01-1970
1,2,2,21-2-21-2,2,21,0,NaN,0,14202,01-01-1970
2,3,3,21-2-21-3,2,21,0,NaN,0,15353,01-01-1970
3,4,4,21-2-21-4,2,21,0,NaN,0,14203,01-01-1970
4,5,5,21-2-21-5,2,21,0,NaN,0,14203,01-01-1970

This file also contains the duplicate row counter column. In addition, the production date is not stored like the Type 11 date. It is split into `Produktionsdatum_Origin_01011970` and `origin`. These two fields have to be combined into one standard production-date column later.

### 3.8.3 Vehicle-Component Mapping

The Type 11 mapping file is an example of a table with a semicolon seperator.

In [34]:
vehicle_component_mapping_raw = pd.read_csv(
    vehicle_paths["Vehicle Type 11 mapping"],
    sep=";",
    encoding="cp1252",
    nrows=5,
)
vehicle_component_mapping_raw.head()

,Unnamed: 0,ID_Karosserie,ID_Schaltung,ID_Sitze,ID_Motor,ID_Fahrzeug
0,1,K4-112-1121-3,K3SG1-105-1051-32,K2LE1-109-1091-2,K1BE1-101-1011-7,11-1-11-1
1,2,K4-112-1121-4,K3SG1-105-1051-141,K2ST1-109-1092-5,K1BE1-101-1011-12,11-1-11-2
2,3,K4-112-1121-7,K3SG1-105-1051-106,K2ST1-109-1092-57,K1BE1-101-1011-38,11-1-11-3
3,4,K4-112-1121-9,K3SG1-105-1051-21,K2ST1-109-1092-91,K1BE1-101-1011-97,11-1-11-4
4,5,K4-112-1121-11,K3SG1-105-1051-59,K2ST1-109-1092-4,K1BE1-101-1011-65,11-1-11-5

Again there is an unnamed duplicate row counter column that needs to be removed.

### 3.8.4 Component K4

Component K4 is an example of a file with duplicated column groups.

In [35]:
component_k4_raw = pd.read_csv(
    component_paths["K4 production"],
    sep=";",
    encoding="cp1252",
    nrows=5,
)
component_k4_raw.head()

,Unnamed: 0,X1,ID_Karosserie.x,Produktionsdatum.x,Herstellernummer.x,Werksnummer.x,Fehlerhaft.x,Fehlerhaft_Datum.x,Fehlerhaft_Fahrleistung.x,ID_Karosserie.y,Produktionsdatum.y,Herstellernummer.y,Werksnummer.y,Fehlerhaft.y,Fehlerhaft_Datum.y,Fehlerhaft_Fahrleistung.y
0,1,1,K4-112-1121-3,2008-11-12,112,1121,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,2,K4-112-1121-4,2008-11-12,112,1121,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,3,K4-112-1121-7,2008-11-12,112,1121,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,4,K4-112-1121-9,2008-11-12,112,1121,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,5,K4-112-1121-11,2008-11-12,112,1121,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Many attributes appear once with the suffix `.x` and again with `.y`. In the displayed rows the `.y` columns appear to be empty. During cleaning, both versions have to be compared first before the are merged into a single column. Again there are an unnamed column and `X1` that need to be removed.

### 3.8.5 Part T04

Part T04 represents a semicolon-separated part file with a 1970s origin-based date.

In [36]:
part_t04_raw = pd.read_csv(
    part_paths["T04"],
    sep=";",
    encoding="cp1252",
    nrows=5,
)
part_t04_raw.head()

,Unnamed: 0,X1,ID_T04,Herstellernummer,Werksnummer,Fehlerhaft,Fehlerhaft_Datum,Fehlerhaft_Fahrleistung,Produktionsdatum_Origin_01011970,origin
0,1,1,4-204-2043-113,204,2043,0,NaN,0,14190,01-01-1970
1,2,2,4-202-2023-18,202,2023,0,NaN,0,14190,01-01-1970
2,3,3,4-204-2043-98,204,2043,0,NaN,0,14190,01-01-1970
3,4,4,4-202-2023-51,202,2023,0,NaN,0,14190,01-01-1970
4,5,5,4-204-2043-169,204,2043,0,NaN,0,14190,01-01-1970

The file has the same duplicate row counter columns as the other files. Its production date is based on a 1970s origin date and will have to be converted to a regular date-forma.

### 3.8.6 Tier 2 Plant Data

The Tier 2 plant file is read with its semicolon separator.

In [37]:
tier_2_plants_raw = pd.read_csv(
    plant_paths["Tier 2 plants"],
    sep=";",
    encoding="cp1252",
    nrows=5,
)
tier_2_plants_raw.head()

,PLZ,ORT,Werk,Breitengrad,L„ngengrad,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17
0,90762,FUERTH,2011,49.477859,10.988665,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,96047,BAMBERG,2012,49.866670,10.866670,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,86150,AUGSBURG,2021,48.369099,10.893711,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,69115,HEIDELBERG,2022,49.400270,8.677846,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,63739,ASCHAFFENBURG,2023,49.400270,8.677846,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

There are repeated semicolons at the end of each row that create several completely empty columns that have to be removed. There is also inconsistent whitespace in the column names (`ORT `).
### 3.8.7 Component K2LE1

Some TXT files do not use normal line breaks. Only a short excerpt is read here so that the raw separators can be inspected without loading the whole file.

In [38]:
def show_raw_excerpt(file_path, byte_limit=500):
    """Read a short raw excerpt and make control characters visible."""
    with file_path.open("rb") as raw_file:
        raw_text = raw_file.read(byte_limit).decode("cp1252", errors="replace")

    # Replace invisible control characters with readable labels.
    raw_text = raw_text.replace("\x08", "<BACKSPACE>")
    raw_text = raw_text.replace("\x0b", "<VERTICAL_TAB>")
    raw_text = raw_text.replace("\r", "<CR>")
    raw_text = raw_text.replace("\n", "<LF>")
    return raw_text


show_raw_excerpt(component_paths["K2LE1 production"])

'"X1"II"ID_Sitze.x"II"Produktionsdatum.x"II"Herstellernummer.x"II"Werksnummer.x"II"Fehlerhaft.x"II"Fehlerhaft_Datum.x"II"Fehlerhaft_Fahrleistung.x"II"ID_Sitze.y"II"Produktionsdatum.y"II"Herstellernummer.y"II"Werksnummer.y"II"Fehlerhaft.y"II"Fehlerhaft_Datum.y"II"Fehlerhaft_Fahrleistung.y"<VERTICAL_TAB>"1"II1II"K2LE1-109-1091-2"II2008-11-12II"109"II1091II1II2010-10-18II37080IINAIINAIINAIINAIINAIINAIINA<VERTICAL_TAB>"2"II2II"K2LE1-109-1091-1"II2008-11-12II"109"II1091II0IINAII0IINAIINAIINAIINAIINAIINAIINA<VERTICAL_TAB>"3"II3II"K2LE1-109-'

Fields are separated by `II`, while individual records e.g. rows are separated by `<VERTICAL_TAB>`. A normal import would therefore not produce the correct columns and rows. This file needs a dedicated import step.

### 3.8.8 Component K3AG2

The next component file uses another raw format.

In [39]:
show_raw_excerpt(component_paths["K3AG2 production"])

'"X1"\\"ID_Schaltung"\\"Herstellernummer"\\"Werksnummer"\\"Fehlerhaft"\\"Fehlerhaft_Datum"\\"Fehlerhaft_Fahrleistung"\\"Produktionsdatum_Origin_01011970"\\"origin"<CR>"1"\\1\\"K3AG2-108-1082-9"\\"108"\\"1082"\\0\\NA\\0\\14196\\"01-01-1970"<CR>"2"\\2\\"K3AG2-108-1082-11"\\"108"\\"1082"\\1\\2010-03-02\\31859\\14196\\"01-01-1970"<CR>"3"\\3\\"K3AG2-108-1082-14"\\"108"\\"1082"\\0\\NA\\0\\14196\\"01-01-1970"<CR>"4"\\4\\"K3AG2-108-1082-3"\\"108"\\"1082"\\0\\NA\\0\\14196\\"01-01-1970"<CR>"5"\\5\\"K3AG2-108-1082-5"\\"108"\\"1082"\\0\\NA\\0\\14196\\"01-01-1970"<CR>"6"\\6\\"K3AG'

Backslashes (`\\`) separate the fields and carriage returns (`<CR>`) separate the records. This file therefore needs a dedicated import step.

### 3.8.9 Part T01

Part T01 shows a multi-character separator.

In [40]:
show_raw_excerpt(part_paths["T01"])

'"X1" | | "ID_T01.x" | | "Produktionsdatum.x" | | "Herstellernummer.x" | | "Werksnummer.x" | | "Fehlerhaft.x" | | "Fehlerhaft_Datum.x" | | "Fehlerhaft_Fahrleistung.x" | | "ID_T01.y" | | "Produktionsdatum.y" | | "Herstellernummer.y" | | "Werksnummer.y" | | "Fehlerhaft.y" | | "Fehlerhaft_Datum.y" | | "Fehlerhaft_Fahrleistung.y" | | "ID_T01" | | "Produktionsdatum" | | "Herstellernummer" | | "Werksnummer" | | "Fehlerhaft" | | "Fehlerhaft_Datum" | | "Fehlerhaft_Fahrleistung" "1" | | 660 | | "1-201-201'

The fields are separated by the pattern `| |` instead of a normal delimiter. This file needs a dedicated import step.

### 3.8.10 Part T31

Part T31 is the last example of a non-standard TXT structure.

In [41]:
show_raw_excerpt(part_paths["T31"])

'"X1"  "ID_T31"  "Herstellernummer"  "Werksnummer"  "Fehlerhaft"  "Fehlerhaft_Datum"  "Fehlerhaft_Fahrleistung"  "Produktionsdatum_Origin_01011970"  "origin"<BACKSPACE>"1"  1  "31-217-2172-53"  "217"  "2172"  0  NA  0  14190  "01-01-1970"<BACKSPACE>"2"  2  "31-217-2172-139"  "217"  "2172"  0  NA  0  14190  "01-01-1970"<BACKSPACE>"3"  3  "31-216-2161-15"  "216"  "2161"  0  NA  0  14190  "01-01-1970"<BACKSPACE>"4"  4  "31-216-2161-93"  "216"  "2161"  0  NA  0  14190  "01-01-1970"<BACKSPACE>"5"  5  "31-216-2161-67"  "216"  "2161"  0  NA  0  14190  '

Spaces separate the fields and `<BACKSPACE>` separates the records. This file also needs a dedicated import step.

## 3.9 Summary of Observed Data Issues

### 3.9.1 File Import Problems

| Problem | Affected Files | Required Cleaning Step |
|---|---|---|
| CSV files use different separators | **Comma-separated:** `Fahrzeuge_OEM1_Typ11.csv`, `Fahrzeuge_OEM2_Typ21.csv`, `Komponente_K1BE1.csv`, `Komponente_K1DI1.csv`, `Komponente_K3AG1.csv`, `Komponente_K3SG1.csv`, `Komponente_K3SG2.csv`, `Einzelteil_T05.csv`, `T06.csv`, `T08.csv`, `T19.csv`, `T25.csv`, `T30.csv`, `T37.csv`<br><br>**Semicolon-separated:** all other relevant CSV files | Load each file with the correct separator. Then check whether the columns were imported correctly. |
| Component TXT files use special separators | `Komponente_K2LE1.txt`: fields `II`, rows `\x0b`<br>`Komponente_K3AG2.txt`: fields `\`, rows `\r`<br>`Komponente_K2LE2.txt`: fields `\`, rows `\r`<br>`Komponente_K2ST1.txt`: fields `\|`, rows `\r`<br>`Komponente_K1DI2.txt`: fields `\`, rows `\t` | Store the field and row separator for each file and use the special TXT reader to import it. |
| Part TXT files use special row separators | `T02`: fields = 2+ spaces, rows = `\t`<br>`T03`: fields = `\|`, rows = `\x0b`<br>`T09`: fields = `\`, rows = `\x0b`<br>`T11`: fields = `\t`, rows = `\x0c`<br>`T16`: fields = ` \| \| `, rows = `\t`<br>`T24`: fields = 2+ spaces, rows = `\x0c`<br>`T27`: fields = ` \| \| `, rows = `\x07`<br>`T31`: fields = 2+ spaces, rows = `\x08` | First split the file with the row separator. Then split each row with the field separator. |
| Some part TXT files have no row separator | `T01`: fields = ` \| \| `<br>`T07`: fields = `\t`<br>`T20`: fields = ` \| \| `<br>`T22`: fields = `\t`<br>`T34`: fields = ` \| \| `<br>`T35`: fields = `\`<br>`T36`: fields = 2+ spaces | Find the start of each new row using the quoted row number and split the file at these positions. |
| TXT rows can have the wrong number of fields | All component and part TXT files with special separators | Compare the number of values in every row with the number of header columns. Stop the import if they do not match. |
| Source files use a different text encoding | All imported source files | Read the files with `cp1252` encoding and replace characters that cannot be decoded. |

### 3.9.2 Structural and Content Cleaning

| Problem | Affected Files | Required Cleaning Step |
|---|---|---|
| Unnecessary export columns | Vehicle, component, assignment, and part files; columns such as `X`, `X1`, `_Zeilenindex`, empty column names, or `Unnamed:*` | Remove columns with these names after importing the file. |
| Extra spaces and different missing-value markers | All imported files | Remove spaces around column names and text values. Replace `""`, `NA`, `N/A`, `NULL`, and `null` with `pd.NA`. |
| The same data is stored in `.x` and `.y` columns | **Components:** `K4`, `K3AG1`, `K3SG1`, `K2LE1`, `K1DI1`<br><br>**Parts:** `T01`, `T02`, `T05`, `T09`, `T12`, `T15`, `T16`, `T17`, `T22`, `T23`, `T24`, `T30`, `T32`, `T35` | Combine the normal, `.x`, and `.y` versions into one column. |
| Production dates are stored differently | `Fahrzeuge_OEM2_Typ21.csv`<br><br>Components `K1BE1`, `K6`, `K3AG2`, `K3SG2`, `K2LE2`, `K2ST2`, `K1BE2`, `K1DI2`<br><br>Parts `T03`, `T04`, `T06`, `T07`, `T08`, `T10`, `T11`, `T13`, `T14`, `T18`, `T19`, `T20`, `T21`, `T25`, `T26`, `T27`, `T31`, `T34`, `T36`, `T37` | Convert normal date values directly. For origin-based dates, add the number of days to the date in `origin`. Save the result as `YYYY-MM-DD`. |
| Defect dates use different formats | Vehicle, component, and part files containing `Fehlerhaft_Datum` | Convert the values to dates and save them as `YYYY-MM-DD`. |
| IDs and keys may be read as numbers | All ID, manufacturer, plant, and postal-code columns | Read the columns as text. |
| Manufacturer or plant numbers do not match the object ID | Vehicle, component, and part files with IDs in the format `Type-Manufacturer-Plant-…` | Get the manufacturer and plant number from the object ID. Use these values when the separate columns are missing or different. |
| Plant files contain empty or inconsistent values | OEM, Tier-1, and Tier-2 plant files | Remove completely empty columns and rows without plant, city, or postal code. Fix the longitude column name, convert coordinates to numbers, and fill postal codes to five digits. |
| OEM plant numbers have a different format | OEM plant data | Remove the `O` at the start of values such as `O11`. This creates the same plant-number format as in the vehicle data. |
| Vehicle-component assignments are stored in several columns | `Bestandteile_Fahrzeuge_OEM1_Typ11.csv`, `Bestandteile_Fahrzeuge_OEM2_Typ21.csv` | Change the four component columns into a long table with one vehicle-component pair per row. Add the component role and component type. |
| Part ID columns use different names | Component-part assignment files; for example `ID_T1` and `ID_T01` | Check both possible column names and rename the selected column to `ID_Einzelteil`. |
| Different components require different part types | All component-part assignment files | Use the configured list of part types for each component type. Only these columns are added to the component-part table. |
| Some component IDs occur more than once | Component master files | Group rows with the same component ID. Keep the highest defect value and the first value from the other columns. Record the number of duplicate rows. |
| Some part IDs occur more than once | Part master files | Group rows with the same part ID. Keep the highest defect value and the first value from the other columns. Record the number of duplicate rows. |
| Defect and mileage columns have the wrong data type | Vehicle, component, and part files | Convert `Fehlerhaft` to a nullable integer and `Fehlerhaft_Fahrleistung` to a number. |
| Plant information is stored in separate files | Vehicle, component, and part data | Add OEM plant data to vehicles, Tier-1 plant data to components, and Tier-2 plant data to parts using `Werksnummer`. |

### 3.9.3 Data Quality and Validation

| Problem | Affected Files | Required Cleaning or Validation Step |
|---|---|---|
| Missing defect values must stay unknown | Vehicle, component, and part data | Use three defect states: `1` for defective, `0` for not defective, and `NA` for unknown. |
| Component and part defects also affect the vehicle | Cleaned vehicle, component, part, and assignment data | Mark a vehicle as defective if the vehicle itself, one of its components, or one of its parts is defective. Keep the result unknown if there is no confirmed defect but some information is missing. |
| Vehicle, component, and part IDs should be unique | Cleaned vehicle, component, and part tables | Check that vehicle, component, and part IDs do not occur more than once after cleaning. |
| Each vehicle should have four components | Cleaned vehicle-component assignments | Count the component assignments for each vehicle and check that the result is always four. |
| Table joins must have the expected structure | Plant joins and the final vehicle-component-part trace | Use `validate` during merges to check whether the join is `many-to-one`, `one-to-one`, or `one-to-many`. |
| The final tables must have the expected size | `vehicle_quality_clean` and `quality_trace_clean` | Check the expected number of Type 11 vehicles, Type 21 vehicles, and rows in the detailed trace table. |
| Important IDs must not be missing in the final trace | `quality_trace_clean` | Check that `ID_Fahrzeug`, `ID_Komponente`, and `ID_Einzelteil` contain no missing values. |
| Some cleaning changes should be recorded | `.x`/`.y` conflicts, corrected manufacturer and plant numbers, duplicate component rows, and duplicate part rows | Save the source file, the type of cleaning, and the number of affected rows in `cleaning_log.csv`. |

# 4. Data Cleaning

This section reads every relevant source file into a pandas DataFrame.

The work follows the data from vehicle down to part:

1. clean the plant master data,
2. clean the vehicle data,
3. reshape the vehicle-component mappings,
4. clean and combine the component files,
5. reshape the component-part mappings,
6. clean and combine the part files,
7. build the detailed trace table,
8. build the vehicle-level quality table.

## 4.1 Cleaning Configuration

The dictionaries below record information that is already known from the data exploration:

- which component belongs to which role (body, transmission, seats, engine),
- which part types belong to which component,
- which files use a comma instead of a semicolon,
- which TXT files need a special field and record separator.

The output folder `data/cleaned` is created here.

In [42]:
CLEAN_DIRECTORY = DATA_DIRECTORY / "cleaned"
CLEAN_DIRECTORY.mkdir(exist_ok=True)

vehicle_data_paths = {
    "Type 11": vehicle_paths["Vehicle Type 11"],
    "Type 21": vehicle_paths["Vehicle Type 21"],
}

vehicle_mapping_paths = {
    "Type 11": vehicle_paths["Vehicle Type 11 mapping"],
    "Type 21": vehicle_paths["Vehicle Type 21 mapping"],
}

component_configuration = {
    "K4": "Karosserie",
    "K3AG1": "Schaltung",
    "K3SG1": "Schaltung",
    "K2LE1": "Sitze",
    "K2ST1": "Sitze",
    "K1BE1": "Motor",
    "K1DI1": "Motor",
    "K6": "Karosserie",
    "K3AG2": "Schaltung",
    "K3SG2": "Schaltung",
    "K2LE2": "Sitze",
    "K2ST2": "Sitze",
    "K1BE2": "Motor",
    "K1DI2": "Motor",
}

component_part_types = {
    "K4": ["T30", "T31", "T32"],
    "K3AG1": ["T21", "T24", "T25"],
    "K3SG1": ["T21", "T22", "T23"],
    "K2LE1": ["T11", "T14", "T15"],
    "K2ST1": ["T11", "T12", "T13"],
    "K1BE1": ["T01", "T02", "T03", "T04"],
    "K1DI1": ["T01", "T02", "T05", "T06"],
    "K6": ["T34", "T35", "T36", "T37"],
    "K3AG2": ["T21", "T24", "T27"],
    "K3SG2": ["T21", "T22", "T26"],
    "K2LE2": ["T16", "T19", "T20"],
    "K2ST2": ["T16", "T17", "T18"],
    "K1BE2": ["T01", "T02", "T07", "T08"],
    "K1DI2": ["T01", "T02", "T09", "T10"],
}

comma_separated_files = {
    "Fahrzeuge_OEM1_Typ11.csv",
    "Fahrzeuge_OEM2_Typ21.csv",
    "Komponente_K1BE1.csv",
    "Komponente_K1DI1.csv",
    "Komponente_K3AG1.csv",
    "Komponente_K3SG1.csv",
    "Komponente_K3SG2.csv",
    "Einzelteil_T05.csv",
    "Einzelteil_T06.csv",
    "Einzelteil_T08.csv",
    "Einzelteil_T19.csv",
    "Einzelteil_T25.csv",
    "Einzelteil_T30.csv",
    "Einzelteil_T37.csv",
}

special_text_formats = {
    "Komponente_K1DI2.txt": ("\\", "\t"),
    "Komponente_K2LE1.txt": ("II", "\x0b"),
    "Komponente_K2LE2.txt": ("\\", "\r"),
    "Komponente_K2ST1.txt": ("|", "\r"),
    "Komponente_K3AG2.txt": ("\\", "\r"),
    "Einzelteil_T01.txt": (" | | ", None),
    "Einzelteil_T02.txt": ("  ", "\t"),
    "Einzelteil_T03.txt": ("|", "\x0b"),
    "Einzelteil_T07.txt": ("\t", None),
    "Einzelteil_T09.txt": ("\\", "\x0b"),
    "Einzelteil_T11.txt": ("\t", "\x0c"),
    "Einzelteil_T16.txt": (" | | ", "\t"),
    "Einzelteil_T20.txt": (" | | ", None),
    "Einzelteil_T22.txt": ("\t", None),
    "Einzelteil_T24.txt": ("  ", "\x0c"),
    "Einzelteil_T27.txt": (" | | ", "\x07"),
    "Einzelteil_T31.txt": ("  ", "\x08"),
    "Einzelteil_T34.txt": (" | | ", None),
    "Einzelteil_T35.txt": ("\\", None),
    "Einzelteil_T36.txt": ("  ", None),
}

# Collects corrections and conflicts found during cleaning.
cleaning_log = []

## 4.2 Reading the Raw Source Files

Most files can be read with `pd.read_csv`. The previews showed, however, that several TXT files use unusual field separators and control characters instead of normal line breaks.

`read_special_text_file` reconstructs those files:

- if a record separator is known (for example a vertical tab), the file is split on that character
- if there is no record separator, a new row starts at a quoted numeric index (`"0"`, `"1"`, ...)
- each record is then split into columns with the field separator identified before

`mmap` is used because some of these TXT files are large. It lets us search the file without first copying the whole content into a Python string.

`read_source_file` is the wrapper function that reads in all files. Regular CSV files are read completely and special TXT files go through the dedicated reader function.

In [43]:
def split_special_record(record, field_separator):
    """Split one TXT record into a list of field values.

    The files use different separators, so one split method is not enough.
    After splitting we only strip leftover spaces and quotes.
    """
    # cp1252 because the source files are Windows exports.
    text = record.decode("cp1252", errors="replace").strip()

    if field_separator == "II":
        # Fixed "II" separator, e.g. K2LE1.
        values = text.split("II")
    elif field_separator == " | | ":
        # Number of spaces around the pipes is not always the same.
        values = re.split(r"\s*\|\s*\|\s*", text)
    elif field_separator == "  ":
        # Two or more spaces = new field. A single space can still be inside a value.
        values = re.split(r" {2,}", text)
    else:
        # Backslash, pipe, tab, etc. csv.reader also handles quoted fields.
        values = next(
            csv.reader(
                [text],
                delimiter=field_separator,
                quotechar='"',
                skipinitialspace=True,
            )
        )

    return [value.strip().strip('"') for value in values]


def special_row_boundary(field_separator):
    """Build a regex that finds the start of a new row.

    Some TXT files have no line breaks at all, just one long stream.
    In those files a new row starts at a quoted index like "0", "1", "2", ...

    We cannot search for every quoted number though: the same pattern can also
    appear in the middle of a row. So we only keep a match if it is NOT sitting
    directly after a field separator.

    We also do not require an ID right after the index. In later .x / .y blocks
    the first ID field can be NA, so that would miss real row starts.
    """
    # Bytes patterns, because we search in the mmap.
    if field_separator == " | | ":
        separator_pattern = rb"\s*\|\s*\|\s*"
        not_after_separator = rb"(?<! \| \| )"
    elif field_separator == "  ":
        separator_pattern = rb" {2,}"
        not_after_separator = rb"(?<!  )"
    elif field_separator == "\t":
        separator_pattern = rb"\t"
        not_after_separator = rb"(?<!\t)"
    elif field_separator == "\\":
        separator_pattern = rb"\\"
        not_after_separator = rb"(?<!\\)"
    elif field_separator == "|":
        separator_pattern = rb"\|"
        not_after_separator = rb"(?<!\|)"
    else:
        encoded_separator = re.escape(field_separator.encode("cp1252"))
        separator_pattern = encoded_separator
        not_after_separator = rb"(?<!" + encoded_separator + rb")"

    return re.compile(not_after_separator + rb'(?="\d+"' + separator_pattern + rb")")


def extract_special_records(mapped_file, field_separator, record_separator):
    """Cut the mapped file into one byte-slice per record (header + data rows).

    Two cases:
    1) The file has a record separator (vertical tab, CR, ...): split there.
    2) It does not: search for row starts with special_row_boundary().
    """
    if record_separator is not None:
        separator = record_separator.encode("cp1252")
        start = 0

        # Walk through the file and cut at every separator.
        while True:
            end = mapped_file.find(separator, start)
            if end == -1:
                # Last piece (no separator after it anymore).
                if start < len(mapped_file):
                    yield mapped_file[start:]
                break
            yield mapped_file[start:end]
            start = end + len(separator)

        return

    # No record separator: the whole file is one stream.
    # Each regex match is the start of a data row. Everything before the
    # first match is the header.
    boundary = special_row_boundary(field_separator)
    previous_start = 0
    first_match = True

    for match in boundary.finditer(mapped_file):
        if first_match:
            yield mapped_file[:match.start()]
            first_match = False
        else:
            yield mapped_file[previous_start:match.start()]
        previous_start = match.start()

    if first_match:
        raise ValueError("No data-row boundary could be found.")

    # Last row goes until the end of the file.
    yield mapped_file[previous_start:]


def read_special_text_file(file_path):
    """Read one non-standard TXT file and return it as a DataFrame.

    Steps:
    1) look up the separators for this filename
    2) split the file into records
    3) split each record into fields
    4) check that every row has the same number of columns
    """
    field_separator, record_separator = special_text_formats[file_path.name]

    # mmap to view the file as bytes without copying it into one huge string.
    with file_path.open("rb") as source_file:
        with mmap.mmap(
            source_file.fileno(),
            length=0,
            access=mmap.ACCESS_READ,
        ) as mapped_file:
            records = extract_special_records(
                mapped_file,
                field_separator,
                record_separator,
            )
            # First record is column names, the rest are data rows.
            header = split_special_record(next(records), field_separator)
            rows = [
                split_special_record(record, field_separator)
                for record in records
                if record.strip()
            ]

    # Some files put a row index in the data, but not in the header.
    # Then the first data row is one field longer -> add a dummy column name.
    if rows and len(rows[0]) == len(header) + 1:
        header = ["_Zeilenindex", *header]

    # If a later row has a different width, the separators were probably wrong.
    invalid_rows = [
        row_number
        for row_number, row in enumerate(rows, start=1)
        if len(row) != len(header)
    ]
    if invalid_rows:
        raise ValueError(
            f"Unexpected field count in {file_path.name}; "
            f"first invalid data row: {invalid_rows[0]}"
        )

    return pd.DataFrame(rows, columns=header, dtype="string")


def read_source_file(file_path):
    """Read one complete source file into a DataFrame."""
    if file_path.name in special_text_formats:
        return read_special_text_file(file_path)

    separator = "," if file_path.name in comma_separated_files else ";"
    return pd.read_csv(
        file_path,
        sep=separator,
        encoding="cp1252",
        encoding_errors="replace",
        dtype="string",
        keep_default_na=False,
        low_memory=False,
    )

## 4.3 Recurring Cleaning Steps

The functions below each solve problems that appeared in many files (as seen in the aforementioned table):

- **standardize_raw_values:** strip whitespace and replace empty strings with a real missing value,
- **remove_export_columns:** drop duplicate row counters,
- **combine_duplicate_columns:** merge regular, `.x`, and `.y` columns into one column,
- **standardize_dates:** convert both normal dates and origin-based day counts to `YYYY-MM-DD`,
- **correct_keys_from_id:** take manufacturer and plant number from the structured ID if the explicit columns disagree.

Every correction is written to `cleaning_log`.

In [44]:
def standardize_raw_values(data):
    """Make values comparable: trim spaces and replace missing-value text with pd.NA.

    The files mix empty strings, 'NA', 'NULL', etc. If we leave them as text,
    later joins would treat them as real values.
    """
    cleaned = data.copy()
    cleaned.columns = [str(column).strip() for column in cleaned.columns]

    for column in cleaned.columns:
        cleaned[column] = cleaned[column].astype("string").str.strip()

    missing_markers = {
        "": pd.NA,
        "NA": pd.NA,
        "N/A": pd.NA,
        "NULL": pd.NA,
        "null": pd.NA,
    }
    return cleaned.replace(missing_markers)


def remove_export_columns(data):
    """Drop duplicate row counters."""
    technical_columns = [
        column
        for column in data.columns
        if column in {"X", "X1", "_Zeilenindex"}
        or column.startswith("Unnamed:")
        or column == ""
    ]
    return data.drop(columns=technical_columns, errors="ignore")


def combine_duplicate_columns(data, source_file):
    """Merge columns that exist as name, name.x and name.y into one column.

    Some exports contain the same attribute twice as a .x and a .y version.
    We keep the first non-missing value. If two filled versions disagree,
    we keep the first one and log the conflict in cleaning_log.
    """
    # Unique base names.
    base_columns = []
    for column in data.columns:
        base_column = re.sub(r"\.[xy]$", "", column)
        if base_column not in base_columns:
            base_columns.append(base_column)

    combined = pd.DataFrame(index=data.index)
    conflict_count = 0

    for base_column in base_columns:
        # Take the column without a suffix, then .x, then .y.
        candidates = [
            column
            for column in [base_column, f"{base_column}.x", f"{base_column}.y"]
            if column in data.columns
        ]

        combined_values = pd.Series(pd.NA, index=data.index, dtype="string")
        for candidate in candidates:
            candidate_values = data[candidate].astype("string")
            # It's a conflict when both sides have a different value.
            conflicts = (
                combined_values.notna()
                & candidate_values.notna()
                & combined_values.ne(candidate_values)
            )
            conflict_count += int(conflicts.fillna(False).sum())
            # Empty cells get filled, filled cells stay the same.
            combined_values = combined_values.combine_first(candidate_values)

        combined[base_column] = combined_values

    if conflict_count > 0:
        cleaning_log.append(
            {
                "Quelldatei": source_file,
                "Prüfung": "Conflicting .x/.y values",
                "Anzahl": conflict_count,
            }
        )

    return combined

In [45]:
def standardize_dates(data):
    """Turn all production / defect dates into YYYY-MM-DD.

    Two formats show up:
    - a normal date column (Produktionsdatum)
    - a day count since an origin date (Produktionsdatum_Origin_01011970)

    If both exist, we keep the normal date and only fill gaps from the day count.
    """
    cleaned = data.copy()
    origin_value_column = "Produktionsdatum_Origin_01011970"

    if origin_value_column in cleaned.columns:
        # Day count needs a start date. Some files store it in 'origin',
        # otherwise the column name already says 01.01.1970.
        if "origin" in cleaned.columns:
            origin_dates = pd.to_datetime(
                cleaned["origin"],
                format="%d-%m-%Y",
                errors="coerce",
            )
        else:
            origin_dates = pd.Series(
                pd.Timestamp("1970-01-01"),
                index=cleaned.index,
            )

        day_values = pd.to_numeric(
            cleaned[origin_value_column],
            errors="coerce",
        )
        converted_dates = origin_dates + pd.to_timedelta(day_values, unit="D")

        if "Produktionsdatum" in cleaned.columns:
            existing_dates = pd.to_datetime(
                cleaned["Produktionsdatum"],
                format="mixed",
                errors="coerce",
            )
        else:
            existing_dates = pd.Series(pd.NaT, index=cleaned.index)

        # Take cleaned date column.
        cleaned["Produktionsdatum"] = existing_dates.fillna(converted_dates)
        cleaned = cleaned.drop(
            columns=[origin_value_column, "origin"],
            errors="ignore",
        )

    # One common string format for all date columns.
    for date_column in ["Produktionsdatum", "Fehlerhaft_Datum"]:
        if date_column in cleaned.columns:
            parsed_dates = pd.to_datetime(
                cleaned[date_column],
                format="mixed",
                errors="coerce",
            )
            cleaned[date_column] = parsed_dates.dt.strftime("%Y-%m-%d")

    return cleaned


def correct_keys_from_id(data, id_column, source_file):
    """If Herstellernummer / Werksnummer differs from ID, take the ID.

    We join plants later on Werksnummer, so a wrong plant number would lead to errors in merging. 
    Every overwrite is written to cleaning_log.
    """
    cleaned = data.copy()
    # Group 1 = manufacturer, group 2 = plant. Everything is separated by '-'.
    id_keys = cleaned[id_column].astype("string").str.extract(
        r"^[^-]+-([^-]+)-([^-]+)-"
    )
    id_keys.columns = ["Herstellernummer_ID", "Werksnummer_ID"]

    key_pairs = [
        ("Herstellernummer", "Herstellernummer_ID"),
        ("Werksnummer", "Werksnummer_ID"),
    ]

    for target_column, id_key_column in key_pairs:
        if target_column not in cleaned.columns:
            cleaned[target_column] = pd.NA

        # Remove ".0" leftover in Werk IDs.
        current_values = (
            cleaned[target_column]
            .astype("string")
            .str.replace(r"\.0$", "", regex=True)
        )
        id_values = id_keys[id_key_column].astype("string")
        corrections = (
            id_values.notna()
            & current_values.fillna("").ne(id_values)
        )
        correction_count = int(corrections.sum())

        if correction_count > 0:
            cleaning_log.append(
                {
                    "Quelldatei": source_file,
                    "Prüfung": f"Corrected {target_column} from ID",
                    "Anzahl": correction_count,
                }
            )

        # Overwrite mismatches with the ID segment, then fill remaining gaps.
        cleaned[target_column] = current_values.mask(corrections, id_values)
        cleaned[target_column] = cleaned[target_column].fillna(id_values)

    return cleaned

## 4.4 Plant Data

The OEM, Tier-1, and Tier-2 plant files are cleaned and combined into one common plant table. This table is later used to add location information to vehicles, components, and parts.

- Clean missing values and remove empty columns and incomplete rows.
- Standardise plant numbers, postal codes, and coordinates.
- Add the supply-chain level and source file.
- Combine all plant data into `plants_clean`.

In [46]:
plant_source_files = {
    "OEM": plant_paths["OEM plants"],
    "Tier 1": plant_paths["Tier 1 plants"],
    "Tier 2": plant_paths["Tier 2 plants"],
}

plant_frames = []

for plant_level, file_path in plant_source_files.items():
    cleaned_plant_data = standardize_raw_values(read_source_file(file_path))
    cleaned_plant_data = cleaned_plant_data.dropna(axis=1, how="all")
    # One plant file uses a wrong spelling of Längengrad because of the Umlaut.
    cleaned_plant_data.columns = [
        "Längengrad" if "ngengrad" in column else column
        for column in cleaned_plant_data.columns
    ]
    cleaned_plant_data = cleaned_plant_data.dropna(subset=["Werk", "ORT", "PLZ"])
    cleaned_plant_data["Werksebene"] = plant_level
    cleaned_plant_data["Werksnummer"] = (
        cleaned_plant_data["Werk"].astype("string").str.replace(r"^O", "", regex=True)
    )
    cleaned_plant_data["PLZ"] = (
        cleaned_plant_data["PLZ"].str.replace(r"\.0$", "", regex=True).str.zfill(5)
    )
    cleaned_plant_data["Breitengrad"] = pd.to_numeric(
        cleaned_plant_data["Breitengrad"],
        errors="coerce",
    )
    cleaned_plant_data["Längengrad"] = pd.to_numeric(
        cleaned_plant_data["Längengrad"],
        errors="coerce",
    )
    cleaned_plant_data["Quelldatei"] = file_path.name
    plant_frames.append(cleaned_plant_data)

plants_clean = pd.concat(plant_frames, ignore_index=True)

PLANT_COLUMNS = ["Werksnummer", "Werk", "PLZ", "ORT", "Breitengrad", "Längengrad"]


def plants_by_level(level):
    """Unique plants for one supply-chain level, ready to join."""
    return (
        plants_clean.loc[plants_clean["Werksebene"] == level, PLANT_COLUMNS]
        .drop_duplicates("Werksnummer")
    )


plants_clean.groupby("Werksebene").size().rename("Anzahl_Werke").to_frame()

            Anzahl_Werke
Werksebene
OEM                    5
Tier 1                22
Tier 2                45

## 4.5 Vehicle Data

The vehicle files for Type 11 and Type 21 are cleaned in the same way and combined into one table. The related OEM plant information is also added to each vehicle.

- Remove technical and duplicated columns.
- Standardise dates, IDs, and numeric values.
- Add the vehicle type, OEM, and source file.
- Join the OEM plant data.
- Combine both vehicle types into `vehicles_clean`.

In [47]:
vehicle_raw_data = {
    vehicle_type: read_source_file(file_path)
    for vehicle_type, file_path in vehicle_data_paths.items()
}

oem_plants = plants_by_level("OEM")
vehicle_frames = []

for vehicle_type, raw_vehicle_data in vehicle_raw_data.items():
    source_file = vehicle_data_paths[vehicle_type].name
    cleaned_vehicle_data = standardize_raw_values(raw_vehicle_data)
    cleaned_vehicle_data = remove_export_columns(cleaned_vehicle_data)
    cleaned_vehicle_data = combine_duplicate_columns(
        cleaned_vehicle_data,
        source_file,
    )
    cleaned_vehicle_data = standardize_dates(cleaned_vehicle_data)
    cleaned_vehicle_data = correct_keys_from_id(
        cleaned_vehicle_data,
        "ID_Fahrzeug",
        source_file,
    )
    cleaned_vehicle_data["Fehlerhaft"] = pd.to_numeric(
        cleaned_vehicle_data["Fehlerhaft"],
        errors="coerce",
    ).astype("Int64")
    cleaned_vehicle_data["Fehlerhaft_Fahrleistung"] = pd.to_numeric(
        cleaned_vehicle_data["Fehlerhaft_Fahrleistung"],
        errors="coerce",
    )
    cleaned_vehicle_data["Fahrzeugtyp"] = vehicle_type
    cleaned_vehicle_data["OEM"] = (
        "OEM1" if vehicle_type == "Type 11" else "OEM2"
    )
    cleaned_vehicle_data["Quelldatei"] = source_file
    cleaned_vehicle_data = cleaned_vehicle_data.merge(
        oem_plants,
        on="Werksnummer",
        how="left",
        validate="many_to_one",
    )
    vehicle_frames.append(cleaned_vehicle_data)

vehicles_clean = pd.concat(vehicle_frames, ignore_index=True)
vehicles_clean = vehicles_clean[
    [
        "ID_Fahrzeug",
        "Fahrzeugtyp",
        "OEM",
        "Produktionsdatum",
        "Herstellernummer",
        "Werksnummer",
        "Fehlerhaft",
        "Fehlerhaft_Datum",
        "Fehlerhaft_Fahrleistung",
        "Werk",
        "PLZ",
        "ORT",
        "Breitengrad",
        "Längengrad",
        "Quelldatei",
    ]
]

del vehicle_raw_data, vehicle_frames

vehicles_clean.groupby("Fahrzeugtyp").size().rename("Anzahl_Fahrzeuge").to_frame()

             Anzahl_Fahrzeuge
Fahrzeugtyp
Type 11               1977164
Type 21                512354

## 4.6 Vehicle-Component Mapping

The mapping files show which body, transmission, seats, and engine are installed in each vehicle. The original wide format is changed into a long format with one vehicle-component assignment per row.

- Clean both vehicle-component mapping files.
- Transform the four component columns into separate rows.
- Add the component role and type.
- Combine the results into `vehicle_components_clean`.

In [48]:
vehicle_component_raw_data = {
    vehicle_type: read_source_file(file_path)
    for vehicle_type, file_path in vehicle_mapping_paths.items()
}

vehicle_component_frames = []
component_role_names = {
    "ID_Karosserie": "Karosserie",
    "ID_Schaltung": "Schaltung",
    "ID_Sitze": "Sitze",
    "ID_Motor": "Motor",
}

for vehicle_type, raw_mapping_data in vehicle_component_raw_data.items():
    cleaned_mapping_data = standardize_raw_values(raw_mapping_data)
    cleaned_mapping_data = remove_export_columns(cleaned_mapping_data)
    # One vehicle has four installed components, stored in four wide columns.
    long_mapping_data = cleaned_mapping_data.melt(
        id_vars="ID_Fahrzeug",
        value_vars=list(component_role_names),
        var_name="Komponentenfeld",
        value_name="ID_Komponente",
    )
    long_mapping_data["Komponentenrolle"] = (
        long_mapping_data["Komponentenfeld"].map(component_role_names)
    )
    # Component type is the prefix of the ID, e.g. K4-... becomes K4.
    long_mapping_data["Komponententyp"] = (
        long_mapping_data["ID_Komponente"]
        .astype("string")
        .str.extract(r"^([A-Za-z0-9]+)-", expand=False)
    )
    long_mapping_data["Fahrzeugtyp"] = vehicle_type
    long_mapping_data["Quelldatei"] = vehicle_mapping_paths[vehicle_type].name
    vehicle_component_frames.append(long_mapping_data)

vehicle_components_clean = pd.concat(
    vehicle_component_frames,
    ignore_index=True,
)
vehicle_components_clean = vehicle_components_clean[
    [
        "ID_Fahrzeug",
        "Fahrzeugtyp",
        "Komponentenrolle",
        "Komponententyp",
        "ID_Komponente",
        "Quelldatei",
    ]
]

del vehicle_component_raw_data, vehicle_component_frames

vehicle_components_clean.groupby(
    ["Fahrzeugtyp", "Komponentenrolle"]
).size().rename("Anzahl_Zuordnungen").to_frame()

                              Anzahl_Zuordnungen
Fahrzeugtyp Komponentenrolle
Type 11     Karosserie                   1977164
            Motor                        1977164
            Schaltung                    1977164
            Sitze                        1977164
Type 21     Karosserie                    512354
            Motor                         512354
            Schaltung                     512354
            Sitze                         512354

## 4.7 Component Data

All 14 relevant component files are cleaned and combined into one component table. Each component is also connected to its Tier-1 production plant.

- Clean all component files.
- Standardise columns, dates, IDs, and numeric values.
- Combine rows with duplicate component IDs.
- Add the component type, role, and Tier-1 plant data.
- Combine all files into `components_clean`.

In [49]:
tier_1_plants = plants_by_level("Tier 1")

component_frames = []

for component_type, component_role in component_configuration.items():
    source_file = component_paths[f"{component_type} production"]
    raw_component_data = read_source_file(source_file)
    cleaned_component_data = standardize_raw_values(raw_component_data)
    cleaned_component_data = remove_export_columns(cleaned_component_data)
    cleaned_component_data = combine_duplicate_columns(
        cleaned_component_data,
        source_file.name,
    )

    component_id_columns = [
        column
        for column in cleaned_component_data.columns
        if column.startswith("ID_")
    ]
    if len(component_id_columns) != 1:
        raise ValueError(
            f"Expected one component ID column in {source_file.name}."
        )

    component_id_column = component_id_columns[0]
    cleaned_component_data = standardize_dates(cleaned_component_data)
    cleaned_component_data = correct_keys_from_id(
        cleaned_component_data,
        component_id_column,
        source_file.name,
    )
    cleaned_component_data["Fehlerhaft"] = pd.to_numeric(
        cleaned_component_data["Fehlerhaft"],
        errors="coerce",
    ).astype("Int64")
    cleaned_component_data["Fehlerhaft_Fahrleistung"] = pd.to_numeric(
        cleaned_component_data["Fehlerhaft_Fahrleistung"],
        errors="coerce",
    )

    duplicate_component_rows = cleaned_component_data.duplicated(
        component_id_column,
        keep=False,
    )
    if duplicate_component_rows.any():
        cleaning_log.append(
            {
                "Quelldatei": source_file.name,
                "Prüfung": "Duplicate component rows consolidated",
                "Anzahl": int(duplicate_component_rows.sum()),
            }
        )
        # If the same component ID appears twice, keep a defect if any copy is defective.
        component_aggregation = {
            column: "max" if column == "Fehlerhaft" else "first"
            for column in cleaned_component_data.columns
            if column != component_id_column
        }
        cleaned_component_data = cleaned_component_data.groupby(
            component_id_column,
            as_index=False,
            dropna=False,
        ).agg(component_aggregation)

    cleaned_component_data = cleaned_component_data.rename(
        columns={component_id_column: "ID_Komponente"}
    )
    cleaned_component_data["Komponententyp"] = component_type
    cleaned_component_data["Komponentenrolle"] = component_role
    cleaned_component_data["Quelldatei"] = source_file.name
    cleaned_component_data = cleaned_component_data.merge(
        tier_1_plants,
        on="Werksnummer",
        how="left",
        validate="many_to_one",
    )
    component_frames.append(cleaned_component_data)

components_clean = pd.concat(component_frames, ignore_index=True)
components_clean = components_clean[
    [
        "ID_Komponente",
        "Komponententyp",
        "Komponentenrolle",
        "Produktionsdatum",
        "Herstellernummer",
        "Werksnummer",
        "Fehlerhaft",
        "Fehlerhaft_Datum",
        "Fehlerhaft_Fahrleistung",
        "Werk",
        "PLZ",
        "ORT",
        "Breitengrad",
        "Längengrad",
        "Quelldatei",
    ]
]

del component_frames, raw_component_data

components_clean.groupby("Komponententyp").size().rename(
    "Anzahl_Komponenten"
).to_frame()

                Anzahl_Komponenten
Komponententyp
K1BE1                      1192630
K1BE2                       409422
K1DI1                      1192630
K1DI2                       409422
K2LE1                       477052
K2LE2                       163769
K2ST1                      1908208
K2ST2                       655075
K3AG1                       477052
K3AG2                       163769
K3SG1                      1908208
K3SG2                       655075
K4                         1977164
K6                          512354

## 4.8 Component-Part Mapping

The component-part files show which individual parts are installed in each component. They are transformed into one table with one component-part assignment per row.

- Clean the component-part mapping files.
- Select the expected part columns for each component type.
- Transform the part columns into separate rows.
- Combine the assignments into `component_parts_clean`.

In [50]:
component_part_frames = []

for component_type, expected_part_types in component_part_types.items():
    source_file = component_paths[f"{component_type} mapping"]
    raw_component_part_data = read_source_file(source_file)
    cleaned_component_part_data = standardize_raw_values(
        raw_component_part_data
    )
    cleaned_component_part_data = remove_export_columns(
        cleaned_component_part_data
    )
    component_id_column = f"ID_{component_type}"

    if component_id_column not in cleaned_component_part_data.columns:
        raise ValueError(
            f"Missing {component_id_column} in {source_file.name}."
        )

    for part_type in expected_part_types:
        # Column names are not fully consistent (ID_T1 vs ID_T01).
        part_number = int(part_type[1:])
        possible_names = [f"ID_T{part_number:02d}", f"ID_T{part_number}"]
        part_columns = [
            column
            for column in dict.fromkeys(possible_names)
            if column in cleaned_component_part_data.columns
        ]

        if len(part_columns) != 1:
            raise ValueError(
                f"Could not identify {part_type} in {source_file.name}."
            )

        component_part_data = cleaned_component_part_data[
            [component_id_column, part_columns[0]]
        ].rename(
            columns={
                component_id_column: "ID_Komponente",
                part_columns[0]: "ID_Einzelteil",
            }
        )
        component_part_data["Komponententyp"] = component_type
        component_part_data["Einzelteiltyp"] = part_type
        component_part_data["Quelldatei"] = source_file.name
        component_part_frames.append(component_part_data)

component_parts_clean = pd.concat(
    component_part_frames,
    ignore_index=True,
)
component_parts_clean = component_parts_clean[
    [
        "ID_Komponente",
        "Komponententyp",
        "ID_Einzelteil",
        "Einzelteiltyp",
        "Quelldatei",
    ]
]

del component_part_frames, raw_component_part_data

component_parts_clean.groupby("Komponententyp").size().rename(
    "Anzahl_Einzelteilzuordnungen"
).to_frame()

                Anzahl_Einzelteilzuordnungen
Komponententyp
K1BE1                                4770520
K1BE2                                1637688
K1DI1                                4770520
K1DI2                                1637688
K2LE1                                1431156
K2LE2                                 491307
K2ST1                                5724624
K2ST2                                1965225
K3AG1                                1431156
K3AG2                                 491307
K3SG1                                5724624
K3SG2                                1965225
K4                                   5931492
K6                                   2049416

## 4.9 Part Data

All relevant part files are cleaned and combined into one common table. Each part is also connected to its Tier-2 production plant.

- Clean all relevant part files.
- Standardise columns, dates, IDs, and numeric values.
- Combine rows with duplicate part IDs.
- Add the part type and Tier-2 plant data.
- Combine all files into `parts_clean`.

In [51]:
tier_2_plants = plants_by_level("Tier 2")

part_frames = []

for part_type, source_file in part_paths.items():
    raw_part_data = read_source_file(source_file)
    cleaned_part_data = standardize_raw_values(raw_part_data)
    cleaned_part_data = remove_export_columns(cleaned_part_data)
    cleaned_part_data = combine_duplicate_columns(
        cleaned_part_data,
        source_file.name,
    )

    part_id_columns = [
        column
        for column in cleaned_part_data.columns
        if column.startswith("ID_")
    ]
    if len(part_id_columns) != 1:
        raise ValueError(
            f"Expected one part ID column in {source_file.name}."
        )

    part_id_column = part_id_columns[0]
    cleaned_part_data = standardize_dates(cleaned_part_data)
    cleaned_part_data = correct_keys_from_id(
        cleaned_part_data,
        part_id_column,
        source_file.name,
    )
    cleaned_part_data["Fehlerhaft"] = pd.to_numeric(
        cleaned_part_data["Fehlerhaft"],
        errors="coerce",
    ).astype("Int64")
    cleaned_part_data["Fehlerhaft_Fahrleistung"] = pd.to_numeric(
        cleaned_part_data["Fehlerhaft_Fahrleistung"],
        errors="coerce",
    )

    duplicate_part_rows = cleaned_part_data.duplicated(
        part_id_column,
        keep=False,
    )
    if duplicate_part_rows.any():
        cleaning_log.append(
            {
                "Quelldatei": source_file.name,
                "Prüfung": "Duplicate part rows consolidated",
                "Anzahl": int(duplicate_part_rows.sum()),
            }
        )
        # If the same part ID appears twice, keep a defect if any copy is defective.
        part_aggregation = {
            column: "max" if column == "Fehlerhaft" else "first"
            for column in cleaned_part_data.columns
            if column != part_id_column
        }
        cleaned_part_data = cleaned_part_data.groupby(
            part_id_column,
            as_index=False,
            dropna=False,
        ).agg(part_aggregation)

    cleaned_part_data = cleaned_part_data.rename(
        columns={part_id_column: "ID_Einzelteil"}
    )
    cleaned_part_data["Einzelteiltyp"] = part_type
    cleaned_part_data["Quelldatei"] = source_file.name
    cleaned_part_data = cleaned_part_data.merge(
        tier_2_plants,
        on="Werksnummer",
        how="left",
        validate="many_to_one",
    )
    part_frames.append(cleaned_part_data)

parts_clean = pd.concat(part_frames, ignore_index=True)
parts_clean = parts_clean[
    [
        "ID_Einzelteil",
        "Einzelteiltyp",
        "Produktionsdatum",
        "Herstellernummer",
        "Werksnummer",
        "Fehlerhaft",
        "Fehlerhaft_Datum",
        "Fehlerhaft_Fahrleistung",
        "Werk",
        "PLZ",
        "ORT",
        "Breitengrad",
        "Längengrad",
        "Quelldatei",
    ]
]

del part_frames, raw_part_data

parts_clean.groupby("Einzelteiltyp").size().rename(
    "Anzahl_Einzelteile"
).to_frame()

               Anzahl_Einzelteile
Einzelteiltyp
T01                       3204104
T02                       3204104
T03                       1192630
T04                       1192630
T05                       1192630
T06                       1192630
T07                        409422
T08                        409422
T09                        409422
T10                        409422
T11                       2385260
T12                       1908208
T13                       1908208
T14                        477052
T15                        477052
T16                        818844
T17                        655075
T18                        655075
T19                        163769
T20                        163769
T21                       3204104
T22                       2563283
T23                       1908208
T24                        640821
T25                        477052
T26                        655075
T27                        163769
T30                       2385260
T31                       2385260
T32                       1977164
T34                        818844
T35                        818844
T36                        512354
T37                        512354

## 4.10 Intermediate Checks

Before the tables are joined, their basic structure is checked. This ensures that the main IDs are complete and unique and that every vehicle has the expected number of components.

- Show the size and missing keys of the six cleaned tables.
- Check that vehicle, component, and part IDs are unique.
- Check that every vehicle has four components.

In [52]:
intermediate_table_summary = pd.DataFrame(
    [
        {
            "Table": "plants_clean",
            "Rows": len(plants_clean),
            "Main key": "Werksebene + Werksnummer",
            "Missing main key": int(plants_clean["Werksnummer"].isna().sum()),
        },
        {
            "Table": "vehicles_clean",
            "Rows": len(vehicles_clean),
            "Main key": "ID_Fahrzeug",
            "Missing main key": int(vehicles_clean["ID_Fahrzeug"].isna().sum()),
        },
        {
            "Table": "vehicle_components_clean",
            "Rows": len(vehicle_components_clean),
            "Main key": "ID_Fahrzeug + ID_Komponente",
            "Missing main key": int(
                vehicle_components_clean[
                    ["ID_Fahrzeug", "ID_Komponente"]
                ].isna().any(axis=1).sum()
            ),
        },
        {
            "Table": "components_clean",
            "Rows": len(components_clean),
            "Main key": "ID_Komponente",
            "Missing main key": int(components_clean["ID_Komponente"].isna().sum()),
        },
        {
            "Table": "component_parts_clean",
            "Rows": len(component_parts_clean),
            "Main key": "ID_Komponente + ID_Einzelteil",
            "Missing main key": int(
                component_parts_clean[
                    ["ID_Komponente", "ID_Einzelteil"]
                ].isna().any(axis=1).sum()
            ),
        },
        {
            "Table": "parts_clean",
            "Rows": len(parts_clean),
            "Main key": "ID_Einzelteil",
            "Missing main key": int(parts_clean["ID_Einzelteil"].isna().sum()),
        },
    ]
)

assert not vehicles_clean["ID_Fahrzeug"].duplicated().any()
assert not components_clean["ID_Komponente"].duplicated().any()
assert not parts_clean["ID_Einzelteil"].duplicated().any()
assert (
    vehicle_components_clean.groupby("ID_Fahrzeug").size().eq(4).all()
)

intermediate_table_summary

,Table,Rows,Main key,Missing main key
0,plants_clean,72,Werksebene + Werksnummer,0
1,vehicles_clean,2489518,ID_Fahrzeug,0
2,vehicle_components_clean,9958072,ID_Fahrzeug + ID_Komponente,0
3,components_clean,12101830,ID_Komponente,0
4,component_parts_clean,40021948,ID_Komponente + ID_Einzelteil,0
5,parts_clean,41451120,ID_Einzelteil,0

## 4.11 Detailed Quality Trace

The cleaned tables are joined to create the complete path from each vehicle to its components and individual parts. The result can later be used to investigate the exact source of a defect.

- Add suffixes to separate vehicle, component, and part columns.
- Join vehicles with their installed components.
- Add the related parts and their master data.
- Store the result in `quality_trace_clean`.

In [53]:
LEVEL_COLUMNS = [
    "Produktionsdatum",
    "Herstellernummer",
    "Werksnummer",
    "Fehlerhaft",
    "Fehlerhaft_Datum",
    "Fehlerhaft_Fahrleistung",
    "Werk",
    "PLZ",
    "ORT",
    "Breitengrad",
    "Längengrad",
]


def add_level_suffix(data, suffix):
    """Add a suffix so vehicle, component, and part fields stay distinguishable."""
    return data.rename(columns={column: f"{column}_{suffix}" for column in LEVEL_COLUMNS})


vehicle_trace_data = add_level_suffix(vehicles_clean, "Fahrzeug").drop(columns="Quelldatei")
component_trace_data = add_level_suffix(components_clean, "Komponente").drop(columns="Quelldatei")
part_trace_data = add_level_suffix(parts_clean, "Einzelteil").drop(columns="Quelldatei")

quality_trace_clean = vehicle_components_clean.drop(columns="Quelldatei").merge(
    vehicle_trace_data,
    on=["ID_Fahrzeug", "Fahrzeugtyp"],
    how="left",
    validate="many_to_one",
)

quality_trace_clean = quality_trace_clean.merge(
    component_trace_data,
    on=["ID_Komponente", "Komponententyp", "Komponentenrolle"],
    how="left",
    validate="many_to_one",
)

quality_trace_clean = quality_trace_clean.merge(
    component_parts_clean.drop(columns="Quelldatei"),
    on=["ID_Komponente", "Komponententyp"],
    how="left",
    validate="one_to_many",
)

quality_trace_clean = quality_trace_clean.merge(
    part_trace_data,
    on=["ID_Einzelteil", "Einzelteiltyp"],
    how="left",
    validate="many_to_one",
)

quality_trace_clean.head()

,ID_Fahrzeug,Fahrzeugtyp,Komponentenrolle,Komponententyp,ID_Komponente,OEM,Produktionsdatum_Fahrzeug,Herstellernummer_Fahrzeug,Werksnummer_Fahrzeug,Fehlerhaft_Fahrzeug,Fehlerhaft_Datum_Fahrzeug,Fehlerhaft_Fahrleistung_Fahrzeug,Werk_Fahrzeug,PLZ_Fahrzeug,ORT_Fahrzeug,...,Breitengrad_Komponente,Längengrad_Komponente,ID_Einzelteil,Einzelteiltyp,Produktionsdatum_Einzelteil,Herstellernummer_Einzelteil,Werksnummer_Einzelteil,Fehlerhaft_Einzelteil,Fehlerhaft_Datum_Einzelteil,Fehlerhaft_Fahrleistung_Einzelteil,Werk_Einzelteil,PLZ_Einzelteil,ORT_Einzelteil,Breitengrad_Einzelteil,Längengrad_Einzelteil
0,11-1-11-1,Type 11,Karosserie,K4,K4-112-1121-3,OEM1,2008-11-18,1,11,0,NaN,0,O11,90491,NUERNBERG,...,52.25431,10.490542,30-217-2171-214,T30,2008-11-07,217,2171,0,NaN,0.0,2171,78048,VILLINGEN-SCHWENNINGEN,47.708784,10.32755
1,11-1-11-1,Type 11,Karosserie,K4,K4-112-1121-3,OEM1,2008-11-18,1,11,0,NaN,0,O11,90491,NUERNBERG,...,52.25431,10.490542,31-217-2172-53,T31,2008-11-07,217,2172,0,NaN,0.0,2172,77656,OFFENBURG,48.439867,7.930517
2,11-1-11-1,Type 11,Karosserie,K4,K4-112-1121-3,OEM1,2008-11-18,1,11,0,NaN,0,O11,90491,NUERNBERG,...,52.25431,10.490542,32-216-2162-62,T32,2008-11-07,216,2162,0,NaN,0.0,2162,87437,KEMPTEN,47.708784,10.32755
3,11-1-11-2,Type 11,Karosserie,K4,K4-112-1121-4,OEM1,2008-11-18,1,11,0,NaN,0,O11,90491,NUERNBERG,...,52.25431,10.490542,30-216-2161-144,T30,2008-11-07,216,2161,0,NaN,0.0,2161,83022,ROSENHEIM,47.851296,12.140443
4,11-1-11-2,Type 11,Karosserie,K4,K4-112-1121-4,OEM1,2008-11-18,1,11,0,NaN,0,O11,90491,NUERNBERG,...,52.25431,10.490542,31-217-2172-139,T31,2008-11-07,217,2172,0,NaN,0.0,2172,77656,OFFENBURG,48.439867,7.930517

## 4.12 Vehicle-Level Quality Table

The detailed trace contains several rows for each vehicle. Therefore, the defect information is grouped into one final quality result per vehicle.

- Calculate component defects for each vehicle.
- Calculate part defects for each vehicle.
- Combine them with the vehicle defect status.
- Create the overall three-state defect flag.
- Store one row per vehicle in `vehicle_quality_clean`.

In [54]:
# Count each installed component once. The trace table would count the same
# component several times because it contains several parts.
installed_component_quality = vehicle_components_clean[
    ["ID_Fahrzeug", "ID_Komponente"]
].merge(
    components_clean[["ID_Komponente", "Fehlerhaft"]].rename(
        columns={"Fehlerhaft": "Fehlerhaft_Komponente_Roh"}
    ),
    on="ID_Komponente",
    how="left",
    validate="many_to_one",
)

installed_component_quality["Komponente_Ist_Fehlerhaft"] = pd.to_numeric(
    installed_component_quality["Fehlerhaft_Komponente_Roh"],
    errors="coerce",
).eq(1)
installed_component_quality["Komponentenstatus_Unbekannt"] = (
    installed_component_quality["Fehlerhaft_Komponente_Roh"].isna()
)

component_quality_by_vehicle = installed_component_quality.groupby(
    "ID_Fahrzeug",
    as_index=False,
).agg(
    Komponente_Hat_Fehler=("Komponente_Ist_Fehlerhaft", "max"),
    Komponentenstatus_Unbekannt=("Komponentenstatus_Unbekannt", "max"),
    Anzahl_Fehlerhafte_Komponenten=("Komponente_Ist_Fehlerhaft", "sum"),
)

part_quality_source = quality_trace_clean[
    ["ID_Fahrzeug", "Fehlerhaft_Einzelteil"]
].copy()
part_quality_source["Einzelteil_Ist_Fehlerhaft"] = pd.to_numeric(
    part_quality_source["Fehlerhaft_Einzelteil"],
    errors="coerce",
).eq(1)
part_quality_source["Einzelteilstatus_Unbekannt"] = (
    part_quality_source["Fehlerhaft_Einzelteil"].isna()
)

part_quality_by_vehicle = part_quality_source.groupby(
    "ID_Fahrzeug",
    as_index=False,
).agg(
    Einzelteil_Hat_Fehler=("Einzelteil_Ist_Fehlerhaft", "max"),
    Einzelteilstatus_Unbekannt=("Einzelteilstatus_Unbekannt", "max"),
    Anzahl_Fehlerhafte_Einzelteile=("Einzelteil_Ist_Fehlerhaft", "sum"),
)

vehicle_quality_clean = vehicles_clean.rename(
    columns={"Fehlerhaft": "Fehlerhaft_Fahrzeug"}
).merge(
    component_quality_by_vehicle,
    on="ID_Fahrzeug",
    how="left",
    validate="one_to_one",
).merge(
    part_quality_by_vehicle,
    on="ID_Fahrzeug",
    how="left",
    validate="one_to_one",
)


def three_state_flag(has_defect, has_unknown):
    """1 = confirmed defect, 0 = all OK, <NA> = incomplete but no confirmed defect."""
    flag = pd.Series(0, index=has_defect.index, dtype="Int64")
    flag = flag.mask(~has_defect & has_unknown, pd.NA)
    flag = flag.mask(has_defect, 1)
    return flag


vehicle_quality_clean["Fehlerhaft_Komponente"] = three_state_flag(
    vehicle_quality_clean["Komponente_Hat_Fehler"],
    vehicle_quality_clean["Komponentenstatus_Unbekannt"],
)
vehicle_quality_clean["Fehlerhaft_Einzelteil"] = three_state_flag(
    vehicle_quality_clean["Einzelteil_Hat_Fehler"],
    vehicle_quality_clean["Einzelteilstatus_Unbekannt"],
)

vehicle_defect = pd.to_numeric(vehicle_quality_clean["Fehlerhaft_Fahrzeug"], errors="coerce")
component_defect = pd.to_numeric(vehicle_quality_clean["Fehlerhaft_Komponente"], errors="coerce")
part_defect = pd.to_numeric(vehicle_quality_clean["Fehlerhaft_Einzelteil"], errors="coerce")

confirmed_defect = (
    vehicle_defect.eq(1) | component_defect.eq(1) | part_defect.eq(1)
).fillna(False)
unknown_status = (
    vehicle_defect.isna() | component_defect.isna() | part_defect.isna()
)

vehicle_quality_clean["Fehlerhaft_Gesamt"] = three_state_flag(
    confirmed_defect,
    unknown_status,
)
vehicle_quality_clean["Datenstatus"] = np.where(
    unknown_status,
    "Teilweise unbekannt",
    "Vollständig",
)

vehicle_quality_clean = vehicle_quality_clean.drop(
    columns=[
        "Komponente_Hat_Fehler",
        "Komponentenstatus_Unbekannt",
        "Einzelteil_Hat_Fehler",
        "Einzelteilstatus_Unbekannt",
    ]
)

vehicle_quality_clean.head()

,ID_Fahrzeug,Fahrzeugtyp,OEM,Produktionsdatum,Herstellernummer,Werksnummer,Fehlerhaft_Fahrzeug,Fehlerhaft_Datum,Fehlerhaft_Fahrleistung,Werk,PLZ,ORT,Breitengrad,Längengrad,Quelldatei,Anzahl_Fehlerhafte_Komponenten,Anzahl_Fehlerhafte_Einzelteile,Fehlerhaft_Komponente,Fehlerhaft_Einzelteil,Fehlerhaft_Gesamt,Datenstatus
0,11-1-11-1,Type 11,OEM1,2008-11-18,1,11,0,NaN,0,O11,90491,NUERNBERG,49.46699,11.107353,Fahrzeuge_OEM1_Typ11.csv,1,2,1,1,1,Vollständig
1,11-1-11-2,Type 11,OEM1,2008-11-18,1,11,0,NaN,0,O11,90491,NUERNBERG,49.46699,11.107353,Fahrzeuge_OEM1_Typ11.csv,1,3,1,1,1,Vollständig
2,11-1-11-3,Type 11,OEM1,2008-11-19,1,11,0,NaN,0,O11,90491,NUERNBERG,49.46699,11.107353,Fahrzeuge_OEM1_Typ11.csv,0,1,0,1,1,Vollständig
3,11-1-11-4,Type 11,OEM1,2008-11-19,1,11,0,NaN,0,O11,90491,NUERNBERG,49.46699,11.107353,Fahrzeuge_OEM1_Typ11.csv,0,3,0,1,1,Vollständig
4,11-1-11-5,Type 11,OEM1,2008-11-19,1,11,0,NaN,0,O11,90491,NUERNBERG,49.46699,11.107353,Fahrzeuge_OEM1_Typ11.csv,1,2,1,1,1,Vollständig

## 4.13 Final Validation

The final tables are checked before they are exported. These checks ensure that the expected number of vehicles and trace rows is present and that important IDs are complete.

- Compare the actual and expected vehicle counts.
- Check that every vehicle ID is unique.
- Check the expected number of trace rows.
- Check that important IDs are not missing.

In [55]:
expected_vehicle_counts = {
    "Type 11": 1_977_164,
    "Type 21": 512_354,
}
expected_trace_rows = (
    expected_vehicle_counts["Type 11"] * 13
    + expected_vehicle_counts["Type 21"] * 14
)

actual_vehicle_counts = (
    vehicle_quality_clean.groupby("Fahrzeugtyp").size().to_dict()
)
trace_rows_by_vehicle_type = (
    quality_trace_clean.groupby("Fahrzeugtyp").size().to_dict()
)

assert actual_vehicle_counts == expected_vehicle_counts
assert not vehicle_quality_clean["ID_Fahrzeug"].duplicated().any()
assert len(quality_trace_clean) == expected_trace_rows
assert quality_trace_clean["ID_Fahrzeug"].notna().all()
assert quality_trace_clean["ID_Komponente"].notna().all()
assert quality_trace_clean["ID_Einzelteil"].notna().all()

final_validation = pd.DataFrame(
    [
        {
            "Check": "Vehicle Type 11 rows",
            "Expected": expected_vehicle_counts["Type 11"],
            "Actual": actual_vehicle_counts["Type 11"],
            "Passed": True,
        },
        {
            "Check": "Vehicle Type 21 rows",
            "Expected": expected_vehicle_counts["Type 21"],
            "Actual": actual_vehicle_counts["Type 21"],
            "Passed": True,
        },
        {
            "Check": "Detailed trace rows",
            "Expected": expected_trace_rows,
            "Actual": len(quality_trace_clean),
            "Passed": True,
        },
        {
            "Check": "Unique vehicle IDs",
            "Expected": len(vehicle_quality_clean),
            "Actual": vehicle_quality_clean["ID_Fahrzeug"].nunique(),
            "Passed": True,
        },
    ]
)

final_validation

                  Check  Expected    Actual  Passed
0  Vehicle Type 11 rows   1977164   1977164    True
1  Vehicle Type 21 rows    512354    512354    True
2   Detailed trace rows  32876088  32876088    True
3    Unique vehicle IDs   2489518   2489518    True

## 4.14 Export of Clean Data

All six intermediate tables and both final tables are written as UTF-8 CSV files in `data/cleaned`.

For the later audit decision, `vehicle_quality_clean` is the main table because it contains one row per vehicle with plant and defect information. `quality_trace_clean` is used to investigate individual vehicles, components, or parts in more detail.

- Collect the six intermediate and two final tables.
- Export them as UTF-8 CSV files to `data/cleaned`.
- Export the cleaning log.
- Create a short export summary.

In [56]:
clean_tables = {
    "vehicles_clean.csv": vehicles_clean,
    "vehicle_components_clean.csv": vehicle_components_clean,
    "components_clean.csv": components_clean,
    "component_parts_clean.csv": component_parts_clean,
    "parts_clean.csv": parts_clean,
    "plants_clean.csv": plants_clean,
    "quality_trace_clean.csv": quality_trace_clean,
    "vehicle_quality_clean.csv": vehicle_quality_clean,
}

# Write UTF-8 CSV files so the clean tables can be reused without repeating the import.
for file_name, clean_table in clean_tables.items():
    clean_table.to_csv(
        CLEAN_DIRECTORY / file_name,
        index=False,
        encoding="utf-8",
    )

cleaning_log_table = pd.DataFrame(cleaning_log)
cleaning_log_table.to_csv(
    CLEAN_DIRECTORY / "cleaning_log.csv",
    index=False,
    encoding="utf-8",
)

export_summary = pd.DataFrame(
    [
        {
            "Table": file_name.removesuffix(".csv"),
            "Rows": len(clean_table),
            "Output file": (CLEAN_DIRECTORY / file_name).relative_to(
                PROJECT_ROOT
            ).as_posix(),
        }
        for file_name, clean_table in clean_tables.items()
    ]
)

export_summary

,Table,Rows,Output file
0,vehicles_clean,2489518,data/cleaned/vehicles_clean.csv
1,vehicle_components_clean,9958072,data/cleaned/vehicle_components_clean.csv
2,components_clean,12101830,data/cleaned/components_clean.csv
3,component_parts_clean,40021948,data/cleaned/component_parts_clean.csv
4,parts_clean,41451120,data/cleaned/parts_clean.csv
5,plants_clean,72,data/cleaned/plants_clean.csv
6,quality_trace_clean,32876088,data/cleaned/quality_trace_clean.csv
7,vehicle_quality_clean,2489518,data/cleaned/vehicle_quality_clean.csv